"use strict";this.default_uiframehook=this.default_uiframehook||{};(function(_){var window=this;
try{
_.aa=_.aa||{};_.h=this;_.ba="closure_uid_"+(1E9*Math.random()>>>0);_.k=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
try{
var ca,da;_.m=function(a){return void 0!==a};ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};da=function(a,b,c){return a.call.apply(a.bind,arguments)};
_.ea=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.p=function(a,b){function c(){}c.prototype=b.prototype;a.w=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.uf=function(a,c,f){for(var l=Array(arguments.length-2),n=2;n<arguments.length;n++)l[n-2]=arguments[n];return b.prototype[c].apply(a,l)}};_.fa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};
_.q=function(a,b,c){_.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?da:ca;return _.q.apply(null,arguments)};_.ga=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.ha=function(a){return"function"==_.ea(a)};_.ja=function(a){return"number"==typeof a};_.r=function(a){return"string"==typeof a};_.u=function(a){return"array"==_.ea(a)};_.ka=function(a){a.S=function(){return a.Qc?a.Qc:a.Qc=new a}};_.la=function(){}; _.ma=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.ma);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.p(_.ma,Error);_.ma.prototype.name="CustomError";
var na,oa;na=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
_.pa=function(a,b){for(var c=0,d=na(String(a)).split("."),e=na(String(b)).split("."),f=Math.max(d.length,e.length),l=0;0==c&&l<f;l++){var n=d[l]||"",t=e[l]||"",w=RegExp("(\\d*)(\\D*)","g"),P=RegExp("(\\d*)(\\D*)","g");do{var ia=w.exec(n)||["","",""],va=P.exec(t)||["","",""];if(0==ia[0].length&&0==va[0].length)break;c=oa(0==ia[1].length?0:(0,window.parseInt)(ia[1],10),0==va[1].length?0:(0,window.parseInt)(va[1],10))||oa(0==ia[2].length,0==va[2].length)||oa(ia[2],va[2])}while(0==c)}return c}; oa=function(a,b){return a<b?-1:a>b?1:0};
_.v=Array.prototype;_.qa=_.v.indexOf?function(a,b,c){return _.v.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.r(a))return _.r(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.ra=_.v.lastIndexOf?function(a,b,c){return _.v.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(_.r(a))return _.r(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.x=_.v.forEach?function(a,b,c){_.v.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.r(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.sa=_.v.filter?function(a,b,c){return _.v.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,l=_.r(a)?a.split(""):a,n=0;n<d;n++)if(n in l){var t=l[n];b.call(c,t,n,a)&&(e[f++]=t)}return e};_.ta=_.v.map?function(a,b,c){return _.v.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.r(a)?a.split(""):a,l=0;l<d;l++)l in f&&(e[l]=b.call(c,f[l],l,a));return e};
_.ua=_.v.reduce?function(a,b,c,d){d&&(b=(0,_.q)(b,d));return _.v.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,_.x)(a,function(c,l){e=b.call(d,e,c,l,a)});return e};_.wa=_.v.some?function(a,b,c){return _.v.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.r(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.xa=function(a,b){var c=(0,_.qa)(a,b),d;(d=0<=c)&&_.v.splice.call(a,c,1);return d};
_.ya=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;t:{var Aa=_.h.navigator;if(Aa){var Ba=Aa.userAgent;if(Ba){_.za=Ba;break t}}_.za=""}_.Ca=function(a){return-1!=_.za.indexOf(a)};var Da=function(a){_.h.setTimeout(function(){throw a;},0)},Ea,Fa=function(){var a=_.h.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(a=function(){var a=window.document.createElement("iframe");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,
a=(0,_.q)(function(a){if(("*"==d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.Ca("Trident")&&!_.Ca("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.m(c.next)){c=c.next;var a=c.yc;c.yc=null;a()}};return function(a){d.next={yc:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("script")? function(a){var b=window.document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.h.setTimeout(a,0)}};
var La=function(a,b){Ga||Ha();Ia||(Ga(),Ia=!0);Ja.push(new Ka(a,b))},Ga,Ha=function(){if(_.h.Promise&&_.h.Promise.resolve){var a=_.h.Promise.resolve();Ga=function(){a.then(Ma)}}else Ga=function(){var a=Ma;!_.ha(_.h.setImmediate)||_.h.Window&&_.h.Window.prototype.setImmediate==_.h.setImmediate?(Ea||(Ea=Fa()),Ea(a)):_.h.setImmediate(a)}},Ia=!1,Ja=[],Ma=function(){for(;Ja.length;){var a=Ja;Ja=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.a.call(c.b)}catch(d){Da(d)}}}Ia=!1},Ka=function(a,b){this.a= a;this.b=b};
_.Na="StopIteration"in _.h?_.h.StopIteration:Error("e");var Oa,Ra,Sa,Va,Xa,Ya,Za,ab;Oa=_.Ca("Opera")||_.Ca("OPR");_.Pa=_.Ca("Trident")||_.Ca("MSIE");_.Qa=_.Ca("Gecko")&&-1==_.za.toLowerCase().indexOf("webkit")&&!(_.Ca("Trident")||_.Ca("MSIE"));Ra=-1!=_.za.toLowerCase().indexOf("webkit");Sa=_.h.navigator||null;_.Ta=Sa&&Sa.platform||"";_.Ua=_.Ca("Macintosh");Va=_.h.navigator||null;_.Wa=!!Va&&-1!=(Va.appVersion||"").indexOf("X11");Xa=function(){var a=_.h.document;return a?a.documentMode:void 0};
Ya=function(){var a="",b;if(Oa&&_.h.opera)return a=_.h.opera.version,_.ha(a)?a():a;_.Qa?b=/rv\:([^\);]+)(\)|;)/:_.Pa?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:Ra&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(_.za))?a[1]:"");return _.Pa&&(b=Xa(),b>(0,window.parseFloat)(a))?String(b):a}();Za={};_.$a=function(a){return Za[a]||(Za[a]=0<=_.pa(Ya,a))};ab=_.h.document;_.bb=ab&&_.Pa?Xa()||("CSS1Compat"==ab.compatMode?(0,window.parseInt)(Ya,10):5):void 0;
_.y=function(){this.I=this.I;this.j=this.j};_.y.prototype.I=!1;_.y.prototype.dc=function(){return this.I};_.y.prototype.H=function(){this.I||(this.I=!0,this.B())};_.A=function(a,b){_.cb(a,_.fa(_.z,b))};_.cb=function(a,b,c){a.j||(a.j=[]);a.j.push(_.m(c)?(0,_.q)(b,c):b)};_.y.prototype.B=function(){if(this.j)for(;this.j.length;)this.j.shift()()};_.z=function(a){a&&"function"==typeof a.H&&a.H()};
_.db=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};_.eb=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var jb,hb,lb,pb;_.gb=function(a,b){this.b=0;this.f=void 0;this.a=this.c=null;this.j=this.e=!1;try{var c=this;a.call(b,function(a){fb(c,2,a)},function(a){fb(c,3,a)})}catch(d){fb(this,3,d)}};_.gb.prototype.then=function(a,b,c){return hb(this,_.ha(a)?a:null,_.ha(b)?b:null,c)};_.db(_.gb);_.gb.prototype.g=function(a){0==this.b&&La(function(){var b=new _.ib(a);jb(this,b)},this)};
jb=function(a,b){if(0==a.b)if(a.c){var c=a.c;if(c.a){for(var d=0,e=-1,f=0,l;l=c.a[f];f++)if(l=l.Ja)if(d++,l==a&&(e=f),0<=e&&1<d)break;0<=e&&(0==c.b&&1==d?jb(c,b):(d=c.a.splice(e,1)[0],lb(c,d,3,b)))}}else fb(a,3,b)};_.nb=function(a,b){a.a&&a.a.length||2!=a.b&&3!=a.b||mb(a);a.a||(a.a=[]);a.a.push(b)};
hb=function(a,b,c,d){var e={Ja:null,hc:null,ic:null};e.Ja=new _.gb(function(a,l){e.hc=b?function(c){try{var e=b.call(d,c);a(e)}catch(w){l(w)}}:a;e.ic=c?function(b){try{var e=c.call(d,b);!_.m(e)&&b instanceof _.ib?l(b):a(e)}catch(w){l(w)}}:l});e.Ja.c=a;_.nb(a,e);return e.Ja};_.gb.prototype.l=function(a){this.b=0;fb(this,2,a)};_.gb.prototype.h=function(a){this.b=0;fb(this,3,a)};
var fb=function(a,b,c){if(0==a.b){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(_.eb(c)){a.b=1;c.then(a.l,a.h,a);return}if(_.ga(c))try{var d=c.then;if(_.ha(d)){ob(a,c,d);return}}catch(e){b=3,c=e}}a.f=c;a.b=b;mb(a);3!=b||c instanceof _.ib||pb(a,c)}},ob=function(a,b,c){a.b=1;var d=!1,e=function(b){d||(d=!0,a.l(b))},f=function(b){d||(d=!0,a.h(b))};try{c.call(b,e,f)}catch(l){f(l)}},mb=function(a){a.e||(a.e=!0,La(a.k,a))};
_.gb.prototype.k=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;b++)lb(this,a[b],this.b,this.f)}this.e=!1};lb=function(a,b,c,d){if(2==c)b.hc(d);else{if(b.Ja)for(;a&&a.j;a=a.c)a.j=!1;b.ic(d)}};pb=function(a,b){a.j=!0;La(function(){a.j&&_.qb.call(null,b)})};_.qb=Da;_.ib=function(a){_.ma.call(this,a)};_.p(_.ib,_.ma);_.ib.prototype.name="cancel";
var rb=!_.Pa||_.Pa&&9<=_.bb,sb=_.Pa&&!_.$a("9");!Ra||_.$a("528");_.Qa&&_.$a("1.9b")||_.Pa&&_.$a("8")||Oa&&_.$a("9.5")||Ra&&_.$a("528");_.Qa&&!_.$a("8")||_.Pa&&_.$a("9");_.B=function(a,b){this.type=a;this.b=this.target=b;this.c=!1;this.bd=!0};_.B.prototype.H=function(){};_.B.prototype.e=function(){this.c=!0};_.B.prototype.j=function(){this.bd=!1};var tb=function(a){tb[" "](a);return a};tb[" "]=_.la;_.ub=function(a,b){try{return tb(a[b]),!0}catch(c){}return!1};var vb=function(a,b){_.B.call(this,a?a.type:"");this.b=this.target=null;this.f=this.clientY=this.clientX=0;this.a=this.state=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.b=b;var c=a.relatedTarget;c&&_.Qa&&_.ub(c,"nodeName");this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.f=a.keyCode||0;this.state=a.state;this.a=a;a.defaultPrevented&&this.j()}};_.p(vb,_.B);
vb.prototype.e=function(){vb.w.e.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};vb.prototype.j=function(){vb.w.j.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,sb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var wb,yb;wb="closure_listenable_"+(1E6*Math.random()|0);_.xb=function(a){return!(!a||!a[wb])};yb=0;var Ab=function(a,b,c,d,e){this.Fa=a;this.proxy=null;this.src=b;this.type=c;this.Wa=!!d;this.xb=e;this.key=++yb;this.removed=this.ob=!1},Bb=function(a){a.removed=!0;a.Fa=null;a.proxy=null;a.src=null;a.xb=null};var Cb=function(a){this.src=a;this.a={};this.b=0},Db;Cb.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var l=Db(a,b,d,e);-1<l?(b=a[l],c||(b.ob=!1)):(b=new Ab(b,this.src,f,!!d,e),b.ob=c,a.push(b));return b};Cb.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Db(e,b,c,d);return-1<b?(Bb(e[b]),_.v.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var Eb=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=_.xa(a.a[c],b);d&&(Bb(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d};Cb.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Bb(d[e]);delete this.a[c];this.b--}return b};_.Fb=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Db(a,c,d,e));return-1<b?a[b]:null}; Db=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.Fa==b&&f.Wa==!!c&&f.xb==d)return e}return-1};
var Gb,Hb,Ib,Nb,Ob,Ub,Tb,Pb,Vb;Gb="closure_lm_"+(1E6*Math.random()|0);Hb={};Ib=0;_.Jb=function(a,b,c,d,e){if(_.u(b)){for(var f=0;f<b.length;f++)_.Jb(a,b[f],c,d,e);return null}c=_.Kb(c);return _.xb(a)?a.listen(b,c,d,e):_.Lb(a,b,c,!1,d,e)};_.Lb=function(a,b,c,d,e,f){if(!b)throw Error("g");var l=!!e,n=_.Mb(a);n||(a[Gb]=n=new Cb(a));c=n.add(b,c,d,e,f);if(c.proxy)return c;d=Nb();c.proxy=d;d.src=a;d.Fa=c;a.addEventListener?a.addEventListener(b.toString(),d,l):a.attachEvent(Ob(b.toString()),d);Ib++;return c};
Nb=function(){var a=Pb,b=rb?function(c){return a.call(b.src,b.Fa,c)}:function(c){c=a.call(b.src,b.Fa,c);if(!c)return c};return b};_.Rb=function(a,b,c,d,e){if(_.u(b))for(var f=0;f<b.length;f++)_.Rb(a,b[f],c,d,e);else c=_.Kb(c),_.xb(a)?a.oc(b,c,d,e):a&&(a=_.Mb(a))&&(b=_.Fb(a,b,c,!!d,e))&&_.Sb(b)};
_.Sb=function(a){if(_.ja(a)||!a||a.removed)return!1;var b=a.src;if(_.xb(b))return Eb(b.ca,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.Wa):b.detachEvent&&b.detachEvent(Ob(c),d);Ib--;(c=_.Mb(b))?(Eb(c,a),0==c.b&&(c.src=null,b[Gb]=null)):Bb(a);return!0};Ob=function(a){return a in Hb?Hb[a]:Hb[a]="on"+a};Ub=function(a,b,c,d){var e=1;if(a=_.Mb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Wa==c&&!f.removed&&(e&=!1!==Tb(f,d))}return Boolean(e)};
Tb=function(a,b){var c=a.Fa,d=a.xb||a.src;a.ob&&_.Sb(a);return c.call(d,b)};
Pb=function(a,b){if(a.removed)return!0;if(!rb){var c;if(!(c=b))t:{c=["window","event"];for(var d=_.h,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break t}c=d}e=c;c=new vb(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){t:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break t}catch(l){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.b;f;f=f.parentNode)e.push(f);for(var f=a.type,n=e.length-1;!c.c&&0<=n;n--)c.b=e[n],d&=Ub(e[n],f,!0,c);for(n=0;!c.c&&n<e.length;n++)c.b=e[n],d&=Ub(e[n],
f,!1,c)}return d}return Tb(a,new vb(b,this))};_.Mb=function(a){a=a[Gb];return a instanceof Cb?a:null};Vb="__closure_events_fn_"+(1E9*Math.random()>>>0);_.Kb=function(a){if(_.ha(a))return a;a[Vb]||(a[Vb]=function(b){return a.handleEvent(b)});return a[Vb]};
_.C=function(){_.y.call(this);this.ca=new Cb(this);this.Y=this;this.l=null};_.p(_.C,_.y);_.C.prototype[wb]=!0;_.g=_.C.prototype;_.g.fb=function(a){this.l=a};_.g.addEventListener=function(a,b,c,d){_.Jb(this,a,b,c,d)};_.g.removeEventListener=function(a,b,c,d){_.Rb(this,a,b,c,d)};_.g.B=function(){_.C.w.B.call(this);this.ca&&this.ca.removeAll(void 0);this.l=null};_.g.listen=function(a,b,c,d){return this.ca.add(String(a),b,!1,c,d)};_.g.tb=function(a,b,c,d){return this.ca.add(String(a),b,!0,c,d)};
_.g.oc=function(a,b,c,d){return this.ca.remove(String(a),b,c,d)};_.g.M=function(a,b,c){a=this.ca.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.Wa==b){var l=f.Fa,n=f.xb||f.src;f.ob&&Eb(this.ca,f);d=!1!==l.call(n,c)&&d}}return d&&0!=c.bd};
var Wb=function(){};Wb.prototype.a=null;var Yb;Yb=function(){};_.p(Yb,Wb);_.Xb=new Yb;var Zb,$b;Zb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;_.bc=function(a){if($b){$b=!1;var b=_.h.location;if(b){var c=b.href;if(c&&(c=_.ac(c))&&c!=b.hostname)throw $b=!0,Error();}}return a.match(Zb)};$b=Ra;_.ac=function(a){return(a=_.bc(a)[3]||null)?(0,window.decodeURI)(a):a};
var cc,dc,ec,fc,gc,hc,ic;ic=hc=gc=fc=ec=dc=cc=!1;var jc=_.za;jc&&(-1!=jc.indexOf("Firefox")?cc=!0:-1!=jc.indexOf("Camino")?dc=!0:-1!=jc.indexOf("iPad")?fc=!0:-1!=jc.indexOf("iPhone")||-1!=jc.indexOf("iPod")?ec=!0:-1!=jc.indexOf("Chrome")?hc=!0:-1!=jc.indexOf("Android")?gc=!0:-1!=jc.indexOf("Safari")&&(ic=!0));var kc=cc,lc=dc,mc=ec,nc=fc,oc=gc,pc=hc,qc=ic;
var rc;rc=function(a){return(a=a.exec(_.za))?a[1]:""};_.sc=function(){if(kc)return rc(/Firefox\/([0-9.]+)/);if(_.Pa||Oa)return Ya;if(pc)return rc(/Chrome\/([0-9.]+)/);if(qc)return rc(/Version\/([0-9.]+)/);if(mc||nc){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.za))return a[1]+"."+a[2]}else{if(oc)return(a=rc(/Android\s+([0-9.]+)/))?a:rc(/Version\/([0-9.]+)/);if(lc)return rc(/Camino\/([0-9.]+)/)}return""}();
var tc=function(){_.y.call(this)};_.p(tc,_.y);tc.prototype.setEnabled=function(){};var uc=function(){_.y.call(this);this.V=null};_.p(uc,tc);var vc=function(){_.y.call(this);this.V=null};_.p(vc,tc);var wc=function(){_.y.call(this);this.a={}};_.p(wc,_.y);wc.prototype.create=function(a){if(null==this.a[a]){switch(a){case "memory":this.a[a]=new vc;break;case "js-errors":this.a[a]=new uc}_.A(this,this.a[a])}return this.a[a]};_.xc=function(){wc.call(this)};_.p(_.xc,wc);_.ka(_.xc);_.xc.S();
}catch(e){_._DumpException(e)}
try{
_.yc=function(a,b){var c=a.split("."),d=_.h;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.m(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};_.D=function(a,b,c){this.c=a;this.b=b||null;this.a=c||[]};_.D.prototype.toString=function(){return this.c};
_.zc=new _.D("fJuxOc");_.Ac=new _.D("ZtVrH");_.Bc=new _.D("zZa4xc");_.Cc=new _.D("pVbxBc");_.Dc=new _.D("byfTOb");_.Ec=new _.D("LEikZe");_.Fc=new _.D("rJmJrc");_.Gc=new _.D("a");
}catch(e){_._DumpException(e)}
try{
_.ki="https://support.google.com/chrome/answer/185277?hl="+window.chrome.i18n.getMessage("@@ui_locale");_.li="https://support.google.com/hangouts/?p=chrome_desktop_app&hl="+window.chrome.i18n.getMessage("@@ui_locale");_.mi="https://support.google.com/hangouts/?p=chrome_desktop_app_outdated&hl="+window.chrome.i18n.getMessage("@@ui_locale");

}catch(e){_._DumpException(e)}
try{
_.yc("_DumpException",function(a){window.console.error(a.stack)});_.xc.S();window.open("","centralRoster")._OnUiFrameReady(window);
}catch(e){_._DumpException(e)}
}).call(this,this.default_uiframehook);
// Google Inc.
