function hasNever(b,a,e,d){b=lpcanonizeUrl(b);0<b.length&&"/"==b.charAt(b.length-1)&&(b=b.substring(0,b.length-1));if(g_neverurls[e]&&0<g_neverurls[e].length){for(var f=!1,c=0;g_neverurls[e]&&c<g_neverurls[e].length;c++){var g=g_neverurls[e][c];if(g==a||g==b){f=!0;break}}if(!f)return!0}for(c=0;g_neverurls[d]&&c<g_neverurls[d].length;c++)if(g=g_neverurls[d][c],g==a||g==b)return!0;return!1}function hasNeverAutologin(b,a){return hasNever(b,a,"onlyautologins","neverautologins")}
function hasNeverFormFill(b,a){return hasNever(b,a,"onlyformfills","neverformfills")}function hasNeverSave(b,a){return hasNever(b,a,"onlyaccounts","neveraccounts")}function hasNeverShowIcon(b,a){return hasNever(b,a,"onlyshowicons","nevershowicons")}function hasNeverGenerate(b,a){return hasNever(b,a,"onlygenerates","nevergenerates")}var g_accessibility_enabled=-1;
function handleFill(b,a){var e=!1;if(lploggedin&&null==grid_getdata("active")||skiplogin())if("autofillaid"==a.cmd||"autologinaid"==a.cmd){var d=a.aid;g_last_launch[d]=(new Date).getTime();if("undefined"!=typeof g_sites[d]){var e="autologinaid"==a.cmd,f=!0,c=get_record(d);a.no_manualfill_on_saveall&&c.save_all&&(f=!1);a.from_iframe&&!c.save_all&&(f=!0);c=a.from_iframe?!0:!1;fill(b,g_sites[d],null,e,!e,"all",!0,!1,f,null,null,c)}}else if(!("undefined"==typeof a||!a||"undefined"==typeof a.url)){var f=
a.url,g=lp_gettld_url(f);if(!lp_url_is_lastpass(f)){if("undefined"==typeof g_launches[b]||!g_launches[b])null!=g_pending_launch&&(g_launches[b]=g_pending_launch);if("undefined"!=typeof g_launches[b]&&g_launches[b]&&(d=g_launches[b],check_ident_aid(d)&&compare_tlds(g,lp_gettld_url(g_sites[d].url)))){if("undefined"!=typeof a.numpass&&0<a.numpass||""==g_sites[d].password)g_launches[b]=null;"undefined"!=typeof g_sites[d]&&(is_guiless()?fill(b,get_record(d),null,!1,!1,"all",!0,!1,!1,!1):(c=a.from_iframe?
!0:!1,fill(b,get_record(d),null,!0,!1,a.docnum,!1,!0,null,null,null,c)),g_pending_launch=g_launches[b]=null)}var l=getsites(g),l=reorderOnURL(l,f,!0);hasNeverAutologin(f,g)&&(l=[]);d=0==a.force&&a.topurl!=f?lp_gettld_url(a.topurl):"";""!=d&&hasNeverAutologin(a.topurl,d)&&(l=[]);for(var k in l){try{if(islastpass&&g_ischrome&&1==l[k].basic_auth&&0>=g_accessibility_enabled&&0==lpGetPref("basicauthnever",0))if(g_is_mac&&have_binary_function("accessibility_enabled"))call_binary_function("accessibility_enabled",
function(a){g_accessibility_enabled=a?1:0;0==g_accessibility_enabled&&setTimeout(function(){get_selected_tab(null,function(a){sendCS(gettabid(a),{cmd:"showbasicauthnotification",needbinary:0,text:gs("In order for LastPass to fill into basic authentication dialogs, you need to enable access for assistive devices.")})})},100)});else if((g_is_win||g_is_mac)&&!have_binary())g_accessibility_enabled=0,setTimeout(function(){get_selected_tab(null,function(a){sendCS(gettabid(a),{cmd:"showbasicauthnotification",
needbinary:1,text:gs("In order for LastPass to fill into basic authentication dialogs, you need to install the binary version of LastPass for Chrome.")})})},100)}catch(j){}g=!1;d=l[k].aid;if(check_ident_aid(d)&&"undefined"!=typeof g_sites[d]){c=get_record(d);c.never_autofill&&(g=!0);if(c.pwprotect||g_prompts.login_site_prompt)g=!0;if(!c.genpw&&!(0==c.fields.length&&""==c.username)){0==c.url.indexOf("https://")&&0!=f.indexOf("https://")&&(g=!0);0==parseInt(lpGetPref("automaticallyFill",1))&&0==parseInt(lpGetPref("highlightFields",
1))&&(g=!0);if(!g){if(d=!c.save_all)"undefined"==typeof g_fillfieldsmatches[f]&&(g_fillfieldsmatches[f]=[]),g_fillfieldsmatches[f][g_fillfieldsmatches[f].length]=c,g_fillfieldsmatchescurridx[f]=0;k=parseInt(lpGetPref("automaticallyFill",1));fill(b,c,a.docid,null,d,a.docnum,null,!0,null,k)}0!=lpGetPref("showFillNotificationBar",1)&&(get_selected_tab(null,function(){sendCS(b,{cmd:"showfillnotification",text:gs("LastPass has filled your login information into the form on this page."),sites:cache_usernames(l),
docnum:a.docnum})}),e=!0);break}}}!e&&0==lpGetPref("showNotificationsAfterClick",1)&&checkgenpwfillforms(b,f)}}}
function checkWeakAndDuplicate(b,a,e){if(g_showweakdupalerts&&qualifyForWeakCheck(getpasswordfromacct(b))&&(g_ischrome||g_issafari))!1==g_disablepwalerts&&("undefined"==typeof b.noalert||"1"!=b.noalert)&&getWeakAndDuplicateIds(g_username_hash,g_username,function(d){isDuplicateSite(d[0],b.aid)?(g_notification_type="alert",g_notification_data={cmd:"notification",type:"alert",aid:b.aid,name:b.name,username:getusernamefromacct(b),alerttype:"duplicate",tld:e,tabid:a},set_badge(g_notification_data,a),drawIconAtRotation(0)):
isWeakPassword(d[1],b.aid)&&(g_notification_type="alert",g_notification_data={cmd:"notification",type:"alert",aid:b.aid,name:b.name,username:getusernamefromacct(b),alerttype:"weak",tld:e,tabid:a},set_badge(g_notification_data,a),drawIconAtRotation(0))})}
function checkgenpwfillforms(b,a,e){var d=lp_gettld_url(a),f=1!=lpGetPref("showGenerateNotifications",1)||hasNeverGenerate(a,d),c=1!=lpGetPref("showFormFillNotifications",1)||hasNeverFormFill(a,d),g=[];if(do_experimental_popupfill){for(var l=0;l<g_formfills.length;l++)check_ident_ffid(g_formfills[l].ffid)&&(g[g.length]=g_formfills[l]);0==g.length&&(c=!0);a={cmd:"checkgenpwfillforms",nevergenerate:f,neverformfill:c,sites:cache_usernames(reorderOnURL(getsites(d),a,!0,!0)),formfills:LPJSON.stringify(g),
active:g_popupfill_last_active[b],activefieldid:g_popupfill_last_active_fieldid[b]};e||(a.ff=g_cachedffdat);sendCS(b,a,"all")}else{if(!c){for(l=0;l<g_formfills.length;l++)check_ident_ffid(g_formfills[l].ffid)&&(g[g.length]=g_formfills[l]);0==g.length&&(c=!0)}if(!f||!c)a={cmd:"checkgenpwfillforms",nevergenerate:f,neverformfill:c,sites:cache_usernames(reorderOnURL(getsites(d),a,!0,!0)),formfills:LPJSON.stringify(g)},e||(a.ff=g_cachedffdat),sendCS(b,a,"all")}}
function cache_usernames(b){for(var a in b)b[a].useusername=getusernamefromacct(b[a]);return LPJSON.stringify(b)}
function handleNever(b,a){if("neverautofill"==a.cmd){var e=a.aid;if("undefined"==typeof g_sites[e])return;g_sites[e].never_autofill=!0;g_sites[e].autologin=!1;e="aid="+en(e);lpMakeRequest(base_url+"set_never_autofill.php",e,null,null)}else if("neverdomain"==a.cmd||"neverpage"==a.cmd){var d="neverdomain"==a.cmd?lp_gettld_url(a.url):lpcanonizeUrl(a.url),e="url="+en(AES.url2hex(d));"undefined"!=typeof a.fromsave&&a.fromsave?g_neverurls.neveraccounts.push(d):"undefined"!=typeof a.fromgenerate&&a.fromgenerate?
(e+="&type=1",g_neverurls.nevergenerates.push(d)):"undefined"!=typeof a.fromformfill&&a.fromformfill?(e+="&type=2",g_neverurls.neverformfills.push(d)):"undefined"!=typeof a.fromshowicons&&a.fromshowicons?(e+="&type=6",g_neverurls.nevershowicons.push(d)):(e+="&type=3",g_neverurls.neverautologins.push(d));lpMakeRequest(base_url+"add_never.php",e,null,null)}g_local_accts_version++;rewritelocalfile()}
function handleSave(b,a){if(g_cpwbot&&CPWbot_bg&&b==CPWbot_bg.get_pwchangetabid())L("handleSave(tab:"+b+", state="+CPWbot_bg.g_pwchangestate+")"),console_log("Skipping save because driving a password change");else{var e=get_ff_translation("ff_currpass_regexp");if(!("undefined"==typeof SAVEALLFORMSUBMITS&&(!lploggedin||lp_url_is_lastpass(a.url,!0)))){for(var d=a.formdata.split("\n"),f=!1,c=!1,g=null,l="",k="",j=[],n=0;n<d.length;n++){var h=d[n],h=h.split("\t");if(!(4!=h.length&&5!=h.length)){var p=
decodeURIComponent(h[2]),m=h[3];if((!f||!c)&&("text"==m||"email"==m||"tel"==m||"url"==m)&&p.length)l=p,f=!0,!1==c&&"undefined"!=typeof SpecialSites[lpcanonizeUrl(a.url)]&&(c=!0);if("password"==m&&(j[j.length]=p,!c&&p.length&&(k=p,c=!0),null==g)){var p=decodeURIComponent(h[1]),q=RegExp(e,"i");if(p&&(p==a.current_pw_field_name||q.exec(p)))g=j.length-1}}}if(c){a.username=l;a.password=k;!f&&1<j.length&&(j[0]!=j[1]&&null==g)&&(a.username=j[0],a.password=j[1]);e=lp_gettld_url(a.url);a.tld=e;h=!1;c="";1<
j.length&&j[j.length-1]==j[j.length-2]&&""!=j[j.length-1]?(h=!0,c=j[j.length-1]):1<j.length&&j[0]==j[1]&&""!=j[0]?(h=!0,c=j[0]):1<j.length&&(j[0]!=j[1]&&""!=j[0]&&null!=g)&&(c=0==g&&2==j.length?j[1]:1==g&&2==j.length?j[0]:"");var u=h||null!=g&&c,g=[];if(u&&(g=getsites(e,!0),a.createacct=2==j.length||0<array_length(g),a.createacct)){for(var v=j="",r="",w="",n=0;n<d.length;n++)if(h=d[n],h=h.split("\t"),!(4!=h.length&&5!=h.length)){m=h[3];if(""==j&&("email"==m||"tel"==m||"text"==m||"url"==m)&&""!=h[1]&&
""!=h[2])p=decodeURIComponent(h[1]),q=get_ff_translation("ff_username_regexp"),""!=q&&(q=RegExp(q,"i"),q.exec(p)&&(j=p,v=decodeURIComponent(h[2])));if(""==r&&("email"==m||"tel"==m||"text"==m||"url"==m)&&""!=h[1]&&""!=h[2])p=decodeURIComponent(h[1]),m=get_ff_translation("ff_email_regexp"),""!=m&&(q=RegExp(m,"i"),q.exec(p)&&(r=p,w=decodeURIComponent(h[2])));if(""!=j&&""!=r)break}""==j&&(j=r,v=w);a.username_field=j;""!=v&&(a.username=v)}if(u&&0<array_length(g)){if(verbose_log("looking for newpw="+(g_show_pw_in_logs||
g_isadmin?c:"REDACTED")+" tld="+e+" in g_didchangepw"),f="undefined"!=typeof g_didchangepw[SHA256(c+e)]&&g_didchangepw[SHA256(c+e)]>(new Date).getTime()-6E5,verbose_log("already processed pw ="+(g_show_pw_in_logs||g_isadmin?c:"REDACTED")+" tld="+e+" is "+f),!f&&(g_notification_type="change",a.newpw=c,g_notification_data=a,sendTS({cmd:"notification",type:"change"}),0!=lpGetPref("showChangeNotificationBar",1))){var d=g,s;a.sitecount=array_length(d);if(1==array_length(d))for(n in d){a.singleaid=n;s=
gs("LastPass detected a password change for user:")+" "+getusernamefromacct(g_sites[n]);break}else s=gs("LastPass detected a password change for domain:")+" "+e;sendCS(b,{cmd:"showchangenotification",text:s,notificationdata:a});g_persistent_notifications[b]={cmd:"showchangenotification",text:s,notificationdata:a}}}else if(!hasNeverSave(a.url,e)){var d=getsites(e),t;for(t in d)if(check_ident_aid(t)&&"undefined"!=typeof g_sites[t]&&(n=get_record(t),s=getusernamefromacct(n),d=getpasswordfromacct(n),
(!f||l==lpmdec_acct(n.username,!0,n,g_shares)||0==l.indexOf("****")||l==s)&&(k==lpmdec_acct(n.password,!0,n,g_shares)||k==d)||n.save_all&&isMatch(n,f,l,k)||l==lpmdec_acct(n.username,!0,n,g_shares)&&""==k))return;g_notification_type="save";g_notification_data=a;0!=lpGetPref("showSaveSiteNotifications",0)&&sendTS({cmd:"notification",type:"save"});0!=lpGetPref("showSaveNotificationBar",1)&&lpCheckAddSite(a.username,a.password,e)&&(g_persistent_notifications[b]={cmd:"showaddnotification",text:gs("Should LastPass remember this password?"),
notificationdata:LPJSON.stringify(a)},sendCS(b,{cmd:"showaddnotification",text:gs("Should LastPass remember this password?"),notificationdata:LPJSON.stringify(a)}))}}}}}
function lpCheckAddSite(b,a,e){var d=lp_get_gmt_timestamp(),f=[],c;for(c in g_rejectedaddsites){var g=g_rejectedaddsites[c];d>g.rejectedTime+600&&(f[f.length]=c)}for(c=f.length-1;0<=c;c--)g_rejectedaddsites.splice(f[c],1);for(c in g_rejectedaddsites)if(g=g_rejectedaddsites[c],g.username==b&&lpdec(g.encryptedPassword)==a&&compare_tlds(g.tld,e))return!1;return!0}var lastupdatefields="";
function handleUpdateFields(b,a){var e=a.aid,d=g_sites[e],f=issharedfolder(g_shares,d.group);if(checkreadonly(f,!0)){var c=[],g=[],l=updateAndEncryptData(a.formdata,c,g,d),k=SHA256(l);if(k!=lastupdatefields){lastupdatefields=k;update_username_from_fields_if(d,c);for(k=d.fields.length-1;0<=k;k--)!d.fields[k].otherfield&&"1"!=d.fields[k].otherlogin&&d.fields.splice(k,1);for(k=0;k<c.length;k++)d.fields[d.fields.length]=c[k];g_local_accts_version++;rewritelocalfile();e="data="+en(bin2hex(l))+"&ref="+
en(url2hex(a.url))+"&updatefields=1&aid="+en(e);e+=!1==f?"":"&sharedfolderid="+en(f.id);d.postdata=e;d.posturl=base_url+"gm_deliver.php";d.newvalues=g;updateFieldsFromSubmit(e,d)}}}
function handleAddUrid(b,a){var e=a.aid,d=g_sites[e],f=issharedfolder(g_shares,d.group);if(checkreadonly(f,!0)){for(var c=[],g=0;g<d.fields.length;g++)"1"==d.fields[g].otherlogin&&!lp_in_array(d.fields[g].urid,c)&&(c[c.length]=d.fields[g].urid);if(!(10<=c.length)){var l=[],c=[],k=updateAndEncryptData(a.formdata,l,c,d);update_username_from_fields_if(d,l);for(g=0;g<l.length;g++)l[g].otherlogin="1",l[g].url=url2hex(a.url),d.fields[d.fields.length]=l[g];g_local_accts_version++;rewritelocalfile();e="data="+
en(bin2hex(k))+"&ref="+en(url2hex(a.url))+"&addurid=1&aid="+en(e);e+=!1==f?"":"&sharedfolderid="+en(f.id);d.postdata=e;d.posturl=base_url+"gm_deliver.php";d.newvalues=c;updateFieldsFromSubmit(e,d)}}}
function update_username_from_fields_if(b,a){for(var e=get_ff_translation("ff_combineddummy_regexp"),d=RegExp(e,"i"),f=0,e="",c=0;c<a.length;c++)if("text"==a[c].type||"email"==a[c].type||"tel"==a[c].type||"url"==a[c].type)if(!d.exec(a[c].name)&&!d.exec(a[c].id)&&!("answer"==a[c].id||"answer"==a[c].name))if(e=a[c].value,2<=++f)break;if(1==f&&""!=e){for(c=d=0;c<b.fields.length;c++)if(!b.fields[c].otherfield&&("text"==b.fields[c].type||"email"==b.fields[c].type||"tel"==b.fields[c].type||"url"==b.fields[c].type)){d++;
break}0==d&&(b.username=e,b.unencryptedUsername=lpdec_acct(crypto_btoa(b.username),b,g_shares))}}function handleSaveAll(b,a){a.save_all=1;g_site_data=a;openURL(getchromeurl("site.html"))}
function isMatch(b,a,e,d){a=a?!1:!0;for(var f=!1,c=0;c<b.fields.length;c++)if(!("text"!=b.fields[c].type&&"password"!=b.fields[c].type&&"email"!=b.fields[c].type&&"tel"!=b.fields[c].type&&"url"!=b.fields[c].type)){var g=lpmdec_acct(b.fields[c].value,!0,b,g_shares);if(("text"==b.fields[c].type||"email"==b.fields[c].type||"tel"==b.fields[c].type||"url"==b.fields[c].type)&&e==g)a=!0;"password"==b.fields[c].type&&d==g&&(f=!0)}return a&&f?!0:!1}var g_reqindex=0;
function fill(b,a,e,d,f,c,g,l,k,j,n,h){verbose_log("tabid="+b+"\nacct="+a+"\ndocid="+e+"\nsubmit="+d+"\ndoconfirm="+f+"\ndocnum="+c+"\nallowforce="+g+"\nskip_pwprotect="+l+"\nmanualfill="+k+"\nautomaticallyFill="+j+"\nskip_basicauth="+n+"\nfrom_iframe="+h);if("undefined"==typeof j||null==j)j=1;k||(k=!1);!l&&(a.pwprotect||g_prompts.login_site_prompt)?(console_log("FILL : Showing Security Prompt"),a.pwprotect?security_prompt(function(){setTimeout(function(){var j=get_record(a.aid);fill(b,j,e,d,f,c,
g,!0,k,null,null,h)},100)},null,null,!0,a.aid,!0):security_prompt(function(){setTimeout(function(){fill(b,a,e,d,f,c,g,!0,k,null,null,h)},100)})):get_selected_tab(null,function(p){if(!n&&j&&(g||1==a.basic_auth)&&gettabid(p)==b&&g_ischrome&&have_binary_function("fill_basicauth")){p=getusernamefromacct(a);var m=getpasswordfromacct(a);if(""!=p||""!=m){var q=check_autologin(d,a),u=lp_gettld_url(a.url),v=lp_gettld_url(g_basicauth_origurl);compare_tlds(u,v)&&(u=v);call_binary_function("fill_basicauth",p,
m,g?!0:!1,u,q?!0:!1,function(h){h?g_basicauth_found=!1:fill(b,a,e,d,f,c,g,l,k,j,!0)});return}}is_guiless()&&(j=1);u=a.tld;m=a.fields;q=m.length?m.length:0;f=1==f?1:0;g=g?1:0;h=h?1:0;p=null!=a.sharedfromaid&&""!=a.sharedfromaid&&"0"!=a.sharedfromaid&&"null"!=a.sharedfromaid?1:0;if(0!=q){for(q=u=0;q<m.length;q++)"password"==m[q].type&&u++;u=!a.save_all&&0==u;v=[];for(q=0;q<m.length;q++)if(a.save_all||!(1==f&&"password"!=m[q].type&&!g&&!u)){var r=m[q],w=r.value;if(!(""!=r.name&&"undefined"!=typeof v[r.name+
w+r.type])){v[r.name+w+r.type]=1;var s=r.type;if(!("undefined"!=typeof a.captcha_id&&""!=a.captcha_id&&a.captcha_id==r.name&&"text"==s)){if("text"==s||"password"==s||"email"==s||"tel"==s||"textarea"==s||"url"==s)w=lpmdec_acct(w,!0,a,g_shares);if(""!=w){verbose_log("Sending FillRequest: "+q+"\ntype="+s+"\nname="+r.name+"\nvalue=<hidden>");var t="undefined"!=typeof g_last_launch&&"undefined"!=typeof g_last_launch[a.aid]&&25E3>=(new Date).getTime()-g_last_launch[a.aid];console_log("Sending fillfield reqindex="+
g_reqindex);var x={from:"fillfield_A",index:g_reqindex,time:(new Date).getTime(),uniqid:Math.floor(1E8*Math.random())};++g_reqindex;t={cmd:"fillfield",realurl:a.url,reqinfo:x,manualfill:k,name:r.name,value:w,formname:r.formname,type:s,docid:e,aid:a.aid,checked:r.checked,doconfirm:f||a.save_all&&"password"==s?1:2,tabid:b,allowforce:g,custom_js:a.custom_js,sharedsite:p,otherfield:r.otherfield,domains:getacceptabletlds(a.url),automaticallyFill:j,is_launch:t,clearfilledfieldsonlogoff:lpGetPref("clearfilledfieldsonlogoff",
0),from_iframe:h};""!=a.custom_js&&(t.username=getusernamefromacct(a),t.password=getpasswordfromacct(a),t.onlyfill=d?0:1);sendCS(b,t,c)}}}}}else g&&(console_log("no fields. finding best match "+getusernamefromacct(a)+" and <hidden>"),t="undefined"!=typeof g_last_launch&&"undefined"!=typeof g_last_launch[a.aid]&&25E3>=(new Date).getTime()-g_last_launch[a.aid],console_log("Sending fillbest from A reqindex="+g_reqindex),x={from:"fillbest_A",index:g_reqindex,time:(new Date).getTime(),uniqid:Math.floor(1E8*
Math.random())},++g_reqindex,m=null,m=getpasswordfromacct(a),sendCS(b,{cmd:"fillbest",reqinfo:x,realurl:a.url,username:getusernamefromacct(a),password:m,docid:e,aid:a.aid,custom_js:a.custom_js,updatefields:1,addurid:0,sharedsite:p,domains:getacceptabletlds(a.url),automaticallyFill:j,is_launch:t,clearfilledfieldsonlogoff:lpGetPref("clearfilledfieldsonlogoff",0)},c));g&&logLoginAndCheckWeakPassword(b,a);if(1!=f&&(q=check_autologin(d,a),"undefined"!=typeof AUTOSUBMIT&&(q=!0),"string"==typeof a.custom_js&&
""!=a.custom_js&&sendCS(b,{cmd:"run_custom_js",docid:e,custom_js:a.custom_js,username:getusernamefromacct(a),password:lpmdec_acct(a.password,!0,a,g_shares),onlyfill:q?0:1,loc:3},c),("string"!=typeof a.custom_js||-1==a.custom_js.indexOf("lpdontsubmit"))&&q))p="undefined"!=typeof a.submit_id?a.submit_id:"",m="undefined"!=typeof a.submit_html?a.submit_html:"",q="undefined"!=typeof a.submit_js?a.submit_js:"",is_guiless()&&"bankofamerica.com"==lp_gettld_url(a.url)||sendCS(b,{cmd:"submit",docid:e,submit_id:p,
submit_html:m,submit_js:q},c)})}function logLoginAndCheckWeakPassword(b,a){get_all_windows({populate:!0},function(e){for(var d=0;d<e.length;d++)for(var f=0;f<get_tabs_length(e[d]);f++){var c=get_tabs(e[d])[f];if(gettabid(c)==b&&(checkWeakAndDuplicate(a,b,lp_gettld_url(gettaburl(c))),(g_loglogins||LPISLOC)&&"undefined"==typeof g_loggedLogins[a.aid]))g_loggedLogins[a.aid]="1",loglogintab(a.aid,c)}})}function showpageoverlay(b){sendCS(b,{cmd:"showoverlay",urlprefix:getchromeurl("",!0)})}
function check_autologin(b,a){var e=!1;if(b)e=!0;else if(a.autologin){var d=(new Date).getTime(),f=parseInt(lpGetPref("autoautoVal",25));if(isNaN(f)||""==f||0>=f)f=25;f=d-1E3*f;"undefined"==typeof a.last_auto_login||isNaN(a.last_auto_login)||a.last_auto_login<f?(console_log("Launching autologin"),a.last_auto_login=d,e=!0):console_log("last autologin too soon!")}return e}
function fillfieldsconfirm(b){var a=b.url,e=b.result,d=b.aid,f=b.docid,c=b.tabid,g=b.doconfirm,l=b.from_iframe?!0:!1,k=b.manualfill,j=b.allowforce,n="undefined"!=typeof b.automaticallyFill?b.automaticallyFill:1,h=get_record(d);if("undefined"!=typeof g_sites[d]){if(e&&(logLoginAndCheckWeakPassword(c,h),2==g)){l&&k&&sendCS(c,{cmd:"conditionalforcefill",reqinfo:m,username:getusernamefromacct(h),password:getpasswordfromacct(h),aid:h.aid,sharedsite:p,automaticallyFill:n,from_iframe:l},b.docnum);return}var p=
null!=h.sharedfromaid&&""!=h.sharedfromaid&&"0"!=h.sharedfromaid&&"null"!=h.sharedfromaid?1:0;if(h.save_all){if(!e||k){a="undefined"!=typeof g_last_launch&&"undefined"!=typeof g_last_launch[h.aid]&&25E3>=(new Date).getTime()-g_last_launch[h.aid];console_log("Sending fillbest from B reqindex="+g_reqindex);var m={from:"fillbest_B",index:g_reqindex,time:(new Date).getTime(),uniqid:Math.floor(1E8*Math.random())};++g_reqindex;password=get_record(h.aid);sendCS(c,{cmd:"fillbest",reqinfo:m,realurl:h.url,
username:getusernamefromacct(h),password:getpasswordfromacct(h),docid:f,aid:h.aid,updatefields:0,addurid:0,sharedsite:p,domains:getacceptabletlds(h.url),automaticallyFill:n,is_launch:a,clearfilledfieldsonlogoff:lpGetPref("clearfilledfieldsonlogoff",0)},b.docnum)}}else if(e){h=get_record(d);k=j=null;l&&b.manualfill&&(j=k=!0);var q;fill(c,h,f,null,!1,b.docnum,j,!0,k,n,!1,l);delete g_fillfieldsmatches[a];delete g_fillfieldsmatchescurridx[a]}else if(b.allowforce)a="undefined"!=typeof g_last_launch&&"undefined"!=
typeof g_last_launch[h.aid]&&25E3>=(new Date).getTime()-g_last_launch[h.aid],console_log("Sending fillbest from C reqindex="+g_reqindex),m={from:"fillbest_C",index:g_reqindex,time:(new Date).getTime(),uniqid:Math.floor(1E8*Math.random())},++g_reqindex,sendCS(c,{cmd:"fillbest",reqinfo:m,realurl:h.url,username:getusernamefromacct(h),password:getpasswordfromacct(h),docid:f,aid:h.aid,updatefields:0,addurid:k?1:0,sharedsite:p,domains:getacceptabletlds(h.url),automaticallyFill:n,is_launch:a,clearfilledfieldsonlogoff:lpGetPref("clearfilledfieldsonlogoff",
0)},b.docnum);else{if(k=g_fillfieldsmatches[a]){h=!1;for(p=0;p<k.length;p++){m=k[p].aid;if(h){(h=g_sites[m])&&(q=!1);fill(c,h,f,null,!0,b.docnum,null,!0,null,n,q,l);return}p==g_fillfieldsmatchescurridx[a]&&(g_fillfieldsmatchescurridx[a]++,h=!0)}}delete g_fillfieldsmatches[a];delete g_fillfieldsmatchescurridx[a]}}}
function web2plug(b){"2"==b.rsa?(g_local_key=AES.hex2bin(b.key),g_local_key_hex=b.key,g_local_key_hash=SHA256(g_local_key),rsa_userchangedpassword(),b=opendb(),createDataTable(b),b&&!LPISLOC&&b.transaction(function(a){a.executeSql("DELETE FROM LastPassData WHERE username_hash=? AND type=?",[db_prepend(g_username_hash),"accts"],function(){},function(a,b){console_log(b)})}),lpWriteKeyFile()):""!=g_username&&null!=g_username&&g_username!=b.username?loggedOut(!1,"web2plug"):(g_local_key=AES.hex2bin(b.key),
g_local_key_hex=b.key,g_local_key_hash=SHA256(g_local_key),lpWriteKeyFile())}function recover(b,a,e,d){var f=lpParseUri(a);a=f.directory;f=f.file;a=a.replace(/^\/~[^/]*/,"");""!=a&&"/"!=a&&"/sso/"!=a||"recover.php"==f&&GetOTPHash(null,b,e,d)}
function loginfromwebsite(b){if(""!=b.wxusername&&""!=b.keyhex){var a=opendb();createSavedLoginsTable(a);a&&a.transaction(function(d){set_default_login_username(b.wxusername);d.executeSql("SELECT * FROM LastPassSavedLogins2 WHERE username = ? AND password != ''",[b.wxusername],function(c,d){if(0<d.rows.length){var e=d.rows.item(0).password,f=function(c){var d=get_key_iterations(b.wxusername);make_lp_key_iterations(b.wxusername,c,d,function(c){AES.bin2hex(c)!=b.keyhex&&a.transaction(function(a){a.executeSql("UPDATE LastPassSavedLogins2 SET password = '' WHERE username = ?",
[b.wxusername],function(){},function(a,b){console_log(b)})})})};1==d.rows.item(0)["protected"]?unprotect_data(e,!1,f):2==d.rows.item(0)["protected"]&&f(lpdec(e,AES.hex2bin(SHA256(b.wxusername))))}},function(){})});var e=AES.hex2bin(b.keyhex),d=null!=g_local_key?AES.bin2hex(g_local_key):"";if(!lploggedin||!(g_username==b.wxusername&&d==b.keyhex))lploggedin&&g_username==b.wxusername?(g_local_key=e,g_local_key_hex=b.keyhex,g_local_key_hash=SHA256(g_local_key)):(lploggedin&&""!=g_username&&loggedOut(!1,
"differentuser"),""!=b.wxsessid&&(lp_phpsessid=b.wxsessid),g_local_key=e,g_local_key_hex=b.keyhex,g_local_key_hash=SHA256(g_local_key),lpWriteKeyFile(),LP.lplogincheck(!0,null,b.wxusername,b.wxhash))}else lploggedin||LP.lplogincheck(!0)}
function reorderOnURL(b,a,e,d){var f=lpParseUri(a),c=lpcanonizeUrl(a,f),g="string"==typeof f.path?f.path.split("/"):[],l=lp_gettld_url(a),k=[],j;for(j in b)if(check_ident_aid(j)&&(b=g_sites[j],!("undefined"==typeof b||"undefined"==typeof b.url)))if(b.save_all||!e||!(""==b.unencryptedUsername&&""==b.password))if(!d||accthaspassword(b)){var n=lpParseUri(b.url);b.realmmatch=(a==g_basicauth_url||a==g_basicauth_origurl)&&(lpmdec_acct(b.realm_data,!0,b,g_shares)==g_basicauth_realm||g_basicauth_found&&""==
g_basicauth_realm&&1==b.basic_auth);b.servermatch=f.host==n.host;b.portmatch=compare_ports(f,n);b.serverportmatch=b.servermatch&&b.portmatch?1:0;b.usernamematch="undefined"!=typeof g_username_vals[a]&&""!=g_username_vals[a]&&g_username_vals[a]==b.unencryptedUsername;b.urlmatch=lpcanonizeUrl(b.url)==c?!0:!1;var n="string"==typeof n.path?n.path.split("/"):[],h;for(h=0;h<g.length&&h<n.length&&n[h]==g[h];h++);b.pathlevelmatch=h;b.fieldmatchcount=0;k.push(b)}k.sort(lp_aids_sort_func);return k=checkurlrules(g_urlrules,
k,l,"string"==typeof f.path?f.path:"",f.host,g_sites,get_port(f))}
function lp_aids_sort_func(b,a){return b.realmmatch!=a.realmmatch?b.realmmatch?-1:1:b.usernamematch!=a.usernamematch?b.usernamematch?-1:1:b.fav!=a.fav?"1"==b.fav?-1:1:b.urlmatch!=a.urlmatch?b.urlmatch?-1:1:b.serverportmatch&&a.serverportmatch&&b.pathlevelmatch!=a.pathlevelmatch?b.pathlevelmatch>a.pathlevelmatch?-1:1:b.serverportmatch!=a.serverportmatch?b.serverportmatch?-1:1:b.servermatch!=a.servermatch?b.servermatch?-1:1:b.fieldmatchcount!=a.fieldmatchcount?b.fieldmatchcount>a.fieldmatchcount?-1:
1:b.last_touch!=a.last_touch?b.last_touch>a.last_touch?-1:1:b.name!=a.name?b.name<a.name?-1:1:0}function lp_sort_case_insensitive_name(b,a){b=b.name.toLowerCase();a=a.name.toLowerCase();return b<a?-1:1}
function launchautologin(b,a){if(check_ident_aid(b)){var e=g_sites[b];e&&(!a&&(e.pwprotect||g_prompts.login_site_prompt)?e.pwprotect?security_prompt(function(){launchautologin(b,!0)},null,null,!0,e.aid,!1):security_prompt(function(){launchautologin(b,!0)}):(g_last_launch[e.aid]=(new Date).getTime(),openURL(e.url,function(a,b){g_launches[gettabid(a)]=b},e.aid)))}}
function is_max_frames_exceeded(b,a){var e=10;if(null==a)return!0;try{var d=g_CS_tops[b],f=g_CS[b][d],c="",c=g_ischrome&&f?lp_gettld_url(f.sender.tab.url):lp_gettld_url(gettaburl(f));"undefined"==typeof d?L("still waiting for topdoc to register for [tab:"+b+"] tld="+c):L("topdoc="+d+" tld="+c);c&&"dailykos.com"==c&&(e=40)}catch(g){console.error("is_max_frames_exceeded: "+g)}debug&&(d=count_cs_for_tabid(b),0<d&&console.warn("is_max_frames_exceeded: CS table count="+d+", global g_CS_count="+g_CS_count[b]),
dumpinfo_for_tabid(b));g_skip_ad_frames&&(e=25);return a[b]>e};
