var data=null,existing=null,origusername=null,origpassword=null,attachnum=0,attaches=[],removedattach=[],g_eye_show=!0,g_eyeimgid=null,g_start_time=null,POLL_MAXTIME=3E5,pass=!0,ENABLE_ONLY=!0,event_handlers={};
function fix_event_handlers(){lpdbg("site","fixing event handlers");for(var a in event_handlers){lpdbg("site","setting event handler for "+a);var c=document.getElementById("fields").contentWindow.document.getElementById(a);c?(c.onclick=event_handlers[a],lpdbg("site","set event handler for "+a)):lpdbg("site","could not find "+a)}}
function onLoad(a){clearData();if(a){var c=getBG();a=c.g_site_data.aid;if("undefined"==typeof a)data=c.g_site_data;else{data=c.g_site_data;var d=!1;"undefined"!==typeof c.g_site_data.save_all&&!0==c.g_site_data.save_all&&(d=!0);var b=get_record(a),k;for(k in b)data[k]=b[k]}c.g_generatedpw&&(document.getElementById("pwprotect").style.visibility="hidden",document.getElementById("pwprotectlabel").style.visibility="hidden");if((existing=data&&"undefined"!=typeof get_record_id(data)&&get_record_id(data)&&
""!=get_record_id(data)&&"0"!=get_record_id(data))&&!c.LPISLOC&&c.g_showhistorylinks)document.getElementById("usernamehistory").style.display="inline",document.getElementById("passwordhistory").style.display="inline";if(data){var b=issharedfolder(c.g_shares,data.group),g=!1==b?c.g_local_key:b.sharekey;"http://sn"==data.url&&c.loglogin(get_record_id(data));b=!1;if(is_application(data)){document.getElementById("usernamehistory").style.display="none";document.getElementById("passwordhistory").style.display=
"none";document.getElementById("urltext").innerHTML=gs("Application:");document.getElementById("url").value=data.appname;for(var e=0,f=0,h=0;h<data.fields.length;h++)if(""==data.fields[h].type){if(1<++e)break}else if("password"==data.fields[h].type&&1<++f)break;if(1!=e||1!=f)b=!0}else if(e=AES._utf8_decode(data.url),existing||!(0<=e.indexOf("homelocal")))document.getElementById("url").value=e;event_handlers={};data.editfields?(document.title=is_application(data)?gs("Edit Application Fields"):gs("Edit Site Fields"),
document.getElementById("siteactions").style.display="none",document.getElementById("urlrow").style.display="none",document.getElementById("namegrouprow").style.display="none",document.getElementById("usernamepasswordrow").style.display="none",document.getElementById("notesrow1").style.display="none",document.getElementById("notesrow2").style.display="none",document.getElementById("advsettingswrap").style.display="none",document.getElementById("fieldsrow2").style.display="block",document.getElementById("fields").contentWindow.document.body.innerHTML=
getFieldsHTML(g)):data.save_all||b?(document.getElementById("usernamepasswordrow").style.display="none",document.getElementById("fieldsrow1").style.display="block",document.getElementById("fieldsrow2").style.display="block",existing?(document.title=is_application(data)?gs("Edit Application"):gs("Edit Site"),document.getElementById("fields").contentWindow.document.body.innerHTML=getFieldsHTML(g)):(document.title=gs("Add Site"),document.getElementById("fields").contentWindow.document.body.innerHTML=
getDataHTML())):data.sn?(document.title=existing?gs("Edit Secure Note"):gs("Add Secure Note"),document.getElementById("usernamepasswordrow").style.display="none",document.getElementById("urlrow").style.display="none",document.getElementById("addrow").style.display="block",showadvpane()):existing?(is_application(data)?(document.title=gs("Edit Application"),document.getElementById("username").value=getusernamefromacct(data),document.getElementById("password").value=getpasswordfromacct(data),origusername=
c.lpmenc(document.getElementById("username").value,!0,g),origpassword=c.lpmenc(document.getElementById("password").value,!0,g)):(document.title=gs("Edit Site"),document.getElementById("username").value=data.unencryptedUsername,b=c.lpmdec(data.password,!0,g),document.getElementById("password").value=b,origusername=data.username,origpassword=data.password),document.getElementById("editfields").style.display="inline"):(document.title=gs("Add Site"),document.getElementById("username").value=data.username,
document.getElementById("password").value=data.password,disable_CPWButton());fix_event_handlers();!existing&&("undefined"!=typeof data.addsite&&-1==AES._utf8_decode(data.url).indexOf("homelocal"))&&(document.getElementById("group").value=get_default_group(data.url),document.getElementById("name").value=c.getname_url(data.url));existing?(document.getElementById("name").value=data.name,document.getElementById("group").value=data.group,b=c.lpmdec(data.extra,!0,g),document.getElementById("notes").value=
b,document.getElementById("fav").checked="1"==data.fav,document.getElementById("pwprotect").checked=data.pwprotect,document.getElementById("autologin").checked=data.autologin&&"0"!=data.autologin,is_application(data)?document.getElementById("never_autofill_td").style.visibility="hidden":document.getElementById("never_autofill").checked=data.never_autofill):data.sn&&(document.getElementById("group").value=gs("Secure Notes"));1==data.sn&&(document.getElementById("favcheck").style.display="none",document.getElementById("never_autofill_td").style.display=
"none",document.getElementById("autologingrp").style.visibility="hidden")}existing&&!data.editfields?(document.getElementById("del").style.display="inline-block",b=get_record(get_record_id(data)),document.getElementById("share").style.display=!c.LPISLOC&&!b.genpw&&("undefined"==typeof b.sharedfromaid||null==b.sharedfromaid||""==b.sharedfromaid||"0"==b.sharedfromaid||"null"==b.sharedfromaid)&&"undefined"==typeof b.sharefolderid&&!is_application(b)?"inline-block":"none"):(document.getElementById("del").style.display=
"none",document.getElementById("share").style.display="none");b=[];for(a in c.g_sites)c.check_ident_aid(a)&&(e=c.g_sites[a].group,""!=e&&!lp_in_array(e,b)&&(b[b.length]=e));for(a in c.g_securenotes)c.check_ident_aid(a)&&(e=c.g_securenotes[a].group,""!=e&&!lp_in_array(e,b)&&(b[b.length]=e));for(a in c.g_applications)c.check_ident_appaid(a)&&(e=c.g_applications[a].group,""!=e&&!lp_in_array(e,b)&&(b[b.length]=e));b.sort(function(a,b){return a.toLowerCase()<b.toLowerCase()?-1:1});if(!existing&&data&&
!data.save_all&&!data.noreplace){e=c.getsites(lp_gettld_url(data.url),!0);a=[];for(h in e)a[a.length]=h;a.sort(function(a,b){return c.g_sites[a].name.toLowerCase()<c.g_sites[b].name.toLowerCase()?-1:1});e=document.getElementById("replaceexistingsiteaid");for(h=0;h<a.length;h++)f=c.g_sites[a[h]].name,typeof c.g_sites[a[h]].useusername&&""!=c.g_sites[a[h]].useusername&&(f+=" ("+c.g_sites[a[h]].useusername+")"),e.options[e.options.length]=new Option(f,a[h]);if(1<e.options.length)for(h=1;4>=h;h++)document.getElementById("addreplacerow"+
h).style.display="block"}document.getElementById("metercontainer").innerHTML=ghetto_meter(280,!0);stylize_ghetto_meter(document,280);update_password_meter("",document.getElementById("password").value);data&&data.last_pwchange_gmt&&pw_age_update(data.last_pwchange_gmt);show_cpw_button(data);my_aid=get_record_id(data);buildSecureNotes(existing);onResize();create_combo("group",b,!0,document,"","group",-22,5);setup_eye_events(document);(getBG().g_is_win||getBG().g_is_mac||getBG().g_is_linux)&&setTimeout(function(){decryptThumbnails(g)},
0);document.getElementById("advsettings").addEventListener("click",showadvpane);document.getElementById("_docwrite_site14a").addEventListener("click",showadvpane);document.getElementById("fav").addEventListener("change",echoFavorite);echoFavorite();null!==document.getElementById("name")&&null!==document.getElementById("notestype")&&(document.getElementById("name").addEventListener("keyup",function(){setTimeout(updateFormHeading,100)}),updateFormHeading());data&&data.openchpw&&show_cpw_dialog("new");
data=c.g_site_data;for(k in c.g_site_data)data[k]=c.g_site_data[k];d&&(data.save_all=!0);c.g_site_data=null}else get_data("site",function(){onLoad(!0)})}
function updateFormHeading(){""!=document.getElementById("notestype").value?set_innertext(document.getElementById("dynheader"),document.getElementById("name").value+" - "+document.getElementById("notestype").value+(1==data.sn?" "+gs("Secure Note"):"")):(document.getElementById("dynheader").style.display="none",document.getElementById("dynbody").style.backgroundColor="transparent")}
function showadvpane(){var a=document.getElementById("advsettings"),c=document.getElementById("checkboxrow1");a.classList.toggle("turn90");c.classList.toggle("displaynone")}
function echoFavorite(){document.getElementById("fav").checked?(document.getElementById("echo_favorite").src="images/favorite.png",document.getElementById("_docwrite_site15").innerHTML=gs("Remove Favorite"),document.getElementById("_docwrite_site34").innerHTML=gs("Remove Site from Favorites")):(document.getElementById("echo_favorite").src="images/not_favorite.png",document.getElementById("_docwrite_site15").innerHTML=gs("Make Favorite"),document.getElementById("_docwrite_site34").innerHTML=gs("Add Site to Favorites"))}
function decryptThumbnails(a){if("undefined"!=typeof data&&(null!==data&&1==data.sn)&&(document.getElementById("lpaddattach").style.display="block","undefined"!=typeof data.attachpresent&&"1"==data.attachpresent)){getBG();num_attachments=data.attaches.length;for(var c in data.attaches)data.attaches.hasOwnProperty(c)&&(addThumbnail(data.attaches[c].id,data.attaches[c].mimetype,data.attaches[c].bytes,data.attaches[c].filename,data.attachkey,a),num_attachments--)}}
function buildSecureNotes(a){if("undefined"!=typeof data&&null!==data&&"undefined"!=typeof data.sn&&1==data.sn){document.getElementById("notesrow0").style.display="block";document.getElementById("notesrow1").style.display="none";document.getElementById("notehistory").style.display="inline-block";document.getElementById("group").style.width="auto";document.getElementById("group").spellcheck=!1;var c=document.getElementById("notestype").val,d=[],b;for(b in sntemplates){var k="undefined"!=typeof sntemplateicons[b]?
sntemplateicons[b]:geticonurl("sn");d[d.length]={label:gs(b),image:k,value:b}}a||(create_combo("notestype",d,!0,document,"","notestype",-22,5),document.getElementById("notestype").addEventListener("click",function(){openCombo(null,"notestype","notestype_combo",document)}));a&&(c=getNoteValue("NoteType",document.getElementById("notes").value));if(!c||"undefined"==typeof sntemplates[c])c="Generic";init_attachment_action_menu();document.getElementById("autologingrp").setAttribute("colspan","0");a=document.getElementById("pwaginggrp");
null!=a&&a.setAttribute("colspan","2");buildForm(c);onResize()}else document.getElementById("attachtabletr").style.width="0px"}function disable_CPWButton(){document.getElementById("cpwbtnmini").classList.add("btn_disabled")}function disable_SaveButton(){document.getElementById("save").classList.add("btn_disabled")}function enable_SaveButton(){document.getElementById("save").classList.remove("btn_disabled")}
function update_SaveButton(a){var c=document,d=c.getElementById("save");c&&d&&(check_for_changes()?0<=d.className.indexOf("btn_disabled")&&enable_SaveButton():a!=ENABLE_ONLY&&-1==d.className.indexOf("btn_disabled")&&disable_SaveButton())}
function buildForm(a){var c=document.getElementById("notestype");c.value=gs(a);c.val=a;var d="undefined"!=typeof sntemplateicons[a]?sntemplateicons[a]:geticonurl("sn");c.style.background="url("+d+") no-repeat 2px 2px"+(existing?" rgb(238,238,238)":" rgb(249,249,249)");document.getElementById("notesrow2").style.display="Generic"==a?"block":"none";document.getElementById("notesrow3").style.display="Generic"==a?"none":"block";document.getElementById("notestype").disabled=existing?!0:!1;if("Generic"!=
a){for(c=document.getElementById("dynamicnotes");c.hasChildNodes()&&0<c.childNodes.length;)c.removeChild(c.firstChild);d=sntemplates[a];a=document.createElement("table");a.style.width="100%";a.style.borderSpacing="0px";for(var b in d){var k=document.createElement("tr"),g=document.createElement("td");g.style.whiteSpace="nowrap";var e=document.createElement("td");e.style.width="100%";var f=document.createTextNode(gsproper(b)+":");g.appendChild(f);var h=f=null;if("text"==d[b])f=document.createElement("input"),
f.type="text",f.spellcheck=!1,f.id="note_"+b,f.style.width="100%",f.style.fontFamily="Courier",existing&&(f.value=getNoteValue(b,document.getElementById("notes").value),"Private Key"==b&&(-1==f.value.indexOf("-----BEGIN")&&-1==f.value.indexOf("END-----")?h=null:(h=document.createElement("a"),h.innerHTML=" Copy Key",h.style.textDecoration="none",h.style.cursor="pointer",h.style.height="15px",h.onclick=function(){var a=document.getElementById("note_Private Key");pkelparse=a.value.split(/-----BEGIN.*KEY----- | -----END.*KEY-----/);
pkelarmor=a.value.split(/-----/);pkelnew=pkelparse[1].replace(/\u0020/g,"\n");pktotal="-----"+pkelarmor[1]+"-----\n"+pkelnew+"\n-----"+pkelarmor[3]+"-----";getBG().copytoclipboard(pktotal);return!1},h.style.align="right"))),"Password"==b&&(f.type="password",h=document.createElement("img"),h.id="note_eye_img",h.src="images/eye-shown.png",h.style.textDecoration="none",h.style.position="relative",h.style.top="6px",h.style.left="-22px",h.onclick=function(){var a=document.getElementById("note_Password");
-1!==document.getElementById("note_eye_img").src.indexOf("images/eye-shown.png")?document.getElementById("note_eye_img").src="images/eye-hidden.png":document.getElementById("note_eye_img").src="images/eye-shown.png";a.type="password"==a.type?"text":"password"});else if("date"==d[b]||"datemoyr"==d[b]){f=document.createElement("span");f.style.width="100%";var j=document.createElement("select");j.id="note_"+b+"_mo";j.style.width="auto";var n="January February March April May June July August September October November December".split(" "),
m;for(m in n)j.options[j.options.length]=new Option(gs(n[m]),n[m]);var r=null;if(existing&&((r=getNoteValue(b,document.getElementById("notes").value))&&(r=r.split(",")),r&&0<r.length))for(var p in n)if(n[p]==r[0]||gs(n[p])==r[0]){j.value=n[p];break}f.appendChild(j);if("date"==d[b]){j=document.createElement("select");j.id="note_"+b+"_day";for(m=1;31>=m;m++)j.options[j.options.length]=new Option(m,m);r&&1<r.length&&(j.value=r[1]);f.appendChild(j)}j=document.createElement("input");j.type="text";j.maxLength=
4;j.size=4;j.spellcheck=!1;j.id="note_"+b+"_yr";n="date"==d[b]?2:1;r&&r.length>n&&(j.value=r[n]);f.appendChild(j)}else if("textarea"==d[b])g.style.verticalAlign="top",f=document.createElement("textarea"),f.cols=30,f.spellcheck=!1,f.rows=7,f.id="note_"+b,f.style.width="100%",existing&&(f.value=getNoteValue(b,document.getElementById("notes").value,!0));else continue;e.appendChild(f);null!==h&&e.appendChild(h);k.appendChild(g);k.appendChild(e);a.appendChild(k)}b=document.createElement("fieldset");b.appendChild(a);
c.appendChild(b);updateFormHeading()}}function onResize(){}
function fix_addreplace(){document.getElementById("addnewsite").checked?(document.getElementById("url").disabled=!1,document.getElementById("name").disabled=!1,document.getElementById("group").disabled=!1,document.getElementById("username").disabled=!1,document.getElementById("password").disabled=!1,document.getElementById("notes").disabled=!1,document.getElementById("fav").disabled=!1,document.getElementById("never_autofill").disabled=!1,document.getElementById("pwprotect").disabled=!1,document.getElementById("autologin").disabled=
!1,document.getElementById("replaceexistingsiteaid").disabled=!0):document.getElementById("replaceexistingsite").checked&&(document.getElementById("url").disabled=!0,document.getElementById("name").disabled=!0,document.getElementById("group").disabled=!0,document.getElementById("username").disabled=!0,document.getElementById("password").disabled=!0,document.getElementById("notes").disabled=!0,document.getElementById("fav").disabled=!0,document.getElementById("never_autofill").disabled=!0,document.getElementById("pwprotect").disabled=
!0,document.getElementById("autologin").disabled=!0,document.getElementById("replaceexistingsiteaid").disabled=!1)}
function getSecureNoteFromFields(){if("undefined"!=typeof data&&1==data.sn){var a=document.getElementById("notestype").val;if("Generic"==a||"none"==document.getElementById("notesrow0").style.display)return document.getElementById("notes").value;var c="NoteType:"+a+"\n",d;for(d in sntemplates[a])"text"==sntemplates[a][d]?c+=d+":"+document.getElementById("note_"+d).value+"\n":"date"==sntemplates[a][d]||"datemoyr"==sntemplates[a][d]?(c+=d+":"+document.getElementById("note_"+d+"_mo").value,"date"==sntemplates[a][d]&&
(c+=","+document.getElementById("note_"+d+"_day").value),c+=","+document.getElementById("note_"+d+"_yr").value+"\n"):"textarea"==sntemplates[a][d]&&(c+=d+":"+document.getElementById("note_"+d).value+"\n");return c}return document.getElementById("notes").value}function get_decrypted_attachdata(a){for(var c in g_encatt)if("undefined"!=typeof g_encatt[c].id&&g_encatt[c].id==a)return g_encatt[c].data;return""}
function dosave(a,c){var d=document.getElementById("replaceexistingsite").checked;if(d&&0==document.getElementById("replaceexistingsiteaid").selectedIndex)alert(gs("Please Make a Selection"));else{var b=getBG();if(b.lploggedin)if(data.editfields){var k=issharedfolder(b.g_shares,data.group);if(checkreadonly(k)){var g=!1==k?b.g_local_key:k.sharekey;if(is_application(data)){var e=get_record(get_record_id(data));e.last_touch=lp_get_gmt_timestamp();for(var f in e.fields){var d=e.fields[f],h=document.getElementById("fields").contentWindow.document.getElementById(d.htmlid);
h&&(d.value=b.lpmenc(h.value,!0,g))}var j="appaid="+b.en(e.appaid);for(f in e.fields)d=e.fields[f],j+="&fieldid"+f+"="+b.en(d.id)+"&fieldtype"+f+"="+b.en(d.type)+"&fieldvalue"+f+"="+b.en(crypto_btoa(d.value));j+=!1==k?"":"&sharedfolderid="+b.en(k.id);(g_issafari||g_isopera||g_ismaxthon||g_isfirefoxsdk)&&b.update_site(get_record_id(data));b.increment_local_accts_version();b.rewritelocalfile();b.saveSite(j,e)}else checkFieldsForUpdates(g);getBG().close_editfieldsopener();setTimeout(function(){getBG().closecurrenttab("site.html")},
0)}}else{var e=punycode.URLToASCII(trim(document.getElementById("url").value)),h=document.getElementById("name").value,j=document.getElementById("group").value,n=document.getElementById("username").value,m=document.getElementById("password").value,r=getSecureNoteFromFields(),p=document.getElementById("fav").checked,s=document.getElementById("never_autofill").checked,w=document.getElementById("pwprotect").checked,q=document.getElementById("autologin").checked,k=issharedfolder(b.g_shares,j);if(checkreadonly(k)){var x=
!1;if(existing&&j!=data.group){if(x=issharedfolder(b.g_shares,data.group),!checkmove(k,x))return}else existing&&(x=k);g=existing?!1==x?b.g_local_key:x.sharekey:!1==k?b.g_local_key:k.sharekey;d&&(q=b.g_sites[document.getElementById("replaceexistingsiteaid").value],h=q.name,j=q.group,k=issharedfolder(b.g_shares,j),g=!1==k?b.g_local_key:k.sharekey,r=b.lpmdec(q.extra,!0,g),p="1"==q.fav,s=q.never_autofill,w=q.pwprotect,q=q.autologin);if(""==h)alert(gs("You must enter a name."));else{if(45E3<r.length)if(confirm(gs("The notes field contains too much data.  You may store a maximum of 45,000 characters per note.\n\nWould you like us to truncate the note for you?  You will lose some of your data.")))r=
r.substring(0,45E3);else return;var u=!1;if(existing&&j!=data.group&&(k||x)){var l=[get_record_id(data)],t=[];t[get_record_id(data)]=j;u=!0;if(!b.moveIntoSharedFolder(k,x,l,t,!1,!0))return}if(existing&&is_application(data)){e=get_record(get_record_id(data));e.last_touch=lp_get_gmt_timestamp();p=getusernamefromacct(e);s=getpasswordfromacct(e);for(f in e.fields)if(d=e.fields[f],"none"!=document.getElementById("fieldsrow2").style.display){if(h=document.getElementById("fields").contentWindow.document.getElementById(d.htmlid))d.value=
b.lpmenc(h.value,!0,g)}else""==d.type&&b.lpmdec_acct(d.value,!0,e,b.g_shares)==p?d.value=b.lpmenc(document.getElementById("username").value,!0,g):"password"==d.type&&b.lpmdec_acct(d.value,!0,e,b.g_shares)==s&&(d.value=b.lpmenc(document.getElementById("password").value,!0,g));e.name=document.getElementById("name").value;e.group=document.getElementById("group").value;e.appname=document.getElementById("url").value;d=getSecureNoteFromFields();d!=b.lpmdec(e.extra,!0,g)&&(e.extra=lpmenc(d,!0,g));e.fav=
document.getElementById("fav").checked?"1":"0";e.pwprotect=document.getElementById("pwprotect").checked;e.autologin=document.getElementById("autologin").checked?"1":"0";var v=e.group;k&&(e.sharefolderid=k.id,v=v.substr(k.decsharename.length+1));if(j!=data.group&&(k||x))l=[get_record_id(data)],t=[],t[get_record_id(data)]=j,b.moveIntoSharedFolder(k,x,l,t,!1,!1,!0);else{j="ajax=1&extjs=1&cmd=updatelpaa&name="+b.en(b.lpenc(e.name,g))+"&grouping="+b.en(b.lpenc(v,g))+"&appname="+b.en(e.appname)+"&extra="+
b.en(crypto_btoa(e.extra))+"&appaid="+b.en(e.appaid);"1"==e.fav&&(j+="&fav=on");e.pwprotect&&(j+="&pwprotect=on");"1"==e.autologin&&(j+="&autologin=on");for(f in e.fields)d=e.fields[f],j+="&fieldid"+f+"="+b.en(d.id)+"&fieldtype"+f+"="+b.en(d.type)+"&fieldvalue"+f+"="+b.en(crypto_btoa(d.value));j+=!1==k?"":"&sharedfolderid="+b.en(k.id);(g_issafari||g_isopera||g_ismaxthon||g_isfirefoxsdk)&&b.update_site(get_record_id(data));b.increment_local_accts_version();b.rewritelocalfile();b.saveSite(j,e)}setTimeout(function(){getBG().closecurrenttab("site.html")},
0)}else{l=existing?data.sn?b.g_securenotes[get_record_id(data)]:b.g_sites[get_record_id(data)]:b.createNewAcct();v=!1;for(f in attaches)attaches.hasOwnProperty(f)&&"undefined"!=typeof attaches[f]&&(v=!0);if(v&&!c){"undefined"==typeof l.attachkey||""==l.attachkey?(t=SHA256(lpCreatePass(32,1,1,1,1,1,1,1)),g_attachkey=b.lpenc(t,g)):g_attachkey=l.attachkey;var t=AES.hex2bin(b.lpdec(g_attachkey,g)),y=[];for(f in attaches)attaches.hasOwnProperty(f)&&"undefined"!=typeof attaches[f]&&(attaches[f].filename=
lpenc(attaches[f].filename,t),y[y.length]={id:attaches[f].id,bytes:attaches[f].bytes});if(y.length){b.fastEncryptAttachments(t,y,function(a){g_encatt=a;dosave(null,!0)});return}}y=lp_gettld_url(AES._utf8_encode(e));if(existing&&!data.sn&&l.tld!=y&&!a&&b.g_prompts.view_pw_prompt)b.security_prompt(function(){dosave(1,c)});else{existing&&!l.sn&&b.fix_tlds(l.tld,y,get_record_id(data));l.genpw=!1;l.name=h;u||(l.group=j);"http://sn"==e?(l.url=e,l.sn=1):l.url=AES._utf8_encode(e);l.tld=y;l.unencryptedUsername=
n;n!=b.lpmdec(l.username,!0,g)&&(l.username=b.lpmenc(n,!0,g));m!=b.lpmdec(l.password,!0,g)&&(l.password=b.lpmenc(m,!0,g));r!=b.lpmdec(l.extra,!0,g)&&(l.extra=b.lpmenc(r,!0,g));l.fav=p?"1":"0";l.autologin=q;l.never_autofill=s;l.pwprotect=w;existing||(l.aid="0");!1!=k&&(l.sharefolderid=k.id,0==k.give&&(l.sharedfromaid=1));u="";t=[];if(v){if("undefined"==typeof l.attachkey||""==l.attachkey)l.attachkey=g_attachkey,u+="&attachkey="+b.en(l.attachkey);l.attachpresent="1";l.retrieveattach=1;v=0;for(f in attaches)attaches.hasOwnProperty(f)&&
"undefined"!=typeof attaches[f]&&(u+="&filename"+v+"="+b.en(attaches[f].filename),u+="&mimetype"+v+"="+b.en(attaches[f].mimetype),u+="&attachid"+v+"="+b.en(attaches[f].id),u+="&attachbytes"+v+"="+b.en(get_decrypted_attachdata(attaches[f].id)),"undefined"==typeof t.add&&(t.add=[]),t.add[t.add.length]=existing?{id:l.aid+"-"+attaches[f].id,mimetype:attaches[f].mimetype,parent:l.aid,filename:attaches[f].filename}:{id:attaches[f].id,mimetype:attaches[f].mimetype,filename:attaches[f].filename},v++)}if(0<
removedattach.length){l.retrieveattach=1;for(f=0;f<removedattach.length;f++)u+="&rmattach"+f+"="+b.en(removedattach[f]),"undefined"==typeof t.remove&&(t.remove=[]),t.remove[t.remove.length]=removedattach[f]}v=j;k&&(v=j.substr(k.decsharename.length+1));if(existing){if(e!=data.url||h!=data.name||j!=data.group||n!=data.unencryptedUsername||m!=b.lpmdec(data.password,!0,g)||r!=b.lpmdec(data.extra,!0,g)||p!=("1"==data.fav)||s!=data.never_autofill||w!=data.pwprotect||q!=data.autologin||0<attaches.length||
0<removedattach.length){l.sn?b.g_securenotes[l.aid]=l:b.g_sites[l.aid]=l;for(f in l.fields)if(l.fields.hasOwnProperty(f)&&(d=l.fields[f],is_encrypted_field(d.type)&&(null!=origpassword&&""!=origpassword&&null!=d.value&&""!=d.value&&b.lpmdec_acct(d.value,!0,l,b.g_shares)==b.lpmdec_acct(origpassword,!0,l,b.g_shares))&&"password"==d.type&&(d.value=l.password),is_encrypted_field(d.type)&&(null!=origusername&&""!=origusername&&null!=d.value&&""!=d.value&&b.lpmdec_acct(d.value,!0,l,b.g_shares)==b.lpmdec_acct(origusername,
!0,l,b.g_shares))&&("text"==d.type||"email"==d.type||"tel"==d.type||"url"==d.type)))d.value=l.username;if(j!=data.group&&(k||x)){l=[get_record_id(data)];t=[];t[get_record_id(data)]=j;b.moveIntoSharedFolder(k,x,l,t,!1,!1,!0);setTimeout(function(){getBG().closecurrenttab("site.html")},0);return}(g_issafari||g_isopera||g_ismaxthon||g_isfirefoxsdk)&&b.update_site(get_record_id(data));b.applyattacharraychanges(t);b.increment_local_accts_version();b.rewritelocalfile();j="ajax=1&extjs=1&name="+b.en(b.lpenc(h,
g))+"&url="+b.en(AES.url2hex(e))+"&grouping="+b.en(b.lpenc(v,g))+"&username="+b.en(crypto_btoa(l.username))+"&password="+b.en(crypto_btoa(l.password))+"&extra="+b.en(crypto_btoa(l.extra))+"&openid_url=&aid="+b.en(get_record_id(data))+"&basic_auth=0&isbookmark=0&localupdate=1";j=j+(w?"&pwprotect=on":"")+(s?"&never_autofill=on":"");j+=q?"&autologin=on":"";j+=p?"&fav=on":"";j+=!1==k?"":"&sharedfolderid="+b.en(k.id);"http://sn"==e&&("undefined"!==typeof b.g_loglogins&&b.g_loglogins)&&(j+="&n="+AES.url2hex(h));
j+=u;l.attacharraychanges=t;l.newvalues=[];b.saveSite(j,l);k=b.getsites(y,!0);m!=b.lpmdec(data.password,!0,g)&&1<array_length(k)&&b.openLinkedSites(m,y)}data.save_all&&checkFieldsForUpdates(g)}else l.fields=[],f=[],j=updateAndEncryptData2(b,l.username,l.password,l.fields,l,f,g),j="name="+b.en(b.lpenc(h,g))+"&grouping="+b.en(b.lpenc(v,g))+"&data="+b.en(b.bin2hex(j))+"&extra="+b.en(b.lpenc(r,g))+(w?"&pwprotect=on":"")+(s?"&never_autofill=on":"")+(q?"&autologin=on":"")+(p?"&fav=on":""),j+="&extjs=1&localupdate=1",
j+=!1==k?"":"&sharedfolderid="+b.en(k.id),"undefined"!=typeof data.realm&&(l.realm=b.lpmenc(data.realm,!0,g),l.basic_auth="1",j+="&basic_auth=1&realm="+b.en(b.lpenc(l.realm,g))),"http://sn"==e&&(g=getNoteValue("NoteType",r),j+=g&&""!=g?"&notetype="+b.en(g):""),d&&(j+="&replacing=1"),j+=u,data.save_all?(l.save_all=!0,j+="&ajax=1&aid=0&save_all=1&url="+b.en(AES.url2hex(e))+"&openid_url=&username=&password=",l.newvalues=f,b.saveAllSite(j,l)):"undefined"!=typeof data.formdata?(j+="&ref="+b.en(AES.url2hex(e)),
d&&(j+="&aid="+b.en(document.getElementById("replaceexistingsiteaid").value)),"undefined"!=typeof data.createacct&&(data.createacct&&"undefined"!=typeof data.username_field)&&(l.fields=[],j+="&createacct=1&username_field="+b.en(data.username_field)),l.newvalues=f,b.saveSiteFromSubmit(j,l)):(j+="&ajax=1&aid=0&url="+b.en(AES.url2hex(e))+"&openid_url=&username="+b.en(crypto_btoa(l.username))+"&password="+b.en(crypto_btoa(l.password)),l.newvalues=f,l.attacharraychanges=t,b.saveSite(j,l));setTimeout(function(){getBG().closecurrenttab("site.html")},
0)}}}}}else console_log("Not logged in!")}}
function checkFieldsForUpdates(a){var c=getBG(),d=document.getElementById("fields").contentWindow.document,b=!1,k;for(k in data.fields){var g=data.fields[k];if(is_encrypted_field(g.type)){var e=d.getElementById(g.htmlid);if(e&&"undefined"!=typeof e.value&&c.lpmdec(g.value,!0,a)!=e.value){var b=!0,f=c.lpmenc(e.value,!0,a);""!=g.value&&(""!=c.g_sites[get_record_id(data)].username&&g.value==c.g_sites[get_record_id(data)].username&&""!=e.value)&&(c.g_sites[get_record_id(data)].username=f,c.g_sites[get_record_id(data)].unencryptedUsername=
e.value);""!=g.value&&(""!=c.g_sites[get_record_id(data)].password&&g.value==c.g_sites[get_record_id(data)].password&&""!=e.value)&&(c.g_sites[get_record_id(data)].password=f);g.value=f}}else if("checkbox"==g.type||"radio"==g.type)e=g.checked,f=d.getElementById(g.htmlid)&&d.getElementById(g.htmlid).checked,e!=f&&(b=!0,g.checked=f);else if("select-one"==g.type&&g.faketype&&(e=d.getElementById(g.htmlid))&&"undefined"!=typeof e.value&&g.value!=e.value)b=!0,g.value=e.value}if(b){if(g_issafari||g_isopera||
g_ismaxthon||g_isfirefoxsdk)c.update_site(get_record_id(data)),c.update_fields(get_record_id(data),data.fields);c.increment_local_accts_version();c.rewritelocalfile();a="update=1&aid="+c.en(get_record_id(data))+"&urid=0";b="";e=[];for(k in data.fields)if(g=data.fields[k],g.htmlid&&d.getElementById(g.htmlid))if(f=data.editfields&&""==g.formname?"_"+g.name:"_"+g.formname+"_"+g.name,is_encrypted_field(g.type)){var h=d.getElementById(g.htmlid).value;e.push(h);h=crypto_btoa(g.value);b+=f+"="+c.en(h)+"&"}else"checkbox"==
g.type?d.getElementById(g.htmlid).checked&&(b+=f+"="+c.en(g.value)+"&"):"select-one"==g.type&&g.faketype&&(h=d.getElementById(g.htmlid).value,b+=f+"="+c.en(h)+"&");b+="&auto=1";d=issharedfolder(c.g_shares,data.group);b+=!1==d?"":"&sharedfolderid="+c.en(d.id);c.saveFields(a,b,{url:base_url+"fields.php?"+a,aid:data.aid,postdata:b,param:null,newvalues:e})}}
function updateAndEncryptData2(a,c,d,b,k,g,e){for(var f="",h="undefined"!=typeof data.formdata?data.formdata.split("\n"):[],j=!1,n=0,m=0,r=0;r<h.length;r++){var p=h[r],p=p.split("\t");4!=p.length&&5!=p.length||("text"==p[3]||"email"==p[3]||"tel"==p[3]||"url"==p[3]?n++:"password"==p[3]&&m++)}0==n&&(2==m&&!data.save_all)&&(j=!0);for(r=0;r<h.length;r++)if(p=h[r],p=p.split("\t"),!(4!=p.length&&5!=p.length)){var n=data.save_all?decodeURIComponent(p[0]):"0",m=decodeURIComponent(p[1]),s=decodeURIComponent(p[2]),
w=getBG().lpmenc(s,!0,e),p=p[3];if("text"==p||"password"==p||"hidden"==p||"textarea"==p||"email"==p||"tel"==p||"url"==p){if("email"==p&&s==data.username&&(w=c),"tel"==p&&s==data.username&&(w=c),"url"==p&&s==data.username&&(w=c),"text"==p&&s==data.username&&(w=c),"password"==p&&j?(w=c,j=!1):"password"==p&&s==data.password&&(w=d),s=lpmdec(w,!0,e),g&&g.push(s),f+=n+"\t"+a.en(m)+"\t"+a.en(crypto_btoa(w))+"\t"+a.en(p)+"\n","hidden"!=p){var q=[];q.otherfield=data.save_all;q.name=m;q.type=p;q.value=w;q.checked=
!1;q.formname=data.save_all?n:"";q.urid="0";q.otherlogin="0";q.url="";b[b.length]=q}}else if("action"==p)f+=n+"\taction\t"+a.en(s)+"\taction\n",k.action=AES.url2hex(s);else if("method"==p)f+=n+"\tmethod\t"+a.en(s)+"\tmethod\n",k.method=s;else if(f+=n+"\t"+a.en(m)+"\t"+a.en(s)+"\t"+a.en(p)+"\n","checkbox"==p||"radio"==p||"select-one"==p)q=[],q.otherfield=data.save_all,q.name=m,q.type=p,"checkbox"==p||"radio"==p?(q.checked="-1"==s.substring(s.length-2),q.value=s.substring(0,s.length-2)):q.value=s,q.formname=
data.save_all?n:"",q.urid="0",q.otherlogin="0",q.url="",b[b.length]=q}return f}
function getDataHTML(){for(var a='<link rel="stylesheet" type="text/css" href="general.css">',c=data.formdata.split("\n"),d=0;d<c.length;d++){var b=c[d].split("\t");if(!(4!=b.length&&5!=b.length)){var k=data.save_all?decodeURIComponent(b[0]):"0",g=decodeURIComponent(b[1]),e=decodeURIComponent(b[2]),b=b[3],k=uniqid(k+"_"+g);if("text"==b||"password"==b||"email"==b||"tel"==b||"url"==b)a+=ofja(g)+' <input readonly id="'+ofja(k)+'" name="'+ofja(g)+'" type="'+ofja(b)+'" value="'+ofa(e)+'">',"password"==
b&&(event_handlers[k+"toggle"]=function(){parent.toggle_password(document.getElementById("fields").contentWindow.document.getElementById(this.id.substring(0,this.id.length-6)),this);return!1},g_eyeimgid=k+"toggleimg",a+=' <a id="'+ofja(k)+'toggle" href="#" class="eye"><img id = "'+ofja(g_eyeimgid)+'" src="images/eye-shown.png" alt="'+gs("[Show]")+'"/></a>'),a+="<br>";else if("textarea"==b)a+=ofja(g)+' <textarea readonly name="'+ofja(g)+'">'+ofa(e)+"</textarea><br>";else if("select-one"==b)a+=ofja(g)+
' <select name="'+ofja(g)+'"><option value="'+ofa(e)+'">'+ofa(e)+"</option></select><br>";else if("checkbox"==b||"radio"==b)checked="-1"==e.substring(e.length-2)?" checked":"","radio"==b&&""==checked||(e=e.substring(0,e.length-2),a+='<input disabled type="'+ofja(b)+'" value="'+ofa(e)+'"'+checked+"> "+ofja(g)+"<br>")}}return a}
function showaddfield(){var a=getBG(),a=issharedfolder(a.g_shares,data.group);checkreadonly(a)&&(a=document.getElementById("fields").contentWindow.document,a.getElementById("addfield").style.display="block",a.getElementById("newname").focus())}
function doaddfield(){var a=getBG(),c=issharedfolder(a.g_shares,data.group);if(checkreadonly(c)){var d=document.getElementById("fields").contentWindow.document,b=d.getElementById("newname").value,k=d.getElementById("newtype").value,g=k;"select-one"==g&&(g="text");var e=d.getElementById("newformname")?d.getElementById("newformname").value:"";if(""==b)alert(gs("You must enter a name."));else{for(var f in data.fields)if(data.fields[f].name==b&&(data.editfields||data.fields[f].formname==e)){alert(gs("You must enter a unique name."));
return}f=uniqid(e+"_"+b);var h="";"text"==k||"password"==k||"select-one"==k||"email"==k||"tel"==k||"url"==k?(h+=ofja(b)+' <input id="'+ofja(f)+'" type="'+ofja(g)+'">',"password"==k&&(g_eyeimgid=f+"toggleimg",h+=' <a id="'+ofja(f)+'toggle" href="#" class="eye"><img id = "'+ofja(g_eyeimgid)+'" src="images/eye-shown.png" alt="'+gs("[Show]")+'"/></a>')):"textarea"==k?h+=ofja(b)+' <textarea id="'+ofja(f)+'"></textarea>':"checkbox"==k&&(h+='<input type="'+ofja(k)+'" id="'+ofja(f)+'"> <label for="'+ofja(f)+
'">'+ofja(b)+"</label>");var h=h+(' <a href="#" id="'+ofja(f)+'delete" data-lpname="'+ofja(b)+'">[&nbsp;-&nbsp;]</a>'),j=d.createElement("div");j.id=f+"_div";j.innerHTML=h;d.body.appendChild(j);event_handlers={};"password"==k&&(event_handlers[f+"toggle"]=function(){parent.toggle_password(document.getElementById("fields").contentWindow.document.getElementById(this.id.substring(0,this.id.length-6)),this);return!1});event_handlers[f+"delete"]=function(){parent.delete_field(this.id.substring(0,this.id.length-
6)+"_div",this.getAttribute("data-lpname"),"");return!1};lpdbg("site","1 added event handler for "+f+"delete");fix_event_handlers();h={};h.otherfield=!data.editfields;h.name=b;h.type=k;"select-one"==k&&(h.faketype=g);h.value="";h.formname=e;h.checked=!1;h.urid="0";h.otherlogin="0";h.url="";h.htmlid=f;data.fields[data.fields.length]=h;(g_issafari||g_isopera||g_ismaxthon||g_isfirefoxsdk)&&a.update_fields(get_record_id(data),data.fields);a.increment_local_accts_version();a.rewritelocalfile();b="add=1&aid="+
a.en(data.aid)+"&urid=0&name="+a.en(b)+"&type="+k;data.editfields||(b+="&formname="+a.en(e));b+="&auto=1";c=!1==c?"":"sharedfolderid="+a.en(c.id);a.saveFields(b,c,{url:base_url+"fields.php?"+b,aid:data.aid,postdata:c,param:null,newvalues:[]});d.getElementById("newname").value="";d.getElementById("newtype").selectedIndex=0;d.getElementById("newformname")&&(d.getElementById("newformname").value="");d.getElementById("addfield").style.display="none"}}}
function getFieldsHTML(a){var c=getBG(),d='<link rel="stylesheet" type="text/css" href="general.css">';is_application(data)||(event_handlers.addfieldlink=function(){parent.showaddfield();return!1},event_handlers.doaddfield=function(){parent.doaddfield()},d+='<a href="#" id="addfieldlink">'+gs("Add Field")+'</a><br><div id="addfield" class="displaynone">'+gs("Name:")+' <input type="text" id="newname" value=""><br>'+gs("Type:")+' <select id="newtype"><option value="text">'+gs("Text")+'</option><option value="password">'+
gs("Password")+'</option><option value="select-one">'+gs("Select")+'</option><option value="checkbox">'+gs("Checkbox")+"</option></select><br>",data.editfields||(d+=gs("Form Name:")+' <input type="text" id="newformname" value=""><br>'),d+='<input type="button" value="'+gs("Add")+'" id="doaddfield"><br><br></div>');var b=[],k;for(k in data.fields){var g=data.fields[k],e=g.formname,f=is_application(data)?k:g.name,h=g.value?g.value:"",j=h,n=g.type,m=f+"_"+n+"_"+h;if("undefined"==typeof b[m]){b[m]=!0;
e=uniqid(e+"_"+f);g.htmlid=e;m="";if(is_application(data)&&""==n||"text"==n||"password"==n||"email"==n||"tel"==n||"url"==n)j=crypto_btoa(h),h=c.lpmdec(h,!0,a),m+=ofja(f)+' <input id="'+ofja(e)+'" type="'+ofja(n)+'" value="'+ofa(h)+'">',"password"==n&&(event_handlers[e+"toggle"]=function(){parent.toggle_password(document.getElementById("fields").contentWindow.document.getElementById(this.id.substring(0,this.id.length-6)),this);return!1},m+=' <a id="'+ofja(e)+'toggle" href="#">'+gs("[Show]")+"</a>");
else if("textarea"==n)j=crypto_btoa(h),h=c.lpmdec(h,!0,a),m+=ofja(f)+' <textarea id="'+ofja(e)+'">'+ofa(h)+"</textarea>";else if("select-one"==n)m+=ofja(f)+' <select id="'+ofja(e)+'"><option value="'+ofa(h)+'">'+ofa(h)+"</option></select>";else if("checkbox"==n||"radio"==n){g=g.checked?" checked":"";if("radio"==n&&""==g)continue;m+='<input type="'+ofja(n)+'" id="'+ofja(e)+'" '+g+'> <label for="'+ofja(e)+'">'+ofja(f)+"</label>"}else continue;is_application(data)||(event_handlers[e+"delete"]=function(){parent.delete_field(this.id.substring(0,
this.id.length-6)+"_div",this.getAttribute("data-lpname"),AES.hex2bin(this.getAttribute("data-lporigval")));return!1},lpdbg("site","2 added event handler for "+e+"delete"),m+=' <a href="#" id="'+ofja(e)+'delete" data-lpname="'+ofja(f)+'" data-lporigval="'+AES.bin2hex(j)+'">[&nbsp;-&nbsp;]</a>');d+='<div id="'+ofja(e)+'_div">'+m+"</div>"}}return d}
function delete_field(a,c,d){try{if(confirm(gs("Are you sure you would like to delete this field?"))){var b=getBG(),k=issharedfolder(b.g_shares,data.group);if(checkreadonly(k)){var g=document.getElementById("fields").contentWindow.document;if(g.getElementById(a)){g.getElementById(a).style.display="none";for(var e in data.fields)if(data.fields.hasOwnProperty(e)&&data.fields[e].name==c){var f=data.fields[e].value;is_encrypted_field(data.fields[e].type)&&(f=crypto_btoa(f));f==d&&data.fields.splice(e,
1)}(g_issafari||g_isopera||g_ismaxthon||g_isfirefoxsdk)&&b.update_fields(get_record_id(data),data.fields);b.increment_local_accts_version();b.rewritelocalfile();var h="delete=1&aid="+b.en(get_record_id(data))+"&urid=0&name="+b.en(c)+"&value="+b.en(d),h=h+"&auto=1",j=!1==k?"":"sharedfolderid="+b.en(k.id);b.saveFields(h,j,{url:base_url+"fields.php?"+h,aid:data.aid,postdata:j,param:null,newfields:[]})}else alert("Sorry, deletion of the field failed. Please re-save the site.")}}}catch(n){console_log("caught exception in delete_field: "+
n.message)}}function dodel(){getBG().deleteAid(get_record_id(data),window,!1,!1,function(){setTimeout(function(){getBG().closecurrenttab("site.html")},0)})}function doshare(){if(!check_for_changes()||confirm(gs("Are you sure you want to share this item?  Doing so will cause you to lose any changes you have made to this item!"))){var a=getBG();a.unlock_plug2web();a.openbaseurl("?ac=1&share="+a.en(get_record_id(data)));setTimeout(function(){window_close("site.html")},0)}}
function docancel(){setTimeout(function(){getBG().closecurrenttab("site.html")},0)}function show_history(a){if(!check_for_changes()||confirm(gs("Are you sure you want to view history?  Doing so will cause you to lose any changes you have made to this item!"))){var c=getBG();c.unlock_plug2web();c.openbaseurl("?ac=1&"+(a?"username":"password")+"history="+c.en(get_record_id(data)));setTimeout(function(){window_close("site.html")},0)}}var logged=!1;
function toggle_password(a,c){if("password"==a.type){if(existing){var d=getBG();if(null!=data.sharedfromaid&&""!=data.sharedfromaid&&"0"!=data.sharedfromaid&&"null"!=data.sharedfromaid){alert(gs("This is a shared site. You are not permitted to view the password."));return}if(d.g_prompts.view_pw_prompt){g_eye_show&&null!=c&&"undefined"!=typeof c.children[0]&&"undefined"!=typeof c.children[0].children[0]?d.security_prompt(function(){a.type="text";c.children[0].children[0].src=get_eye_src(a.type,"glow");
c.children[0].children[0].setAttribute("alt",gs("[Hide]"));set_innertext(c.children[0].children[1],gs("Hide Password"))}):d.security_prompt(function(){a.type="text";c.innerHTML=gs("[Hide]")});return}}existing&&!logged&&(d.loglogin(get_record_id(data)),logged=!0);a.type="text";g_eye_show&&null!=c&&"undefined"!=typeof c.children[0]&&"undefined"!=typeof c.children[0].children[0]?(c.children[0].children[0].src=get_eye_src(a.type,"glow"),c.children[0].children[0].setAttribute("alt",gs("[Hide]")),set_innertext(c.children[0].children[1],
gs("Hide Password"))):c.innerHTML=gs("[Hide]")}else a.type="password",g_eye_show&&null!=c&&"undefined"!=typeof c.children[0]&&"undefined"!=typeof c.children[0].children[0]?(c.children[0].children[0].src=get_eye_src(a.type),c.children[0].children[0].setAttribute("alt",gs("[Show]")),set_innertext(c.children[0].children[1],gs("Show Password"))):c.innerHTML=gs("[Show]")}function gsproper(a){return gs(a+"proper")!=a+"proper"?gs(a+"proper"):gs(a)}
function check_for_changes(){var a=getBG(),c=document.getElementById("url").value,d=document.getElementById("name").value,b=document.getElementById("group").value,k=document.getElementById("username").value,g=document.getElementById("password").value,e=getSecureNoteFromFields(),f=document.getElementById("fav").checked,h=document.getElementById("never_autofill").checked,j=document.getElementById("pwprotect").checked,n=document.getElementById("autologin").checked,m=issharedfolder(a.g_shares,b),m=!1==
m?a.g_local_key:m.sharekey;return is_application(data)?c!=data.appname||d!=data.name||b!=data.group||k!=getusernamefromacct(data)||g!=getpasswordfromacct(data)||e!=a.lpmdec(data.extra,!0,m)||f!=("1"==data.fav)||j!=data.pwprotect||n!=("1"==data.autologin):c!=data.url||d!=data.name||b!=data.group||k!=data.unencryptedUsername||g!=a.lpmdec(data.password,!0,m)||e!=a.lpmdec(data.extra,!0,m)||f!=("1"==data.fav)||h!=data.never_autofill||j!=data.pwprotect||n!=data.autologin}
function doeditfields(){var a=getBG();if(!check_for_changes()||confirm(is_application(data)?gs("LoseChangesApp"):gs("LoseChanges"))){a.g_site_data=[];for(var c in data)a.g_site_data[c]=data[c];a.g_site_data.editfields=1;a.set_editfieldsopener(window);a.openURL(getchromeurl("site.html"),null,a.g_site_data)}}function showattach(a){a.getAttribute("src_hidden")&&a.getAttribute("src_hidden").length?getBG().showImageAttach(a.getAttribute("src_hidden")):openattach(a)}
function openattach(a){var c=a.getAttribute("filename")?a.getAttribute("filename"):"";getBG().openAttach(get_record_id(data),a.getAttribute("attachid"),c)}function addattach(){getBG().have_binary()?getBG().addAttach(function(){getBG().g_ischrome&&addattachcb()}):confirm(gs("This feature requires the binary version of this browser extension.  Would you like to install it now?"))&&getBG().install_binary()}
function addThumbnail(a,c,d,b,k,g){var e=get_extension_from_mimetype(c),f=check_filename_badchars(e),h=null,h=f==FILENAME_FRAGMENT_VALID?"."+e:0==f.length||f==FILENAME_FRAGMENT_EMPTY?"":"."+gs(e);if(k&&g)try{var j=AES.hex2bin(lpdec(k,g));b=lpdec(b,j)}catch(n){b=""}if(null===b||""==b)b="attachment"+num_attachments+h;e=document.getElementById("attachtable");f=document.createElement("tr");h=document.createElement("td");h.id=a;h.style.height="28px";h.style.width="80%";h.style.background="url('images/paperclip.png') no-repeat 2px 2px #e6e6e6";
var m=document.createElement("span");m.style.fontWeight="bold";m.style.position="relative";m.style.left="32px";m.style.top="6px";m.style.cursor="pointer";m.appendChild(document.createTextNode(b));d&&""!=d&&0==c.indexOf("data:image")?(m.setAttribute("attachid",a),k?getBG().fastDecryptAttachment(a,c,d,k,g,function(a){getBG().g_ischrome&&(a&&a.length?m.setAttribute("src_hidden",c+";base64,"+a):m.setAttribute("src_hidden",""),m.addEventListener("click",function(){attachment_action_menu(this,showattach)}))}):
(d&&d.length?m.setAttribute("src_hidden",c+";base64,"+d):m.setAttribute("src_hidden",""),getBG().have_binary()?m.addEventListener("click",function(){attachment_action_menu(this,showattach)}):m.addEventListener("click",function(){showattach(this)}))):(m.setAttribute("attachid",a),getBG().have_binary()?m.addEventListener("click",function(){attachment_action_menu(this,openattach)}):m.addEventListener("click",function(){openattach(this)}));d=document.createElement("span");d.className="attachx";d.setAttribute("attachid",
a);d.addEventListener("click",function(){rmattach(this)});d.innerHTML="&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";h.appendChild(m);h.appendChild(d);f.appendChild(h);e.insertBefore(f,e.firstChild);attachnum++}function createAttachId(){for(;;){var a=Math.floor(99999*Math.random()),c;for(c in data.attaches)if(data.attaches.hasOwnProperty(c)&&data.attaches[c].id==get_record_id(data)+"-"+a)break;for(c=0;c<attaches.length&&!("undefined"!=typeof attaches[c]&&attaches[c].id==a);c++);return a}}
function rmattach(a){a=a.getAttribute("attachid");if(confirm(gs("Are you sure you would like to remove this attachment?"))){if("undefined"!=typeof data.attachpresent&&"1"==data.attachpresent)for(var c in data.attaches)data.attaches.hasOwnProperty(c)&&a==data.attaches[c].id&&(removedattach[removedattach.length]=a);delete attaches[a];delThumbnail(a)}}
function delThumbnail(a){for(var c=document.getElementById("attachtable"),d=0;d<c.children.length;d++){var b=c.children[d];if(b.children&&b.children.length&&b.children[0].id==a){c.removeChild(b);break}}}
function attachment_action_doSave(){if(null!=open_attach_target){var a=open_attach_target.getAttribute("filename")?open_attach_target.getAttribute("filename"):"";getBG().exportAttachment(get_record_id(data),open_attach_target.getAttribute("attachid"),a)}else alarm("error, trying to save an attachment that does not exist");close_attach_list()}
function clearData(){for(var a=document.getElementsByTagName("input"),c=0;c<a.length;c++)"button"!=a[c].type&&(a[c].value="");a=document.getElementsByTagName("textarea");for(c=0;c<a.length;c++)a[c].value=""}function uniqid(a){a||(a="");return"a"+SHA256(a+"_"+(new Date).getTime()+"_"+Math.floor(100*Math.random()))}function setup_eye_events(a){g_eye_show&&(a.getElementById("passwordtoggle"),a.getElementById("passwordtoggleimg").style.verticalAlign="bottom")}
function eye_over(a){if(!(null==a||null==a.target)){var c=document.getElementById("passwordtoggleimg"),d=document.getElementById("password");a.target==c&&(c.src=get_eye_src(d.type,"glow"))}}function eye_out(a){if(!(null==a||null==a.target)){var c=document.getElementById("passwordtoggleimg"),d=document.getElementById("password");a.target==c&&(c.src=get_eye_src(d.type))}}function get_eye_src(a){return"password"==a?"images/eye-shown.png":"images/eye-hidden.png"}var CPW_WAKETIME=97,my_aid=null;
function docpwbtn(){var a=getBG();if(!document||!a||!data)return!1;var c=data.aid,d=data.url;g_cpwbot&&d?"undefined"!=typeof a.dopwchange?(g_start_time=(new Date).getTime(),a.cpwbot_preinit(),g_cpw_progress_ctr=20,show_cpw_dialog("progress"),setTimeout(function(){cpw_status_check()},CPW_WAKETIME),a.dopwchange(c,!1)):pass:pass;return!1}
function docpwdebug(){var a=getBG(),c=document;if(!c||!a||!data)return!1;if(g_cpwbot){if(document.getElementById("cpwmsgdiv"))return!1;a=c.createElement("div");a.style.height="200px";a.style.width="100%";a.style.overflow="auto";a.style.backgroundColor="blue";a.style.color="yellow";a.style.padding="3px";a.id="cpwmsgdiv";var d=c.getElementById("sitebody");d?d.appendChild(a):c.body.appendChild(a)}return!1}var g_cpw_progress_ctr=0,g_lastmsg="";
function cpw_status_check(){var a=getBG(),c=document;if(!c||!a||!data)return!1;var d=!1,b=!1,k=!1,g=!1,e=!1,f=!1;(c=c.getElementById("cpwmsgdiv"))&&(g_ischrome?set_innertext(c,a.cpwbot_get_user_debug_messages()):a.cpwbot_get_user_debug_messages());g_ischrome?(a=a.cpwbot_get_dialog_msg(),cpw_progress_update(a)):a.cpwbot_get_dialog_msg();a=get_current_state(!0);lpdbg("site","BG.current_state is "+a);switch(a){case "FAIL":b=d=!0;break;case "CAPTCHA":k=b=d=!0;break;case "DOCAPTCHA":g=!0;break;case "TIMEOUT":f=
b=d=!0;break;case "FAIL_PW_SAVED":e=b=d=!0;break;case "DONE":case "OK":d=!0;break;case 0:case null:d=!1}form_refresh();g?g_start_time=(new Date).getTime():(new Date).getTime()>g_start_time+POLL_MAXTIME&&(b=d=!0,lpdbg("site","max timeout"));lpdbg("site",sprintf("done=%s, captcha=%s, docaptcha=%s, timeout=%s, fail=%s, fail_pw_saved=%s",d,k,g,f,b,e));d?(b?k?show_cpw_dialog("captcha"):f?show_cpw_dialog("timeout"):e?show_cpw_dialog("fail_pw_saved"):show_cpw_dialog("fail"):show_cpw_dialog("dismiss"),lpdbg("site",
"setup delayed form_refresh on complete"),g_ischrome?setTimeout(function(){form_refresh()},3001):setTimeout(function(){get_data("siterefresh",function(){form_refresh()})},3001)):setTimeout(function(){cpw_status_check()},CPW_WAKETIME)}
function form_refresh(){var a=getBG(),c=document;if(!c||(!a||!data)||!a.lploggedin)return!1;var d=(new Date).getTime();lpdbg("site","entered form_refresh @ "+d);var b=0;if(my_aid){var k=get_record(my_aid,!0);if(k){var g="";"undefined"!=typeof a.g_pending_pw_change&&(g=a.lpdec_acct(a.g_pending_pw_change[my_aid],k,a.g_shares));var e=getpasswordfromacct(k),f=c.getElementById("password"),h=f.value;if(e&&f&&g&&g!=e&&(e==h||g==h))lpdbg("site","using pending pw instead of g_sites"),e=g,b=d/1E3;e&&f&&(h!==
e&&h&&e)&&(f.value=e,lpdbg("site","REFRESH: reset password from "+(a.g_show_pw_in_logs?h:"REDACTED")+" to "+(a.g_show_pw_in_logs?e:"REDACTED")),d=issharedfolder(a.g_shares,data.group),data.password=a.lpmenc(e,!0,!1==d?a.g_local_key:d.sharekey),0<b?pw_age_update(b):pw_age_update(k.last_pwchange_gmt),update_password_meter("",c.getElementById("password").value),update_SaveButton())}}return!1}
function show_cpw_button(a){var c=getBG(),d=document;if(!d||!c||!a)return!1;var b=!1;!g_cpwbot&&("undefined"!=typeof c.g_cpwbot&&c.g_cpwbot)&&(g_cpwbot=c.g_cpwbot);c=issharedfolder(c.g_shares,a.group);a&&(c?(checkreadonly(c,!0)?(b=!1,lpdbg("site","in shared folder, writable")):(b=!0,lpdbg("site","in shared folder, readonly")),"1"===c.associative&&lpdbg("site","entry is in linked account")):a.individualshare?null!=a.sharedfromaid&&""!=a.sharedfromaid&&"0"!=a.sharedfromaid&&"null"!=a.sharedfromaid?
(lpdbg("site","individual share, readonly"),b=!0):(lpdbg("site","individual share, writable"),b=!1):b=!1);if(g_cpwbot&&a&&"1"==a.pwch&&!b){if(a=d.getElementById("cpwbtnmini"))a.addEventListener("click",function(){document.getElementById("cpwbtnmini").classList.contains("btn_disabled")||show_cpw_dialog("new")}),a.style.fontSize="12px",a.style.display="inline-block";if(d=d.getElementById("pwspacer"))d.style.display="inline-block",d.style.width="50px"}else{if(a=d.getElementById("cpwbtnmini"))a.style.display=
"none";if(d=d.getElementById("pwspacer"))d.style.display="none"}}
function pw_age_update(a){var c=getBG(),d=document;if(!d||!c||!data)return!1;a=parseInt(a);var b=(new Date).getTime(),c=180,c=0,b=null===b?0:parseInt(b/1E3)-60*c,c="Never";if(!a||"number"!=typeof a||!b||isNaN(a)||isNaN(b)||b<a){c="";if(a=d.getElementById("pwagelabel"))a.style.display="none";pass}else d.getElementById("pwagelabel"),a=b-a,60>a?c=a.toString()+" "+(1==a?gs("second"):gs("seconds")):3600>a?(a=parseInt(a/60),c=a.toString()+" "+(1==a?gs("minute"):gs("minutes"))):86400>a?(a=parseInt(a/3600),
c=a.toString()+" "+(1==a?gs("hour"):gs("hours"))):604800>a?(a=parseInt(a/86400),c=a.toString()+" "+(1==a?gs("day"):gs("days"))):2592E3>a?(a=parseInt(a/604800),c=a.toString()+" "+(1==a?gs("week"):gs("weeks"))):31536E3>a?(a=parseInt(a/2592E3),c=a.toString()+" "+(1==a?gs("month"):gs("months"))):(a=parseInt(a/31536E3),c=a.toString()+" "+(1==a?gs("year"):gs("years")));a=d.getElementById("pwagediv");a.style.fontStyle="italic";a&&(set_innertext(a,c),d.getElementById("pwagelabel").style.display="inline")}
function hide_cpw_dialog(){var a=getBG(),c=document;if(!c||!a||!data)return!1;c.getElementById("pwcontainer");var d=c.getElementById("cpwdialog");d&&(d.style.display="none");if(c=c.getElementById("modalbg"))c.style.display="none";"undefined"!=typeof a.cpwbot_halt&&(c=get_current_state(),"FAIL"!=c&&("CAPTCHA"!=c&&"DONE"!=c&&"OK"!=c&&"TIMEOUT"!=c&&0!=c&&null!==c)&&a.cpwbot_halt())}var event_flags=0,EV_CX=1,EV_OK=2;
function show_cpw_dialog(a,c,d,b,k){var g=getBG(),e=document;if(!e||!g||!data)return!1;e.getElementById("notesrow1");e.getElementById("pwcontainer");g=e.getElementById("modalbg");g.style.width=e.body.clientWidth;g.style.height=e.body.clientHeight;g.style.display="block";var g=e.getElementById("dlghdg"),f=e.getElementById("dlghtml");f.style.fontSize="12px";var h=e.getElementById("bcnd"),j=e.getElementById("bokd"),n=e.getElementById("bdis");h&&0==(event_flags&EV_CX)&&(h.addEventListener("click",function(){hide_cpw_dialog()}),
e.getElementById("dlgclose").addEventListener("click",function(){hide_cpw_dialog()}),n.addEventListener("click",function(){hide_cpw_dialog()}),event_flags|=EV_CX);j&&0==(event_flags&EV_OK)&&(j.addEventListener("click",function(a){docpwbtn(a);return!1}),event_flags|=EV_OK);set_innertext(h,gs("No, Thanks"));set_innertext(j,gs("Change Password Now"));set_innertext(n,gs("Dismiss"));set_innertext(g,sprintf(gs("%s Password One-Click Change"),"LastPass"));switch(a){case "new":f.innerHTML="<p>"+sprintf(gs("%s will now attempt to change your password to a strong, generated password that will be saved in your vault and known only to you."),
"LastPass")+"</p><br/><p>"+sprintf(gs("In order to complete the process, %s will have to log in to %s and navigate through a number of windows quickly. It is normal to see windows flashing and changing quickly, and may take several moments. We'll let you know when you're all set!"),"LastPass","<b>"+of(data.name)+"</b>")+"</p>";h.style.display="block";j.style.display="block";n.style.display="none";break;case "progress":f.innerHTML="<b>"+gs("Overall Progress:")+"</b><br /><div class='progress_container'><div class='progress_bar' id='progress_bar'></div></div><div id='stepbystep'></div><div id='advanced'></div>";
e.getElementById("progress_bar").style.width="10%";h.style.display="none";j.style.display="none";n.style.display="none";break;case "update":e.getElementById("progress_bar").style.width=c+"%";d&&(a=e.createElement("p"),"DOCAPTCHA"==get_current_state()&&(a.className="boldred"),d=e.createTextNode(d),a.appendChild(d),e.getElementById("stepbystep").appendChild(a));b&&(a=e.createElement("i"),d=e.createTextNode(gs("Complete!")),a.appendChild(d),(b=e.getElementById("stepbystep").lastChild)&&b.appendChild(a));
k&&(a=e.createElement("p"),d=e.createTextNode(k),a.appendChild(d),e.getElementById("advanced").appendChild(a));break;case "dismiss":f.innerHTML="<br><br><p>"+sprintf(gs("Congratulations! Your password for %s was updated, and is now saved in your LastPass vault. Your change will sync on every device."),"<b>"+of(data.name)+"</b>")+"</p>";h.style.display="none";j.style.display="none";n.style.display="block";set_innertext(n,gs("OK"));break;case "fail":f.innerHTML="<br><br><p>"+sprintf(gs("We're sorry. We were not able to change your password automatically for %s. Your password was not changed."),
"<b>"+of(data.name)+"</b>")+"</p>";h.style.display="none";j.style.display="none";n.style.display="block";break;case "captcha":f.innerHTML="<br><br><p>"+gs("Unable to proceed, the website does not allow automated password change.")+"</p>";h.style.display="none";j.style.display="none";n.style.display="block";break;case "timeout":f.innerHTML="<br><br><p>"+gs("Timed out waiting for the page to load.  Retry?");NaN;h.style.display="none";j.style.display="none";n.style.display="block";break;case "fail_pw_saved":f.innerHTML=
"<br><br><p>"+sprintf(gs("We're sorry. We were not able to change your password automatically for %s. Your password was not changed."),"<b>"+of(data.name)+"</b>")+gs("The random password that was generated has been saved to your vault.")+"</p>",h.style.display="none",j.style.display="none",n.style.display="block"}k=e.getElementById("cpwdialog");k.style.display="block";k.style.height="250px";k.style.width="470px";k.style.left=(parseInt(e.body.clientWidth)-470)/2+"px";k.style.top=(parseInt(e.body.clientHeight)-
470)/2+"px";g_ischrome||(g_cpwbot_pwchangestate="init_state_dingbats")}function notehist(){var a=getBG();a.unlock_plug2web();a.openbaseurl("?ac=1&notehistory="+a.en(get_record_id(data)));setTimeout(function(){window_close("site.html")},0)}var g_cpwbot_pwchangestate=null;function cpw_progress_update(a){a&&a!=g_lastmsg&&(g_lastmsg=a,g_cpw_progress_ctr+=20,90<g_cpw_progress_ctr&&(g_cpw_progress_ctr=95),show_cpw_dialog("update",g_cpw_progress_ctr,a,!1,""))}
function get_current_state(a){if(g_ischrome)return getBG().cpwbot_getpwchangestate();var c=g_cpwbot_pwchangestate;a&&getBG().cpwbot_getpwchangestate();return c};
