#!/bin/bash

if ! command -v fish &> /dev/null; then
  echo "fish is not installed"
  echo "Please install fish and then re-run yadm bootstrap"
  exit 1
fi

if [[ $(basename "${SHELL}") != "fish" ]]; then
  echo "Setting fish as default shell"
  chsh -s $(command -v fish)
fi


echo "Installing fisher"
#fish -ic 'curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher'

echo "done"
