"use strict";this.default_datachannel=this.default_datachannel||{};(function(_){var window=this;
try{
_.aa=_.aa||{};_.k=this;_.ba="closure_uid_"+(1E9*Math.random()>>>0);_.m=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
try{
var ca,ea;ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};ea=function(a,b,c){return a.call.apply(a.bind,arguments)};
_.fa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.n=function(a,b,c){_.n=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:ca;return _.n.apply(null,arguments)};_.ga=function(a){return"function"==_.fa(a)};_.p=function(a){return"string"==typeof a};
_.ha=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};_.r=Array.prototype;_.ia=_.r.indexOf?function(a,b,c){return _.r.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.p(a))return _.p(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.ja=_.r.lastIndexOf?function(a,b,c){return _.r.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(_.p(a))return _.p(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.s=_.r.forEach?function(a,b,c){_.r.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.p(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.ka=_.r.filter?function(a,b,c){return _.r.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=_.p(a)?a.split(""):a,l=0;l<d;l++)if(l in g){var q=g[l];b.call(c,q,l,a)&&(e[f++]=q)}return e};_.ma=_.r.map?function(a,b,c){return _.r.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.p(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
_.na=_.r.reduce?function(a,b,c,d){d&&(b=(0,_.n)(b,d));return _.r.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,_.s)(a,function(c,g){e=b.call(d,e,c,g,a)});return e};_.pa=_.r.some?function(a,b,c){return _.r.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.p(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};
_.qa="StopIteration"in _.k?_.k.StopIteration:Error("d");t:{var ra=_.k.navigator;if(ra){var sa=ra.userAgent;if(sa){_.t=sa;break t}}_.t=""};var wa,ya,Aa;_.ta=-1!=_.t.indexOf("Opera")||-1!=_.t.indexOf("OPR");_.u=-1!=_.t.indexOf("Trident")||-1!=_.t.indexOf("MSIE");_.ua=-1!=_.t.indexOf("Gecko")&&-1==_.t.toLowerCase().indexOf("webkit")&&!(-1!=_.t.indexOf("Trident")||-1!=_.t.indexOf("MSIE"));_.va=-1!=_.t.toLowerCase().indexOf("webkit");wa=_.k.navigator||null;_.xa=wa&&wa.platform||"";ya=function(){var a=_.k.document;return a?a.documentMode:void 0};
_.za=function(){var a="",b;if(_.ta&&_.k.opera)return a=_.k.opera.version,_.ga(a)?a():a;_.ua?b=/rv\:([^\);]+)(\)|;)/:_.u?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:_.va&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(_.t))?a[1]:"");return _.u&&(b=ya(),b>(0,window.parseFloat)(a))?String(b):a}();Aa=_.k.document;_.Ba=Aa&&_.u?ya()||("CSS1Compat"==Aa.compatMode?(0,window.parseInt)(_.za,10):5):void 0;
_.k.ace_i18n={chrome_ext_short_name:{message:"Hangouts"},chrome_ext_description:{message:"Hangouts brings conversations to life with photos, emoji, and even group video calls for free."},quasar_chat_toast_info:{message:"Click to go to page..."},quasar_answer_button_text:{message:"Answer"},quasar_decline_button_text:{message:"Decline"},quasar_help:{message:"Help"},quasar_legend_startup_shutdown:{message:"Application"},chrome_ext_run_at_browser_start:{message:"Sign in to Hangouts when Chrome starts"},
chrome_ext_run_after_browser_close:{message:"Allow background mode"},chrome_ext_new_windows_topmost:{message:"Keep Hangouts on top of other windows"},quasar_label_tray_icon:{message:"Show system tray icon"},quasar_legend_notifications:{message:"Notifications"},quasar_label_all_notification:{message:"Disable notifications"},quasar_label_chat_notification:{message:"Disable chat notifications"},quasar_label_toast_timeout_chat:{message:"Allow chat notifications to timeout automatically"},quasar_label_toast_duration_chat:{message:"Timeout length (in seconds):"},
quasar_button_save:{message:"Ok"},quasar_button_apply:{message:"Apply"},quasar_button_cancel:{message:"Cancel"},chrome_ext_menutext_feedback:{message:"Send feedback"},quasar_feedback_server_uri:{message:"https://www.google.com/tools/feedback"},chrome_ext_feedback_subtitle:{message:"Send feedback"},chrome_ext_feedback_comments:{message:"Comments"},quasar_feedback_system_legend:{message:"System Information"},quasar_feedback_platform_label:{message:"Platform:"},quasar_feedback_user_agent_label:{message:"User Agent:"},
quasar_feedback_privacy_legend:{message:"Privacy Statement"},quasar_feedback_privacy_text:{message:"The description, product information, additional information and your email address will be sent to Google. See the Google Feedback Terms of Service. By submitting this content you are granting to Google the right to use it to improve our products and services. See our Privacy Policy."},quasar_feedback_submit_button:{message:"Send Feedback"},quasar_feedback_cancel_button:{message:"Cancel"},quasar_video_title:{message:"Video call from $1...",
placeholders:{1:{content:"$1"}}},quasar_voice_title:{message:"Voice call from $1...",placeholders:{1:{content:"$1"}}},quasar_group_chat_title:{message:"From group chat..."},quasar_chat_title:{message:"$1 says...",placeholders:{1:{content:"$1"}}},quasar_hangout_title:{message:"$1 is hanging out",placeholders:{1:{content:"$1"}}},chrome_ext_oneonone_plus_hangout_details:{message:"is video calling you via Hangouts"},chrome_ext_group_plus_hangout_details:{message:"has invited you to a group Hangout video call"},
quasar_video_details:{message:"is calling you with video chat"},quasar_voice_details:{message:"is calling you"},quasar_tip_connected:{message:"Status: Connected"},chrome_ext_tip_connected_missed_messages:{message:"Status: Connected\nMissed messages"},quasar_tip_connecting:{message:"Status: Connecting"},quasar_tip_reconnecting:{message:"Status: Reconnecting"},quasar_tip_disconnected:{message:"Status: Disconnected"},quasar_tip_not_login:{message:"Status: Not logged in"},quasar_tip_not_load:{message:"Status: Loading error"},
chrome_ext_menutext_unsigned_user:{message:"Not signed in"},quasar_menutext_unknown_user:{message:"Unknown"},quasar_menutext_feedback:{message:"Feedback"},quasar_menutext_settings:{message:"Options"},quasar_menutext_quit:{message:"Exit"},quasar_menutext_signout:{message:"Sign out"},chrome_ext_cannot_connect:{message:"Unable to connect to Google. Please check your internet connection."},quasar_try_now:{message:"Try now"},quasar_sign_in_to_start_talking:{message:"Sign in to start talking with friends"},
quasar_sign_in:{message:"Sign in"},chrome_app_description:{message:"Always stay connected with the new desktop app for Hangouts on ChromeOS and Windows."},chrome_app_connection_error_title:{message:"Connection Error"},chrome_app_connection_error_detail:{message:"Make sure you are connected to the Internet and try again"},chrome_app_connection_error_button:{message:"Try again"},chrome_app_welcome_message:{message:"Enjoy private and group conversations with text, photos, gifs, voice, video and more."},
chrome_app_chrome_signin_message:{message:"Sign in to Chrome to get started."},chrome_app_learn_more_message:{message:"Learn more"},chrome_app_signin_button:{message:"Sign in"},chrome_app_outdated_title:{message:"Update your Hangouts Chrome app"},chrome_app_outdated_detail:{message:"This app is out of date. There's a newer version available."},chrome_app_exit_title:{message:"Are you sure you want to quit Hangouts?"},chrome_app_exit_title_2:{message:"Do you want to quit Hangouts?"},chrome_app_exit_detail:{message:"You will not receive new messages or calls on this device"},
chrome_app_exit_detail_2:{message:"You can also choose to minimize it and continue to receive messages and calls."},chrome_app_exit_no:{message:"No"},chrome_app_exit_quit:{message:"Quit"},chrome_app_exit_minimize:{message:"Minimize"},chrome_app_osx_warning_message:{message:"Hangouts Chrome app is not fully supported on Mac OSX."},chrome_app_osx_warning_ack:{message:"OK, GOT IT"}};

}catch(e){_._DumpException(e)}
try{
var Ca,Da,Ea,Ha,Ia;Ca=function(a,b){return a<b?-1:a>b?1:0};Da={};Ea=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};_.Fa=function(){};_.Fa.prototype.next=function(){throw _.qa;};_.Fa.prototype.ha=function(){return this};_.Ga=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};Ha=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};
Ia=function(a,b){for(var c=0,d=(0,_.ha)(String(a)).split("."),e=(0,_.ha)(String(b)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var l=d[g]||"",q=e[g]||"",B=RegExp("(\\d*)(\\D*)","g"),K=RegExp("(\\d*)(\\D*)","g");do{var da=B.exec(l)||["","",""],P=K.exec(q)||["","",""];if(0==da[0].length&&0==P[0].length)break;c=Ca(0==da[1].length?0:(0,window.parseInt)(da[1],10),0==P[1].length?0:(0,window.parseInt)(P[1],10))||Ca(0==da[2].length,0==P[2].length)||Ca(da[2],P[2])}while(0==c)}return c};
_.Ja=function(a){var b=_.fa(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.v=function(a){return void 0!==a};_.Ka=function(a){return Da[a]||(Da[a]=0<=Ia(_.za,a))};_.La=function(a){if("function"==typeof a.B)return a.B();if(_.p(a))return a.split("");if(_.Ja(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ha(a)};
_.w=function(a,b){this.b={};this.a=[];this.j=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("f");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){"undefined"!=typeof _.w&&a instanceof _.w?(c=a.M(),d=a.B()):(c=_.Ga(a),d=Ha(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.w.prototype.V=function(){return this.c};_.w.prototype.B=function(){Ma(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.w.prototype.M=function(){Ma(this);return this.a.concat()};
_.Na=function(a,b){return Ea(a.b,b)};_.w.prototype.P=function(){return 0==this.c};_.w.prototype.clear=function(){this.b={};this.j=this.c=this.a.length=0};_.w.prototype.remove=function(a){return Ea(this.b,a)?(delete this.b[a],this.c--,this.j++,this.a.length>2*this.c&&Ma(this),!0):!1};
var Ma=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Ea(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],Ea(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.h=_.w.prototype;_.h.get=function(a,b){return Ea(this.b,a)?this.b[a]:b};_.h.set=function(a,b){Ea(this.b,a)||(this.c++,this.a.push(a),this.j++);this.b[a]=b};_.h.forEach=function(a,b){for(var c=this.M(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};
_.h.clone=function(){return new _.w(this)};_.h.ha=function(a){Ma(this);var b=0,c=this.a,d=this.b,e=this.j,f=this,g=new _.Fa;g.next=function(){for(;;){if(e!=f.j)throw Error("g");if(b>=c.length)throw _.qa;var g=c[b++];return a?g:d[g]}};return g};_.x=function(a){return"array"==_.fa(a)};_.Oa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};
_.y=function(a,b){function c(){}c.prototype=b.prototype;a.t=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ad=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};
_.Pa=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(_.Ja(a)||_.p(a))(0,_.s)(a,b,c);else{var d;if("function"==typeof a.M)d=a.M();else if("function"!=typeof a.B)if(_.Ja(a)||_.p(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=_.Ga(a);else d=void 0;for(var e=_.La(a),f=e.length,g=0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};_.Qa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};_.Ra=function(a,b){var c=(0,_.ia)(a,b),d;(d=0<=c)&&_.r.splice.call(a,c,1);return d};
_.Sa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.Sa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.y(_.Sa,Error);_.Sa.prototype.name="CustomError";_.Ta=function(a,b){var c=a.split("."),d=_.k;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.v(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};
_.Ua=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.Va=function(a){return"number"==typeof a};_.Wa=function(){};_.Xa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
var Ya;_.z=function(){};_.A=function(a,b,c,d){a.a={};b||(b=c?[c]:[]);a.p=c?String(c):void 0;a.b=0===c?-1:0;a.G=b;t:{if(a.G.length&&(b=a.G.length-1,(c=a.G[b])&&"object"==typeof c&&"number"!=typeof c.length)){a.j=b-a.b;a.c=c;break t}a.j=Number.MAX_VALUE}if(d)for(b=0;b<d.length;b++)c=d[b],c<a.j?(c+=a.b,a.G[c]=a.G[c]||[]):a.c[c]=a.c[c]||[]};_.C=function(a,b){return b<a.j?a.G[b+a.b]:a.c[b]};_.z.prototype.toString=function(){return this.G.toString()};_.D=function(a,b){Ya[a]=b;b.messageId=a};Ya={};
_.E=function(){this.D=this.D;this.j=this.j};_.E.prototype.D=!1;_.E.prototype.yb=function(){return this.D};_.E.prototype.C=function(){this.D||(this.D=!0,this.n())};_.G=function(a,b){_.Za(a,_.Ua(_.F,b))};_.Za=function(a,b){a.j||(a.j=[]);a.j.push(_.v(void 0)?(0,_.n)(b,void 0):b)};_.E.prototype.n=function(){if(this.j)for(;this.j.length;)this.j.shift()()};_.F=function(a){a&&"function"==typeof a.C&&a.C()};
_.$a=!_.u||_.u&&9<=_.Ba;!_.ua&&!_.u||_.u&&_.u&&9<=_.Ba||_.ua&&_.Ka("1.9.1");_.u&&_.Ka("9");var ab=function(a){ab[" "](a);return a};ab[" "]=_.Wa;_.cb=function(a,b){try{return ab(a[b]),!0}catch(c){}return!1};var db,eb;db=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;_.gb=function(a){if(eb){eb=!1;var b=_.k.location;if(b){var c=b.href;if(c&&(c=_.fb(c))&&c!=b.hostname)throw eb=!0,Error();}}return a.match(db)};eb=_.va;_.fb=function(a){return(a=_.gb(a)[3]||null)?(0,window.decodeURI)(a):a};
var hb=!_.u||_.u&&9<=_.Ba,ib=_.u&&!_.Ka("9");!_.va||_.Ka("528");_.ua&&_.Ka("1.9b")||_.u&&_.Ka("8")||_.ta&&_.Ka("9.5")||_.va&&_.Ka("528");_.ua&&!_.Ka("8")||_.u&&_.Ka("9");_.H=function(a,b){this.type=a;this.a=this.target=b;this.pc=!0};_.H.prototype.C=function(){};_.H.prototype.b=function(){this.pc=!1};var jb=function(a,b){_.H.call(this,a?a.type:"");this.a=this.target=null;this.clientY=this.clientX=0;this.c=this.state=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;c&&_.ua&&_.cb(c,"nodeName");this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.state=a.state;this.c=a;a.defaultPrevented&&this.b()}};_.y(jb,_.H); jb.prototype.b=function(){jb.t.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,ib)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var kb,mb;kb="closure_listenable_"+(1E6*Math.random()|0);_.lb=function(a){return!(!a||!a[kb])};mb=0;var nb=function(a,b,c,d,e){this.qa=a;this.proxy=null;this.src=b;this.type=c;this.Ua=!!d;this.$a=e;this.key=++mb;this.removed=this.Ta=!1},ob=function(a){a.removed=!0;a.qa=null;a.proxy=null;a.src=null;a.$a=null};var pb=function(a){this.src=a;this.a={};this.b=0};pb.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=qb(a,b,d,e);-1<g?(b=a[g],c||(b.Ta=!1)):(b=new nb(b,this.src,f,!!d,e),b.Ta=c,a.push(b));return b};pb.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=qb(e,b,c,d);return-1<b?(ob(e[b]),_.r.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var rb=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=_.Ra(a.a[c],b);d&&(ob(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d};pb.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,ob(d[e]);delete this.a[c];this.b--}return b}; var sb=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=qb(a,c,d,e));return-1<b?a[b]:null},qb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.qa==b&&f.Ua==!!c&&f.$a==d)return e}return-1};
var tb,ub,vb,Ab,Bb,Gb,Fb,Cb,zb,Hb;tb="closure_lm_"+(1E6*Math.random()|0);ub={};vb=0;_.wb=function(a,b,c,d,e){if(_.x(b)){for(var f=0;f<b.length;f++)_.wb(a,b[f],c,d,e);return null}c=_.xb(c);return _.lb(a)?a.listen(b,c,d,e):_.yb(a,b,c,!1,d,e)};_.yb=function(a,b,c,d,e,f){if(!b)throw Error("l");var g=!!e,l=zb(a);l||(a[tb]=l=new pb(a));c=l.add(b,c,d,e,f);if(c.proxy)return c;d=Ab();c.proxy=d;d.src=a;d.qa=c;a.addEventListener?a.addEventListener(b.toString(),d,g):a.attachEvent(Bb(b.toString()),d);vb++;return c};
Ab=function(){var a=Cb,b=hb?function(c){return a.call(b.src,b.qa,c)}:function(c){c=a.call(b.src,b.qa,c);if(!c)return c};return b};_.Db=function(a,b,c,d,e){if(_.x(b))for(var f=0;f<b.length;f++)_.Db(a,b[f],c,d,e);else c=_.xb(c),_.lb(a)?a.Fb(b,c,d,e):a&&(a=zb(a))&&(b=sb(a,b,c,!!d,e))&&_.Eb(b)};
_.Eb=function(a){if(_.Va(a)||!a||a.removed)return!1;var b=a.src;if(_.lb(b))return rb(b.U,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.Ua):b.detachEvent&&b.detachEvent(Bb(c),d);vb--;(c=zb(b))?(rb(c,a),0==c.b&&(c.src=null,b[tb]=null)):ob(a);return!0};Bb=function(a){return a in ub?ub[a]:ub[a]="on"+a};Gb=function(a,b,c,d){var e=1;if(a=zb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Ua==c&&!f.removed&&(e&=!1!==Fb(f,d))}return Boolean(e)};
Fb=function(a,b){var c=a.qa,d=a.$a||a.src;a.Ta&&_.Eb(a);return c.call(d,b)};
Cb=function(a,b){if(a.removed)return!0;if(!hb){var c;if(!(c=b))t:{c=["window","event"];for(var d=_.k,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break t}c=d}e=c;c=new jb(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){t:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break t}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,l=e.length-1;0<=l;l--)c.a=e[l],d&=Gb(e[l],f,!0,c);for(l=0;l<e.length;l++)c.a=e[l],d&=Gb(e[l],f,!1,c)}return d}return Fb(a, new jb(b,this))};zb=function(a){a=a[tb];return a instanceof pb?a:null};Hb="__closure_events_fn_"+(1E9*Math.random()>>>0);_.xb=function(a){if(_.ga(a))return a;a[Hb]||(a[Hb]=function(b){return a.handleEvent(b)});return a[Hb]};
_.Ib=function(a){_.A(this,a,"h_cc",[])};_.y(_.Ib,_.z);_.D("h_cc",_.Ib);_.Ib.prototype.Z=function(){return _.C(this,19)};_.I=function(a){_.E.call(this);this.I=a;this.g={}};_.y(_.I,_.E);var Jb=[];_.I.prototype.listen=function(a,b,c,d){return _.Lb(this,a,b,c,d)};_.Lb=function(a,b,c,d,e,f){_.x(c)||(c&&(Jb[0]=c.toString()),c=Jb);for(var g=0;g<c.length;g++){var l=_.wb(b,c[g],d||a.handleEvent,e||!1,f||a.I||a);if(!l)break;a.g[l.key]=l}return a};
_.I.prototype.Fb=function(a,b,c,d,e){if(_.x(b))for(var f=0;f<b.length;f++)this.Fb(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.I||this,c=_.xb(c),d=!!d,b=_.lb(a)?sb(a.U,String(b),c,d,e):a?(a=zb(a))?sb(a,b,c,d,e):null:null,b&&(_.Eb(b),delete this.g[b.key]);return this};_.I.prototype.removeAll=function(){_.Qa(this.g,_.Eb);this.g={}};_.I.prototype.n=function(){_.I.t.n.call(this);this.removeAll()};_.I.prototype.handleEvent=function(){throw Error("m");};
var Mb,Nb,Ob;Mb=function(a){_.k.setTimeout(function(){throw a;},0)};_.Pb=function(a,b){var c=a;b&&(c=(0,_.n)(a,b));!_.ga(_.k.setImmediate)||_.k.Window&&_.k.Window.prototype.setImmediate==_.k.setImmediate?(Nb||(Nb=Ob()),Nb(c)):_.k.setImmediate(c)};
Ob=function(){var a=_.k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(a=function(){var a=window.document.createElement("iframe");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.n)(function(a){if(("*"==d||a.origin==d)&&
a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&-1==_.t.indexOf("Trident")&&-1==_.t.indexOf("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.v(c.next)){c=c.next;var a=c.Rb;c.Rb=null;a()}};return function(a){d.next={Rb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("script")? function(a){var b=window.document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.k.setTimeout(a,0)}};
var Vb=function(a,b){Qb||Rb();Sb||(Qb(),Sb=!0);Tb.push(new Ub(a,b))},Qb,Rb=function(){if(_.k.Promise&&_.k.Promise.resolve){var a=_.k.Promise.resolve();Qb=function(){a.then(Wb)}}else Qb=function(){_.Pb(Wb)}},Sb=!1,Tb=[],Wb=function(){for(;Tb.length;){var a=Tb;Tb=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.a.call(c.b)}catch(d){Mb(d)}}}Sb=!1},Ub=function(a,b){this.a=a;this.b=b};
_.J=function(){_.E.call(this);this.U=new pb(this);this.L=this;this.u=null};_.y(_.J,_.E);_.J.prototype[kb]=!0;_.h=_.J.prototype;_.h.addEventListener=function(a,b,c,d){_.wb(this,a,b,c,d)};_.h.removeEventListener=function(a,b,c,d){_.Db(this,a,b,c,d)};_.h.n=function(){_.J.t.n.call(this);this.U&&this.U.removeAll(void 0);this.u=null};_.h.listen=function(a,b,c,d){return this.U.add(String(a),b,!1,c,d)};_.h.Fb=function(a,b,c,d){return this.U.remove(String(a),b,c,d)}; _.h.da=function(a,b,c){a=this.U.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.Ua==b){var g=f.qa,l=f.$a||f.src;f.Ta&&rb(this.U,f);d=!1!==g.call(l,c)&&d}}return d&&0!=c.pc};
var Xb=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},Yb=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var $b;$b=function(a,b){this.b=0;this.f=void 0;this.a=this.c=null;this.j=this.e=!1;try{var c=this;a.call(b,function(a){Zb(c,2,a)},function(a){Zb(c,3,a)})}catch(d){Zb(this,3,d)}};_.bc=function(){var a,b=new $b(function(b){a=b});return new ac(b,a)};$b.prototype.then=function(a,b,c){return cc(this,_.ga(a)?a:null,_.ga(b)?b:null,c)};Xb($b);
var fc=function(a){0==a.b&&Vb(function(){var a=new dc(void 0);ec(this,a)},a)},ec=function(a,b){if(0==a.b)if(a.c){var c=a.c;if(c.a){for(var d=0,e=-1,f=0,g;g=c.a[f];f++)if(g=g.Ea)if(d++,g==a&&(e=f),0<=e&&1<d)break;0<=e&&(0==c.b&&1==d?ec(c,b):(d=c.a.splice(e,1)[0],gc(c,d,3,b)))}}else Zb(a,3,b)},ic=function(a,b){a.a&&a.a.length||2!=a.b&&3!=a.b||hc(a);a.a||(a.a=[]);a.a.push(b)},cc=function(a,b,c,d){var e={Ea:null,jc:null,lc:null};e.Ea=new $b(function(a,g){e.jc=b?function(c){try{var e=b.call(d,c);a(e)}catch(B){g(B)}}:
a;e.lc=c?function(b){try{var e=c.call(d,b);!_.v(e)&&b instanceof dc?g(b):a(e)}catch(B){g(B)}}:g});e.Ea.c=a;ic(a,e);return e.Ea};$b.prototype.g=function(a){this.b=0;Zb(this,2,a)};$b.prototype.h=function(a){this.b=0;Zb(this,3,a)};
var Zb=function(a,b,c){if(0==a.b){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(Yb(c)){a.b=1;c.then(a.g,a.h,a);return}if(_.Oa(c))try{var d=c.then;if(_.ga(d)){jc(a,c,d);return}}catch(e){b=3,c=e}}a.f=c;a.b=b;hc(a);3!=b||c instanceof dc||kc(a,c)}},jc=function(a,b,c){a.b=1;var d=!1,e=function(b){d||(d=!0,a.g(b))},f=function(b){d||(d=!0,a.h(b))};try{c.call(b,e,f)}catch(g){f(g)}},hc=function(a){a.e||(a.e=!0,Vb(a.k,a))};
$b.prototype.k=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;b++)gc(this,a[b],this.b,this.f)}this.e=!1};var gc=function(a,b,c,d){if(2==c)b.jc(d);else{if(b.Ea)for(;a&&a.j;a=a.c)a.j=!1;b.lc(d)}},kc=function(a,b){a.j=!0;Vb(function(){a.j&&lc.call(null,b)})},lc=Mb,dc=function(a){_.Sa.call(this,a)};_.y(dc,_.Sa);dc.prototype.name="cancel";var ac=function(a,b){this.b=a;this.a=b};
var mc,nc,oc,pc,qc,rc,sc,vc,wc,xc,yc,zc,Ac;sc=rc=qc=pc=oc=nc=mc=!1;var tc=_.t;tc&&(-1!=tc.indexOf("Firefox")?mc=!0:-1!=tc.indexOf("Camino")?nc=!0:-1!=tc.indexOf("iPad")?pc=!0:-1!=tc.indexOf("iPhone")||-1!=tc.indexOf("iPod")?oc=!0:-1!=tc.indexOf("Chrome")?rc=!0:-1!=tc.indexOf("Android")?qc=!0:-1!=tc.indexOf("Safari")&&(sc=!0));_.uc=mc;vc=nc;wc=oc;xc=pc;yc=qc;zc=rc;Ac=sc;
_.L=function(a){this.a=a};_.L.prototype.toString=function(){return this.a};_.Bc=new _.L("fJuxOc");_.Cc=new _.L("ZtVrH");_.Dc=new _.L("zZa4xc");_.Ec=new _.L("pVbxBc");_.Fc=new _.L("byfTOb");_.Gc=new _.L("LEikZe");_.Hc=new _.L("rJmJrc");_.Ic=new _.L("a");_.Jc=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")};_.Kc=function(){return 0<=window.navigator.userAgent.indexOf("CrOS")};_.Lc=function(a,b){this.j=a||"e";this.c=null!=a&&"p"==a?"e":"p";this.b=this.e=null;this.h=b||"u";this.a=this.g=null;this.f=[]};_.Lc.prototype.message=function(){var a={};a.i=this.a;a.m=this.f;a.r=this.h;a.o=this.g;a.s=this.b;a.st=this.c;a.d=this.e;a.dt=this.j;return a};_.Ta("ace.base.Message.prototype.message",_.Lc.prototype.message);
_.Mc=function(a,b){for(var c in b)switch(c){case "r":a.h=b[c];break;case "i":a.a=b[c];break;case "m":a.f=b[c];break;case "o":a.g=b[c];break;case "s":a.b=b[c];break;case "d":a.e=b[c];break;case "st":a.c=b[c];break;case "dt":a.j=b[c]}return a};_.Nc=function(a,b,c){null!=b&&(a.b=b,null!=c&&(a.c=c))};_.Oc=function(a,b){null!=b&&(a.a=b)};_.Pc=function(a,b){"object"==typeof b?a.f=b:a.f=[b]};_.Lc.prototype.source=function(){return this.b};_.Lc.prototype.target=function(){return this.e}; _.Lc.prototype.content=function(){return this.f};
_.Qc=function(a,b,c,d,e){_.E.call(this);this.b=a;this.Qa=b;this.a=typeof b;this.Ab=c?c:!1;this.ba=!0;this.wb=d?d:!1;this.pb=e?e:!1};_.y(_.Qc,_.E);_.h=_.Qc.prototype;_.h.n=function(){_.Qc.t.n.call(this);this.b="";this.Qa=null;this.a=""};_.h.id=function(){return this.b};_.h.type=function(){return this.a};_.h.F=function(){return this.Qa};_.h.setEnabled=function(a){this.ba=a};
var Rc=function(a){return(a=a.exec(_.t))?a[1]:""},Sc=function(){if(_.uc)return Rc(/Firefox\/([0-9.]+)/);if(_.u||_.ta)return _.za;if(zc)return Rc(/Chrome\/([0-9.]+)/);if(Ac)return Rc(/Version\/([0-9.]+)/);if(wc||xc){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.t))return a[1]+"."+a[2]}else{if(yc)return(a=Rc(/Android\s+([0-9.]+)/))?a:Rc(/Version\/([0-9.]+)/);if(vc)return Rc(/Camino\/([0-9.]+)/)}return""}();
_.Uc=function(a){_.E.call(this);this.a=new _.w;this.b=["https://talkgadget.google.com/talkgadget/notifier-js","","https://test.talkgadget.google.com/talkgadget/notifier-js?jsmode=debug_unobfuscated"];a&&_.Tc(this,a)};_.y(_.Uc,_.E);_.Vc=0<=Ia(Sc,"23.0.1262.0")&&!_.Kc();_.Uc.prototype.n=function(){_.Uc.t.n.call(this);for(var a=this.a.M(),b=0;b<a.length;++b)_.F(this.a.get(a[b]));delete this.a};_.Uc.prototype.getItem=function(a){return _.Na(this.a,a)?this.a.get(a):null};
_.Uc.prototype.setItem=function(a){this.a.set(a.id(),a)};_.Tc=function(a,b){for(var c in b){var d=b[c],e=null;_.Na(a.a,c)?(e=a.a.get(c),e.Qa=d.value,d.changed&&(e.pb=d.changed)):(e=new _.Qc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
_.Yc=function(){this.c=new _.w;this.a=null;this.b=!1;this.a=new Wc;this.b=!0;_.Xc(this)};_.Yc.ua=function(){return _.Yc.a?_.Yc.a:_.Yc.a=new _.Yc};_.Xc=function(a,b){var c=b||_.Wa;a.b?c():window.chrome.storage.local.get((0,_.n)(function(a){if(!this.b){for(var b in a)this.c.set(b,a[b]);this.b=!0}c()},a))};_.Yc.prototype.get=function(a){return this.a.get(a)};_.Yc.prototype.set=function(a,b){var c=_.bc();this.a.set(a,b);c.a(void 0);return c.b};_.Yc.prototype.remove=function(a){this.a.remove(a)};
_.Yc.prototype.clear=function(){this.a.clear()};var Wc=function(){this.a=window.localStorage};Wc.prototype.clear=function(){this.a.clear()};Wc.prototype.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=Ya[a[0]];if(!b)throw Error("i`"+a[0]);a=new b(a)}}else a=null;return a};Wc.prototype.set=function(a,b){var c=null;b instanceof _.z&&(b=b.G,c="jspb");var d={};d.data=b;d.timestamp=(0,_.m)();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}}; Wc.prototype.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
_.Zc=function(a,b){this.b=a;this.a=b;this.constructor.Pb||(this.constructor.Pb={});this.constructor.Pb[this.toString()]=this};_.Zc.prototype.toString=function(){this.c||(this.c=this.b.a+":"+this.a);return this.c};_.M=function(a,b){_.Zc.call(this,a,b)};_.y(_.M,_.Zc);_.$c=function(a){this.a=a};_.ad=new _.$c("lib");/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.bd=function(a,b){this.j=[];this.u=b||null;this.b=this.a=!1;this.c=void 0;this.l=this.p=this.f=!1;this.e=0;this.h=null;this.q=0};_.bd.prototype.k=function(a,b){this.f=!1;_.cd(this,a,b)};_.cd=function(a,b,c){a.a=!0;a.c=c;a.b=!b;dd(a)};_.fd=function(a){if(a.a){if(!a.l)throw new ed;a.l=!1}};_.bd.prototype.g=function(a){_.fd(this);_.cd(this,!0,a)};_.gd=function(a,b,c,d){a.j.push([b,c,d]);a.a&&dd(a)};
_.bd.prototype.then=function(a,b,c){var d,e,f=new $b(function(a,b){d=a;e=b});_.gd(this,d,function(a){"undefined"!=typeof _.hd&&a instanceof _.hd?fc(f):e(a)});return f.then(a,b,c)};Xb(_.bd);
var id=function(a){return(0,_.pa)(a.j,function(a){return _.ga(a[1])})},dd=function(a){if(a.e&&a.a&&id(a)){var b=a.e,c=jd[b];c&&(_.k.clearTimeout(c.Wa),delete jd[b]);a.e=0}a.h&&(a.h.q--,delete a.h);for(var b=a.c,d=c=!1;a.j.length&&!a.f;){var e=a.j.shift(),f=e[0],g=e[1],e=e[2];if(f=a.b?g:f)try{var l=f.call(e||a.u,b);_.v(l)&&(a.b=a.b&&(l==b||l instanceof Error),a.c=b=l);Yb(b)&&(d=!0,a.f=!0)}catch(q){b=q,a.b=!0,id(a)||(c=!0)}}a.c=b;d&&(l=(0,_.n)(a.k,a,!0),d=(0,_.n)(a.k,a,!1),b instanceof _.bd?(_.gd(b,
l,d),b.p=!0):b.then(l,d));c&&(b=new kd(b),jd[b.Wa]=b,a.e=b.Wa)},ed=function(){_.Sa.call(this)};_.y(ed,_.Sa);ed.prototype.message="Deferred has already fired";ed.prototype.name="AlreadyCalledError";var kd=function(a){this.Wa=_.k.setTimeout((0,_.n)(this.b,this),0);this.a=a};kd.prototype.b=function(){delete jd[this.Wa];throw this.a;};var jd={};

}catch(e){_._DumpException(e)}
try{
var md;_.ld=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)};md=function(a,b){for(var c=_.p(a)?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)};_.od=function(a){_.E.call(this);this.c={};this.h={};this.k={};this.e={};this.l={};this.q={};this.p=a?a.ta():new _.J;this.w=!a;this.f=null;a?(this.f=a,this.k=a.k,this.e=a.e,this.h=a.h,this.l=a.l):(0,_.m)();a=nd(this);this!=a&&(a.g?a.g.push(this):a.g=[this])};_.y(_.od,_.E);var nd=function(a){for(;a.f;)a=a.f;return a};_.od.prototype.get=function(a){var b=this.b(a);if(null==b)throw new pd(a);return b};
_.od.prototype.b=function(a){for(var b=this;b;b=b.f){if(b.D)throw Error("q");if(b.c[a])return b.c[a][0];if(b.q[a])break}if(b=this.k[a]){b=b(this);if(null==b)throw Error("r`"+a);this.a(a,b);return b}return null};_.od.prototype.a=function(a,b,c){if(this.D)c||_.F(b);else{this.c[a]=[b,!c];b=qd(this,this,a);for(c=0;c<b.length;c++)b[c].g(null);delete this.h[a]}};_.od.prototype.u=function(){var a=_.rd;if(!this.c[a])throw Error("s`"+a);var b=this.c[a];delete this.c[a];b[1]&&_.F(b[0])};
var qd=function(a,b,c){var d=[],e=a.e[c];e&&(md(e,function(a){var c;t:{for(c=a.Qb;c;){if(c==b){c=!0;break t}c=c.f}c=!1}c&&(d.push(a.Bd),_.Ra(e,a))}),0==e.length&&delete a.e[c]);return d},sd=function(a,b){a.e&&_.Pa(a.e,function(a,d,e){md(a,function(d){d.Qb==b&&_.Ra(a,d)});0==a.length&&delete e[d]})};
_.od.prototype.n=function(){if(nd(this)==this){var a=this.g;if(a)for(;a.length;)a[0].C()}else for(var a=nd(this).g,b=0;b<a.length;b++)if(a[b]==this){a.splice(b,1);break}for(var c in this.c)a=this.c[c],a[1]&&"undefined"!=typeof a[0].C&&a[0].C();this.c=null;this.w&&this.p.C();sd(this,this);this.e=null;_.F(this.v);this.q=this.v=null;_.od.t.n.call(this)};_.od.prototype.ta=function(){return this.p};var pd=function(a){_.Sa.call(this);this.id=a;this.message='Service for "'+a+'" is not registered'}; _.y(pd,_.Sa);var td=new _.$c("fva");new _.M(td,1);

}catch(e){_._DumpException(e)}
try{
var ud,vd,wd,xd,yd,zd,Gd,Hd,Md,Ld,Pd,Qd,Rd,Sd,Td,Ud,Vd,$d,he;ud={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};vd=function(a,b){b.push('"',a.replace(_.Xa,function(a){if(a in ud)return ud[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return ud[a]=e+b.toString(16)}),'"')};
wd=function(a,b,c){switch(typeof b){case "string":vd(b,c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(_.x(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),wd(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],"function"!=typeof f&&(c.push(d),vd(e,c),c.push(":"),
wd(a,f,c),d=","));c.push("}");break;case "function":break;default:throw Error("h`"+typeof b);}};xd=function(){};yd="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");zd=function(a,b,c,d,e){if(_.x(b)){for(var f=0;f<b.length;f++)zd(a,b[f],c,d,e);return null}c=_.xb(c);return _.lb(a)?a.U.add(String(b),c,!0,d,e):_.yb(a,b,c,!0,d,e)};_.N=function(a,b,c){b<a.j?a.G[b+a.b]=c:a.c[b]=c};_.Ad=function(a){var b=[];wd(new xd,a,b);return b.join("")};
_.Bd=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<yd.length;f++)c=yd[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};_.Cd=function(a,b,c){null!=b&&(a.e=b,null!=c&&(a.j=c))};
_.O=function(a,b){var c,d=a.u;if(d)for(c=[];d;d=d.u)c.push(d);var d=a.L,e=b,f=e.type||e;if(_.p(e))e=new _.H(e,d);else if(e instanceof _.H)e.target=e.target||d;else{var g=e,e=new _.H(f,d);_.Bd(e,g)}var g=!0,l;if(c)for(var q=c.length-1;0<=q;q--)l=e.a=c[q],g=l.da(f,!0,e)&&g;l=e.a=d;g=l.da(f,!0,e)&&g;g=l.da(f,!1,e)&&g;if(c)for(q=0;q<c.length;q++)l=e.a=c[q],g=l.da(f,!1,e)&&g};
_.Ed=function(a,b,c,d,e,f){if(_.x(c))for(var g=0;g<c.length;g++)_.Ed(a,b,c[g],d,e,f);else{b=zd(b,c,d||a.handleEvent,e,f||a.I||a);if(!b)return a;a.g[b.key]=b}return a};_.Fd=function(a,b,c){var d=c?c.G:c;a.a[b]=c;_.N(a,b,d)};_.Q=function(a,b,c){if(!a.a[c]){var d=_.C(a,c);d&&(a.a[c]=new b(d))}return a.a[c]};Gd=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};Hd=function(a,b){return a?b?(0,window.decodeURI)(a):(0,window.decodeURIComponent)(a):""};
_.Id=function(a){return _.r.concat.apply(_.r,arguments)};_.Jd=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};_.Kd=function(a,b,c){this.a=a||null;this.b=!!c};
Md=function(a){if(!a.H&&(a.H=new _.w,a.O=0,a.a))for(var b=a.a.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),e=null,f=null;0<=d?(e=b[c].substring(0,d),f=b[c].substring(d+1)):e=b[c];e=(0,window.decodeURIComponent)(e.replace(/\+/g," "));e=Ld(a,e);a.add(e,f?(0,window.decodeURIComponent)(f.replace(/\+/g," ")):"")}};_.h=_.Kd.prototype;_.h.H=null;_.h.O=null;_.h.V=function(){Md(this);return this.O};
_.h.add=function(a,b){Md(this);this.a=null;a=Ld(this,a);var c=this.H.get(a);c||this.H.set(a,c=[]);c.push(b);this.O++;return this};_.h.remove=function(a){Md(this);a=Ld(this,a);return _.Na(this.H,a)?(this.a=null,this.O-=this.H.get(a).length,this.H.remove(a)):!1};_.h.clear=function(){this.H=this.a=null;this.O=0};_.h.P=function(){Md(this);return 0==this.O};var Nd=function(a,b){Md(a);b=Ld(a,b);return _.Na(a.H,b)};
_.Kd.prototype.M=function(){Md(this);for(var a=this.H.B(),b=this.H.M(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};_.Kd.prototype.B=function(a){Md(this);var b=[];if(_.p(a))Nd(this,a)&&(b=_.Id(b,this.H.get(Ld(this,a))));else{a=this.H.B();for(var c=0;c<a.length;c++)b=_.Id(b,a[c])}return b};_.Kd.prototype.set=function(a,b){Md(this);this.a=null;a=Ld(this,a);Nd(this,a)&&(this.O-=this.H.get(a).length);this.H.set(a,[b]);this.O++;return this};
_.Kd.prototype.get=function(a,b){var c=a?this.B(a):[];return 0<c.length?String(c[0]):b};_.Od=function(a,b,c){a.remove(b);0<c.length&&(a.a=null,a.H.set(Ld(a,b),_.Jd(c)),a.O+=c.length)};_.Kd.prototype.toString=function(){if(this.a)return this.a;if(!this.H)return"";for(var a=[],b=this.H.M(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.B(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(g)}return this.a=a.join("&")};
_.Kd.prototype.clone=function(){var a=new _.Kd;a.a=this.a;this.H&&(a.H=this.H.clone(),a.O=this.O);return a};Ld=function(a,b){var c=String(b);a.b&&(c=c.toLowerCase());return c};Pd=function(a,b){b&&!a.b&&(Md(a),a.a=null,a.H.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),_.Od(this,e,a))},a));a.b=b};Qd=/#/g;Rd=/[\#\?@]/g;Sd=/[\#\?]/g;Td=/[\#\?:]/g;Ud=/[#\/\?@]/g;
Vd=function(a,b,c){return _.p(a)?(a=(0,window.encodeURI)(a).replace(b,Gd),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};_.Wd=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.m)()).toString(36)};
_.Xd=function(a,b){var c;"undefined"!=typeof _.Xd&&a instanceof _.Xd?(this.ma=_.v(b)?b:a.ma,_.Yd(this,a.fa),this.sa=a.sa,this.R=a.R,_.Zd(this,a.ea),this.N=a.N,$d(this,a.a.clone()),this.la=a.la):a&&(c=_.gb(String(a)))?(this.ma=!!b,_.Yd(this,c[1]||"",!0),this.sa=Hd(c[2]||""),this.R=Hd(c[3]||"",!0),_.Zd(this,c[4]),this.N=Hd(c[5]||"",!0),$d(this,c[6]||"",!0),this.la=Hd(c[7]||"")):(this.ma=!!b,this.a=new _.Kd(null,0,this.ma))};_.h=_.Xd.prototype;_.h.fa="";_.h.sa="";_.h.R="";_.h.ea=null;_.h.N="";
_.h.la="";_.h.ma=!1;_.h.toString=function(){var a=[],b=this.fa;b&&a.push(Vd(b,Ud,!0),":");if(b=this.R){a.push("//");var c=this.sa;c&&a.push(Vd(c,Ud,!0),"@");a.push((0,window.encodeURIComponent)(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.ea;null!=b&&a.push(":",String(b))}if(b=this.N)this.R&&"/"!=b.charAt(0)&&a.push("/"),a.push(Vd(b,"/"==b.charAt(0)?Sd:Td,!0));(b=this.a.toString())&&a.push("?",b);(b=this.la)&&a.push("#",Vd(b,Qd));return a.join("")};
_.ae=function(a,b){var c=a.clone(),d=!!b.fa;d?_.Yd(c,b.fa):d=!!b.sa;d?c.sa=b.sa:d=!!b.R;d?c.R=b.R:d=null!=b.ea;var e=b.N;if(d)_.Zd(c,b.ea);else if(d=!!b.N){if("/"!=e.charAt(0))if(a.R&&!a.N)e="/"+e;else{var f=c.N.lastIndexOf("/");-1!=f&&(e=c.N.substr(0,f+1)+e)}f=e;if(".."==f||"."==f)e="";else if(-1!=f.indexOf("./")||-1!=f.indexOf("/.")){for(var e=0==f.lastIndexOf("/",0),f=f.split("/"),g=[],l=0;l<f.length;){var q=f[l++];"."==q?e&&l==f.length&&g.push(""):".."==q?((1<g.length||1==g.length&&""!=g[0])&&
g.pop(),e&&l==f.length&&g.push("")):(g.push(q),e=!0)}e=g.join("/")}else e=f}d?c.N=e:d=""!==b.a.toString();d?$d(c,Hd(b.a.toString())):d=!!b.la;d&&(c.la=b.la);return c};_.Xd.prototype.clone=function(){return new _.Xd(this)};_.Yd=function(a,b,c){a.fa=c?Hd(b,!0):b;a.fa&&(a.fa=a.fa.replace(/:$/,""))};_.Zd=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("j`"+b);a.ea=b}else a.ea=null};$d=function(a,b,c){b instanceof _.Kd?(a.a=b,Pd(a.a,a.ma)):(c||(b=Vd(b,Rd)),a.a=new _.Kd(b,0,a.ma))};
_.R=function(a,b,c){a.a.set(b,c)};_.be=function(a,b,c){_.x(c)||(c=[String(c)]);_.Od(a.a,b,c)};_.ce=function(a,b){return a.a.get(b)};_.de=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};_.ee=function(a,b){return 0<=(0,_.ia)(a,b)};
_.fe=function(a,b,c){if(_.ga(a))c&&(a=(0,_.n)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.n)(a.handleEvent,a);else throw Error("n");return 2147483647<b?-1:_.k.setTimeout(a,b||0)};_.ge=function(a){_.k.clearTimeout(a)};he=function(a){var b=arguments.length;if(1==b&&_.x(arguments[0]))return he.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};_.ie=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
_.je=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c],e;if(_.x(d)||(e=_.Ja(d))&&Object.prototype.hasOwnProperty.call(d,"callee"))a.push.apply(a,d);else if(e)for(var f=a.length,g=d.length,l=0;l<g;l++)a[f+l]=d[l];else a.push(d)}};_.ke=function(a,b){var c;t:{c=a.length;for(var d=_.p(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break t}c=-1}return 0>c?null:_.p(a)?a.charAt(c):a[c]};
he("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));he("action","cite","data","formaction","href","manifest","poster","src");he("embed","iframe","link","script","style","template");var oe,me,ne,pe;_.le=function(){};oe=function(a){var b=a.ia,c=function(a){c.t.constructor.call(this,a);var b=this.T.length;this.a=[];for(var d=0;d<b;++d)this.T[d].Cd||(this.a[d]=new this.T[d](a))};_.y(c,b);for(var d=[];a;){if(b=a.ia){b.T&&_.je(d,b.T);var b=b.prototype,e;for(e in b)if(b.hasOwnProperty(e)&&_.ga(b[e])&&b[e]!==a){var f=!!b[e].Mc,g=me(e,b,d,f);(f=ne(e,b,g,f))&&(c.prototype[e]=f)}}a=a.t&&a.t.constructor}c.prototype.T=d;return c};
me=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||(e.push(f),!d));++f);return e};
ne=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.T[c[0]].prototype[a].apply(this,arguments)}:b[a].Oc?e=function(b){var d;t:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var q=this.a[c[e]];if(q=q?q[a].apply(q,d):this.T[c[e]].prototype[a].apply(this,d)){d=q;break t}}d=!1}return d}:b[a].Nc?e=function(b){var d;t:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var q=this.a[c[e]],q=q?q[a].apply(q,
d):this.T[c[e]].prototype[a].apply(this,d);if(null!=q){d=q;break t}}d=void 0}return d}:b[a].hc?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var q=this.a[c[e]];q?q[a].apply(q,d):this.T[c[e]].prototype[a].apply(this,d)}}:e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],q=0;q<c.length;++q){var B=this.a[c[q]];e.push(B?B[a].apply(B,d):this.T[c[q]].prototype[a].apply(this,d))}return e}:d||b[a].Oc||b[a].Nc||b[a].hc?e=null:e=pe;return e};pe=function(){return[]}; _.le.prototype.tb=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};
var qe;_.re=function(a){if(!a.qb){var b;for(b=a.constructor;b&&!b.ia;)b=b.t&&b.t.constructor;b.ia.Ub||(b.ia.Ub=oe(b));b=new b.ia.Ub(a);a.qb=b;a.tb||(a.tb=qe)}};qe=function(a){return this.qb.tb(a)};var se=function(){};se.prototype.a=null;var ue=function(a){var b;(b=a.a)||(b={},te(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var ve,we=function(){};_.y(we,se);var xe=function(a){return(a=te(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},te=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("t");}return a.b};ve=new we;
var ze,Ce,He,Je,Ie,Ee;_.ye=function(a){_.J.call(this);this.A=new _.w;this.k=a||null;this.b=!1;this.h=this.a=null;this.q="";this.e=0;this.c=this.p=this.f=this.l=!1;this.v=0;this.g=null;this.I="";this.w=this.aa=!1};_.y(_.ye,_.J);ze=/^https?$/i;_.Ae=["POST","PUT"];_.Be=[];_.ye.prototype.S=function(){this.C();_.Ra(_.Be,this)};
_.ye.prototype.send=function(a,b,c,d){if(this.a)throw Error("u`"+this.q+"`"+a);b=b?b.toUpperCase():"GET";this.q=a;this.e=0;this.l=!1;this.b=!0;this.a=this.k?xe(this.k):xe(ve);this.h=this.k?ue(this.k):ue(ve);this.a.onreadystatechange=(0,_.n)(this.J,this);try{this.p=!0,this.a.open(b,String(a),!0),this.p=!1}catch(e){Ce(this);return}a=c||"";var f=this.A.clone();d&&_.Pa(d,function(a,b){f.set(b,a)});d=_.ke(f.M(),De);c=_.k.FormData&&a instanceof _.k.FormData;!_.ee(_.Ae,b)||d||c||f.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
f.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.I&&(this.a.responseType=this.I);"withCredentials"in this.a&&(this.a.withCredentials=this.aa);try{Ee(this),0<this.v&&((this.w=Fe(this.a))?(this.a.timeout=this.v,this.a.ontimeout=(0,_.n)(this.K,this)):this.g=_.fe(this.K,this.v,this)),this.f=!0,this.a.send(a),this.f=!1}catch(g){Ce(this)}};var Fe=function(a){return _.u&&_.Ka(9)&&_.Va(a.timeout)&&_.v(a.ontimeout)},De=function(a){return"content-type"==a.toLowerCase()};
_.ye.prototype.K=function(){"undefined"!=typeof _.aa&&this.a&&(this.e=8,_.O(this,"timeout"),_.Ge(this,8))};Ce=function(a){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);a.e=5;He(a);Ie(a)};He=function(a){a.l||(a.l=!0,_.O(a,"complete"),_.O(a,"error"))};_.Ge=function(a,b){a.a&&a.b&&(a.b=!1,a.c=!0,a.a.abort(),a.c=!1,a.e=b||7,_.O(a,"complete"),_.O(a,"abort"),Ie(a))};_.ye.prototype.n=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),Ie(this,!0));_.ye.t.n.call(this)};
_.ye.prototype.J=function(){this.D||(this.p||this.f||this.c?Je(this):this.W())};_.ye.prototype.W=function(){Je(this)};Je=function(a){if(a.b&&"undefined"!=typeof _.aa&&(!a.h[1]||4!=(a.a?a.a.readyState:0)||2!=_.Ke(a)))if(a.f&&4==(a.a?a.a.readyState:0))_.fe(a.J,0,a);else if(_.O(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{_.Le(a)?(_.O(a,"complete"),_.O(a,"success")):(a.e=6,He(a))}finally{Ie(a)}}};
Ie=function(a,b){if(a.a){Ee(a);var c=a.a,d=a.h[0]?_.Wa:null;a.a=null;a.h=null;b||_.O(a,"ready");try{c.onreadystatechange=d}catch(e){}}};Ee=function(a){a.a&&a.w&&(a.a.ontimeout=null);_.Va(a.g)&&(_.ge(a.g),a.g=null)};
_.Le=function(a){var b=_.Ke(a),c;t:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break t;default:c=!1}if(!c){if(b=0===b)a=_.gb(String(a.q))[1]||null,!a&&window.self.location&&(a=window.self.location.protocol,a=a.substr(0,a.length-1)),b=!ze.test(a?a.toLowerCase():"");c=b}return c};_.Ke=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}};_.Me=function(a){try{return a.a?a.a.responseText:""}catch(b){return""}};
_.Ne=function(a){_.A(this,a,"h_icr",[])};_.y(_.Ne,_.z);_.D("h_icr",_.Ne);_.Oe=function(a){_.A(this,a,"h_cs",[])};_.y(_.Oe,_.z);_.D("h_cs",_.Oe);_.Oe.prototype.getState=function(){return _.C(this,1)};_.Pe=new _.L("HwdKC");
}catch(e){_._DumpException(e)}
try{
_.Qe=function(){return window.chrome.runtime.getURL("feedbackdialog.html")};
}catch(e){_._DumpException(e)}
try{
var Re=function(a,b){var c,d,e,f;c=window.document;c=b||c;if(c.querySelectorAll&&c.querySelector&&a)return c.querySelectorAll(""+(a?"."+a:""));if(a&&c.getElementsByClassName){var g=c.getElementsByClassName(a);return g}g=c.getElementsByTagName("*");if(a){f={};for(d=e=0;c=g[d];d++){var l=c.className;"function"==typeof l.split&&_.ee(l.split(/\s+/),a)&&(f[e++]=c)}f.length=e;return f}return g},Se=function(a){return a instanceof _.Xd?a.clone():new _.Xd(a,void 0)},Te=function(a){_.A(this,a,0,[])};
_.y(Te,_.z);var Ue=function(a){_.A(this,a,0,[])};_.y(Ue,_.z);var Ve=function(a){_.A(this,a,0,[])};_.y(Ve,_.z);var We=function(a){_.A(this,a,0,[])};_.y(We,_.z);
var Xe=/[?&]($|#)/,Ye=/#|$/,Ze=function(a,b,c,d){for(var e=c.length;0<=(b=a.indexOf(c,b))&&b<d;){var f=a.charCodeAt(b-1);if(38==f||63==f)if(f=a.charCodeAt(b+e),!f||61==f||38==f||35==f)return b;b+=e+1}return-1},$e=function(a){if(a&&"number"==typeof a.length){if(_.Oa(a))return"function"==typeof a.item||"string"==typeof a.item;if(_.ga(a))return"function"==typeof a.item}return!1},af={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",
role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},bf=/&/g,cf=/</g,df=/>/g,ef=/"/g,ff=/'/g,gf=/\x00/g,hf=/[\x00&<>"']/,jf=function(a,b,c){function d(c){c&&b.appendChild(_.p(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];!_.Ja(f)||_.Oa(f)&&0<f.nodeType?d(f):(0,_.s)($e(f)?_.Jd(f):f,d)}},kf=function(a,b){_.Qa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in af?a.setAttribute(af[d],b):0==d.lastIndexOf("aria-",
0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})},lf=function(a){if(!hf.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(bf,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(cf,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(df,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ef,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(ff,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(gf,"&#0;"));return a},mf={LOADING:0,vc:1,yd:2,zd:3,ERROR:4,LOADED:5,uc:6},nf=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,
of=function(a,b,c){for(var d=a.search(Ye),e=0,f,g=[];0<=(f=Ze(a,e,b,d));)g.push(a.substring(e,f)),e=Math.min(a.indexOf("&",f)+1||d,d);g.push(a.substr(e));a=[g.join("").replace(Xe,"$1"),"&",b];null!=c&&a.push("=",(0,window.encodeURIComponent)(String(c)));a[1]&&(c=a[0],b=c.indexOf("#"),0<=b&&(a.push(c.substr(b)),a[0]=c=c.substr(0,b)),b=c.indexOf("?"),0>b?a[1]="?":b==c.length-1&&(a[1]=void 0));return a.join("")},pf=function(a){for(var b;b=a.firstChild;)a.removeChild(b)},qf=function(a){_.J.call(this);
this.c=a;this.a=mf.LOADING;this.b=new _.I(this);_.G(this,this.b);this.b.listen(this.c.ta(),"h_cs",this.e)};_.y(qf,_.J);qf.prototype.getState=function(){return this.a};qf.prototype.e=function(a){a=new _.Oe(a.ab);this.a!=a.getState()&&(this.a=a.getState(),_.O(this,"c"))};
var rf=function(a){(a?a:function(){}).Mc=!0},sf=function(a,b,c){var d=arguments,e=window.document,f=d[0],g=d[1];if(!_.$a&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',lf(g.name),'"');if(g.type){f.push(' type="',lf(g.type),'"');var l={};_.Bd(l,g);delete l.type;g=l}f.push(">");f=f.join("")}f=e.createElement(f);g&&(_.p(g)?f.className=g:_.x(g)?f.className=g.join(" "):kf(f,g));2<d.length&&jf(e,f,d);return f},tf=function(a,b){var c=b||window.document,d=null;c.querySelectorAll&&c.querySelector? d=c.querySelector("."+a):d=Re(a,b)[0];return d||null},uf=function(a){var b;b=b||0;return function(){return a.apply(this,Array.prototype.slice.call(arguments,0,b))}};
var vf=function(a){this.a=a;_.u||(delete this.a.lpu,delete this.a.ppu)},wf=["cn","tp"],xf=function(a,b){var c=null,d;if(_.ga(window.document.postMessage)||_.ga(window.postMessage)||_.u&&window.postMessage)d=1;else if(_.ua)d=2;else{if(c=_.u){c=!1;try{d=window.opener,window.opener={},c=_.cb(window,"opener"),window.opener=d}catch(e){}}d=c?6:4}c=d;d={};d.cn=Math.floor(2147483648*Math.random()).toString(36);d.tp=c;d.ifrid=b;d.pu=a;return new vf(d)};_.Ta("GTalk_IFrameChannelConfig.build",xf);
var yf=function(){if(tf("talk_loading_msg")){var a=tf("talk_loading_msg_error");a&&_.ld(a)}},zf=function(a){var b=tf("talk_loading_msg");if(b){yf();var c=window.document.createElement("DIV");kf(c,{"class":"talk_loading_msg_error",style:"margin: 12px 8px; font-size: 10px"});var d=window.document.createElement("DIV");a="Errors: "+a.join(", ");if("textContent"in d)d.textContent=a;else if(3==d.nodeType)d.data=a;else if(d.firstChild&&3==d.firstChild.nodeType){for(;d.lastChild!=d.firstChild;)d.removeChild(d.lastChild); d.firstChild.data=a}else pf(d),d.appendChild((9==d.nodeType?d:d.ownerDocument||d.document).createTextNode(String(a)));c.appendChild(d);b.appendChild(c)}};
var Af=function(){};_.y(Af,_.le);Af.prototype.b=function(a){return a};rf(Af.prototype.b);Af.prototype.c=function(){return!0};rf(Af.prototype.c);var Bf=function(a){_.A(this,a,0,[])};_.y(Bf,_.z);var Cf=function(a,b){var c=new Bf;_.N(c,1,b);_.N(c,2,a);return c},Df=Cf("?",0),Ef=Cf("q",1),Ff=Cf("<",2),Gf=Cf(">",3),Hf=Cf("~",4),If=Cf("s",5),Jf={e:Df,k:Ef,g:Ff,h:Gf,f:Hf,l:If};var Kf=function(a){_.A(this,a,"ci:dc",[])};_.y(Kf,_.z);_.D("ci:dc",Kf);var Lf=function(a){_.A(this,a,"ci:ec",[])};_.y(Lf,_.z);_.D("ci:ec",Lf);var Mf=function(a){return null!=_.C(a,2)?_.C(a,2):!1};var Nf=function(a){this.a=a},Of=/\s*;\s*/;_.h=Nf.prototype;_.h.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("v`"+a);if(/[;\r\n]/.test(b))throw Error("w`"+b);_.v(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.m)()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};
_.h.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(Of),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.h.remove=function(a,b,c){var d=_.v(this.get(a));this.set(a,"",0,b,c);return d};_.h.M=function(){return Pf(this).keys};_.h.B=function(){return Pf(this).xd};_.h.P=function(){return!this.a.cookie};_.h.V=function(){return this.a.cookie?(this.a.cookie||"").split(Of).length:0};
_.h.clear=function(){for(var a=Pf(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};var Pf=function(a){a=(a.a.cookie||"").split(Of);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,xd:c}};
var Qf=function(a,b,c){_.re(this);var d=this.qb.b(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(0==d.lastIndexOf("https://talkgadget.google.com/talkgadget/",0)){var e=(new Nf(window.document)).get("WCSDBG",""),e=e.split(";")[0],e=e.split("|")[0],f=["plus.google.com"],g=/^[-_a-zA-Z0-9\.]+\.talkgadget\.google\.com$/;0<e.length&&!_.ee(f,e)&&g.test(e)&&(d=Se(d),d=Se("https://"+e+d.N).toString())}this.ca=d;this.c=c||new Lf;a.notificationsOnly&&_.N(this.c,1,!0);this.b="0";null!=a.authUser?
this.b=a.authUser:(c=_.ce(new _.Xd(window.location.href),"authuser"),null!=c&&(this.b=c));this.j=a.clientUrl||"notifierclient";c=_.ce(Se(this.j),"authuser");null!=c&&(this.b=c);this.g=a.propertyName||"Google Talk";this.l=a.cssUrl;this.locale=a.locale;this.f=a.debug;this.Mb=a.userJid;this.Kb=a.uiVersion;this.tc=null!=a.rosterExpanded?a.rosterExpanded:!0;this.S=a.hostLogMinValue;this.Hb=a.hideChat;this.Ac=a.refresh;this.I=a.hideProfileCard;this.L=a.hideStatusMsgs;this.K=a.hideRosterOptions;this.J=a.hideRecentConversations;
this.A=a.hideOTR;this.xc=a.hostServerMessageCallback||!1;this.aa=a.isCentralRoster;this.zc=a.isFullFrame||!1;this.Dc=a.rosterClass||"talk_roster";this.Ra=a.rosterId||"talk_roster";this.a="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.a=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);this.e=a.parentToken;this.Cc=b||!1;_.v(a.isRtl)||nf.test(this.locale);this.position=a.position||"l";if(!a.keyboardShortcuts){b=[];for(var l in Jf)b.push(Jf[l].G)}this.q=
a.entityId;this.Lb=a.useQuasarPanels||!1;this.Ib=a.silent||!1;this.yc=a.ignoreCentralRoster||!1;this.Bc=a.lazy||!1;this.wc=a.handleProfileLinks||!1;this.W=a.hostSettings;this.h=a.screen;this.p=a.docsConfig;this.za=a.jsmode;this.Ca=a.moleWidth;this.Ba=a.moleHeight;this.Aa=a.minimizedMoleHeight||36;this.Ec=a.derp;this.Jb=window.location.protocol+"//"+window.location.host;this.v=a.optOutAllowed;this.w=a.showWelcomePromo;this.u=a.legacyTalkSignedIn;this.k=a.conversationId};Af.t||_.y(Af,_.le);Qf.ia=Af;
var Rf=function(a){switch(a){case 1:return"homepage";case 2:return"Orkut";case 3:return"iGoogle";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";case 6:return"customersupport";case 9:return"present";case 15:return"hangout";case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 25:return"bigtop";case 27:return"ChromeApp";case 29:return"potluck"}};
var Sf=function(a,b,c,d,e){_.E.call(this);this.a=a;this.b=d||window.document;this.c=new _.I(this);_.G(this,this.c);var f=_.t;d=new _.Xd(a.ca+a.j);Mf(a.c)||(_.R(d,"ts","0"),_.R(d,"re",a.tc),_.R(d,"ref",a.Ac));_.R(d,"client","sm");_.R(d,"prop",a.g);_.R(d,"nav","true");_.R(d,"fid",a.a);a.f&&_.R(d,"debug",a.f);_.R(d,"os",_.xa);_.R(d,"stime",c);a.Hb&&_.R(d,"hc",a.Hb);for(c=0;c<wf.length;++c);b=_.Ad(b.a);_.R(d,"xpc",b);_.R(d,"ec",_.Ad(a.c.G));a.h&&_.R(d,"screen",a.h);-1!=f.indexOf("MSIE")&&_.R(d,"ua",f);
a.e&&_.R(d,"pvt",a.e);a.xc&&_.R(d,"hsmc","true");_.v(a.S)&&_.R(d,"logl",a.S);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),_.R(d,"href",b.join("?")));b=new _.Xd(window.location.href);"false"==_.ce(b,"uacheck")&&_.R(d,"uacheck",!1);(f=a.za)&&_.R(d,"jsmode",f);(f=_.ce(b,"cssmode"))&&_.R(d,"cssmode",f);(f=_.ce(b,"convid"))&&_.R(d,"convid",f);(f=b.a.B("convp"))&&_.be(d,"convp",f);(f=_.ce(b,"smexp"))&&_.R(d,"smexp",f);f=b.a.B("mods");a.Bc&&
f.push("lazy");e&&(f=_.Id(f,e));0<f.length&&_.R(d,"mods",f.join(","));if(!a.ca||0>a.ca.indexOf("/u/"))(e=_.ce(b,"authuser"))?_.R(d,"authuser",e):null!=a.b&&_.R(d,"authuser",a.b);e=_.ce(b,"eid");/^[\s\xa0]*$/.test(null==e?"":String(e))||_.R(d,"eid",e);e=this.a.q;/^[\s\xa0]*$/.test(null==e?"":String(e))||_.R(d,"eid",this.a.q);null!=this.a.position&&_.R(d,"pos",this.a.position);_.v(a.Kb)&&_.R(d,"uiv",this.a.Kb);a.l&&_.R(d,"css",a.l);e=a.locale||_.ce(b,"hl");null!=e&&_.R(d,"hl",e);_.v(a.Mb)&&_.R(d,"uj",
a.Mb);null!=a.I&&_.R(d,"hpc",a.I);null!=a.L&&_.R(d,"hsm",a.L);null!=a.K&&_.R(d,"hro",a.K);null!=a.J&&_.R(d,"hrc",a.J);null!=a.A&&_.R(d,"hotr",a.A);null!=a.aa&&_.R(d,"pop",a.aa);a.Cc&&_.R(d,"pal","1");null!=a.Lb&&_.R(d,"uqp",a.Lb);null!=a.v&&_.R(d,"gooa",a.v);null!=a.w&&_.R(d,"gswp",a.w);null!=a.u&&_.R(d,"gltsi",a.u);null!=a.Ib&&_.R(d,"sl",a.Ib);a.yc&&_.R(d,"icr","1");a.wc&&_.R(d,"hpl","1");a.W&&_.R(d,"hs",a.W);a.p&&_.R(d,"dc",_.Ad(a.p.G));null!=a.Ca&&_.R(d,"molew",a.Ca);null!=a.Ba&&_.R(d,"moleh",
a.Ba);null!=a.Aa&&_.R(d,"mmoleh",a.Aa);a.Ec&&_.R(d,"derp","1");null!=a.Jb&&_.R(d,"two",a.Jb);null!=a.k&&_.R(d,"convid",a.k);_.R(d,"host","1");_.R(d,"zx",_.Wd());this.e=d.toString()};_.y(Sf,_.E);
var Tf=function(a,b,c,d){var e=a.b.getElementById(b);e||(e=a.b.createElement("div"),e.id=b,e.className=a.a.Dc,a.b.body.appendChild(e));a=(0,_.n)(function(){var a="";this.a.zc||(a="height:400px");var b=this.b.createElement("iframe");kf(b,{id:this.a.a,name:this.a.a,"class":"talk_iframe",frameborder:"0",style:a});tf("talk_loading_msg",e)||pf(e);e.appendChild(b);a=this.b.getElementById(this.a.a);_.Ed(this.c,a,["load","error"],uf(d),void 0);a.src=this.e.toString();c()},a);window.setTimeout(a,0)};
var Uf=function(a){_.H.call(this,a[0]);this.ab=a};_.y(Uf,_.H);var Vf=function(a){_.A(this,a,"h_ccf",[])};_.y(Vf,_.z);_.D("h_ccf",Vf);var Wf=function(a){_.A(this,a,"h_rtp",[])};_.y(Wf,_.z);_.D("h_rtp",Wf);var Xf=function(a,b){_.E.call(this);this.I=(0,_.m)();this.A=a;this.document=b||window.document;this.a=new Qf(a,!0,a.endpointConfig);this.g=[];this.q=new _.J;this.f=null};_.y(Xf,_.E);Xf.prototype.n=function(){Xf.t.n.call(this);_.ge(this.f);this.b&&this.l&&this.b.parentNode.removeEventListener("DOMAttrModified",this.l,!0)};Xf.prototype.e=function(a,b){this.c?this.c[a]&&this.c[a].apply(this.c,Array.prototype.slice.call(arguments,1)):this.g.push(arguments)};
Xf.prototype.h=function(){var a=this.Zb().GTalkNotifier;if(a){var b=_.ie(this.A);b.endpointConfig=this.a.c.G;this.c=new a(b,!0);for(a=0;a<this.g.length;a++)this.e.apply(this,this.g[a]);this.g=[];a=(0,_.n)(this.onMessage,this);this.e("_addClientMessageCallback",a);this.e("_addHostBundleMessageCallback",a)}};Xf.prototype.onMessage=function(a){switch(a[0]){case "h_ccf":new Vf(a)}_.O(this.q,new Uf(a))};var Yf=function(a,b){a.e("_h",b.G)};_.h=Xf.prototype;_.h.sendMessage=function(a){Yf(this,a)};
_.h.ta=function(){return this.q};_.h.Zb=function(){return this.document.parentWindow||this.document.defaultView};_.h.Vc=function(a,b){if(b.target==a&&("style"==b.attrName||"class"==b.attrName)){var c=new Wf;Yf(this,c)}};_.h.Wc=function(){tf("talk_loading_msg",this.document.getElementById(this.a.Ra))&&(this.document.getElementById(this.a.a).style.display="none")};
var Zf=function(a){var b=a.a.ca+"host-js",b=of(b,"prop",a.a.g),c=a.a.za;c&&(b=of(b,"jsmode",c));Mf(a.a.c)&&(b=of(b,"b","1"));var b=of(b,"zx",_.Wd()),d=(0,_.n)(a.h,a),e=sf("script",{type:"text/javascript",src:b}),f=!1;e.onload=e.onreadystatechange=function(){f||e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(f=!0,d())};e.onerror=(0,_.n)(a.u,a,e);a.f&&(_.ge(a.f),a.f=null);a.f=_.fe((0,_.n)(function(){null!=this.c||this.v(e)},a),25E3);a.document.body.appendChild(e)};Xf.prototype.u=function(){}; Xf.prototype.v=function(){};
var $f=function(a){if(a.classList)return a.classList;a=a.className;return _.p(a)&&a.match(/\S+/g)||[]},ag=function(a){return a.classList?a.classList.contains("talk_network_warning"):_.ee($f(a),"talk_network_warning")},bg=function(a){a.classList?a.classList.remove("talk_network_warning"):ag(a)&&(a.className=(0,_.ka)($f(a),function(a){return"talk_network_warning"!=a}).join(" "))};
var cg=function(a,b){this.b=b;this.a=a};cg.prototype.F=function(){return this.a};var dg=function(a){a.a=Math.min(a.b,2*a.a)};var eg=function(a,b,c){var d={},e=null!=_.C(a,1)?_.C(a,1):"talkgadget.google.com",f="";0>e.indexOf("://")&&(f="https://",0<=e.indexOf(":")&&23!=_.C(a,2)&&27!=_.C(a,2)&&(f="http://"));d.clientBaseUrl=f+e+"/talkgadget/_/";d.authUser=null!=_.C(a,8)?_.C(a,8):"0";d.clientUrl="chat";d.propertyName=Rf(_.C(a,2));d.locale=_.C(a,4);d.hideProfileCard=!0;d.parentToken=_.C(a,3);d.isRtl=null!=_.C(a,6)?_.C(a,6):!1;d.lazy=null!=_.C(a,7)?_.C(a,7):!1;d.entityId=_.C(a,9);d.hostSettings=_.C(a,5);d.jsmode=_.C(a,11);d.isFullFrame=
null!=_.C(a,13)?_.C(a,13):!1;d.rosterId=null!=_.C(a,12)?_.C(a,12):"talk_roster";d.rosterIframeIdB=null!=_.C(a,15)?_.C(a,15):"gtn-roster-iframe-id-b";d.derp=!(null==_.C(a,16)||!_.C(a,16));e=_.Q(a,Te,14);null!=e&&(d.isCentralRoster=null!=_.C(e,1)?_.C(e,1):!1,d.useQuasarPanels=null!=_.C(e,2)?_.C(e,2):!1);e=_.Q(a,We,10);null!=e&&(d.moleManagerLeftMargin=_.C(e,1),d.moleManagerMiddleMargin=_.C(e,2),d.moleManagerRightMargin=_.C(e,3),d.moleManagerNoMoleAreaMargin=_.C(e,4),d.moleManagerBoundingElementId=_.C(e,
5),d.moleWidth=_.C(e,6),d.moleHeight=_.C(e,7),d.minimizedMoleHeight=_.C(e,8));e=_.Q(a,Ve,18);null!=e&&(d.optOutAllowed=null!=_.C(e,1)?_.C(e,1):!0,d.showWelcomePromo=_.C(e,2),e=_.Q(e,Ue,3),null!=e&&(d.legacyTalkSignedIn=null!=_.C(e,1)?_.C(e,1):!0));d.uiVersion=2;d.hideStatusMsgs=!0;d.hideRecentConversations=!0;e=new Lf;_.N(e,2,!0);_.N(e,1,!0);_.N(e,3,!1);d.endpointConfig=e;d.ignoreAutomatedRoster=null!=_.C(a,17)?_.C(a,17):!1;d.conversationId=a.Z();d.hostCallback=c;Xf.call(this,d,b);this.p=new cg(5E3,
3E5);this.w=null};_.y(eg,Xf);var fg=function(a,b){var c=1+.5*Math.random();a.w=_.fe(function(){null==this.c&&(_.de(this.document.body,b)&&this.document.body.removeChild(b),Zf(this))},a.p.F()*c,a);dg(a.p)};eg.prototype.v=function(a){zf(["301"]);fg(this,a)};eg.prototype.u=function(a){var b=tf("talk_loading_msg",this.document.body);b&&(b.classList?b.classList.add("talk_network_warning"):ag(b)||(b.className+=0<b.className.length?" talk_network_warning":"talk_network_warning"));zf(["302"]);fg(this,a)}; eg.prototype.h=function(){eg.t.h.call(this);var a=tf("talk_loading_msg",this.document.body);a&&bg(a);yf()};eg.prototype.n=function(){eg.t.n.call(this);_.ge(this.w)};
var gg=function(a){_.A(this,a,"h_exts",[2])};_.y(gg,_.z);_.D("h_exts",gg);var hg=function(){_.E.call(this);this.b=" "};_.y(hg,_.E);var ig=function(a,b,c){a.a=c;b=new _.Xd(b);b=_.ae(b,new _.Xd("/talkgadget/_/extension-start"));a=(0,_.n)(a.c,a);c=new _.ye;_.Be.push(c);a&&c.listen("complete",a);c.U.add("ready",c.S,!0,void 0,void 0);c.send(b,void 0,void 0,void 0)};hg.prototype.c=function(a){if(!this.D){if(_.Le(a.target))try{var b=JSON.parse(_.Me(a.target)),c=new gg(b);this.b=_.C(c,1)||""}catch(d){this.b=""}this.a&&(this.a(),this.a=null)}};
var jg=function(a){_.J.call(this);this.c=a?a:null;this.a=null;this.e=!1;this.b=[];this.f=(0,_.n)(this.Gc,this);this.g=(0,_.n)(this.Nb,this);this.h=null};_.y(jg,_.J);var kg=function(a){_.H.call(this,"message");this.message=a};_.y(kg,_.H);_.h=jg.prototype;_.h.n=function(){jg.t.n.call(this);_.ge(this.h);this.Nb(!0);for(var a=0;a<this.b.length;++a)_.F(this.b[a]);delete this.b;delete this.f;delete this.g};
_.h.sendMessage=function(a){if(null==a||null==a.message)return!1;_.Nc(a,this.c,"p");this.a&&this.e?this.a.postMessage(a.message()):this.b.push(a);return!0};_.h.connect=function(){if(null==this.c)return!1;try{if(this.a=window.chrome.runtime.connect({name:this.c}),null==this.a)return!1}catch(a){return!1}this.e=!0;this.a.onMessage.addListener(this.f);this.a.onDisconnect.addListener(this.g);for(var b=this.b.shift();null!=b;)_.Nc(b,this.c,"p"),this.a.postMessage(b.message()),b=this.b.shift();return!0};
_.h.Gc=function(a){_.O(this,new kg(_.Mc(new _.Lc,a)))};_.h.Nb=function(a){this.a&&(this.a.onMessage.removeListener(this.f),this.a.onDisconnect.removeListener(this.g),this.a.disconnect(),delete this.a);this.e=!1;a||(this.h=_.fe(this.qd,5E3,this))};_.h.qd=function(){this.connect()?_.O(this,{type:"reconnected"}):_.O(this,{type:"disconnected"})};
var lg=function(a){_.A(this,a,"h_cp",[])};_.y(lg,_.z);_.D("h_cp",lg);var mg=function(a){_.A(this,a,"rbc_d",[])};_.y(mg,_.z);_.D("rbc_d",mg);mg.prototype.setTitle=function(a){_.N(this,1,a)};var ng=function(a){_.A(this,a,"h_cd",[1,4,5])};_.y(ng,_.z);_.D("h_cd",ng);ng.prototype.Z=function(){return _.C(this,2)};var og=function(a){_.A(this,a,"h_hn",[])};_.y(og,_.z);_.D("h_hn",og);var pg=function(a){_.A(this,a,"h_hs",[])};_.y(pg,_.z);_.D("h_hs",pg);var qg=function(a){_.A(this,a,"h_jm",[2])};_.y(qg,_.z);_.D("h_jm",qg);var rg=function(a){_.A(this,a,"h_oc",[])};_.y(rg,_.z);_.D("h_oc",rg);var sg=function(a){_.A(this,a,"h_opc",[])};_.y(sg,_.z);_.D("h_opc",sg);var tg=function(a){_.A(this,a,"h_ogc",[])};_.y(tg,_.z);_.D("h_ogc",tg);var ug=function(a){_.A(this,a,"h_sc",[])};_.y(ug,_.z);_.D("h_sc",ug);var vg=function(a){_.A(this,a,"h_ssc",[5])};_.y(vg,_.z);_.D("h_ssc",vg);var wg=function(a){_.A(this,a,"h_sm",[1,3])};_.y(wg,_.z);_.D("h_sm",wg);var xg=function(a){_.J.call(this);this.a=a};_.y(xg,_.J);var yg=new _.L("O9EQob");var zg=function(a){_.A(this,a,"capi:f_cfr",[])};_.y(zg,_.z);_.D("capi:f_cfr",zg);var Ag=function(a){_.A(this,a,"capi:f_cvr",[])};_.y(Ag,_.z);_.D("capi:f_cvr",Ag);var Bg=function(a){_.A(this,a,"capi:f_vsm",[])};_.y(Bg,_.z);_.D("capi:f_vsm",Bg);var Cg=function(a){_.A(this,a,"capi:f_ccr",[])};_.y(Cg,_.z);_.D("capi:f_ccr",Cg);var Dg=function(a){_.A(this,a,"capi:f_csm",[])};_.y(Dg,_.z);_.D("capi:f_csm",Dg);var Eg=function(a){_.A(this,a,0,[])};_.y(Eg,_.z);var Fg=function(a){_.A(this,a,"capi:f_var",[])};
_.y(Fg,_.z);_.D("capi:f_var",Fg);Fg.prototype.getState=function(){return _.Q(this,Eg,1)};var Gg=function(a){_.A(this,a,"capi:f_van",[])};_.y(Gg,_.z);_.D("capi:f_van",Gg);Gg.prototype.getState=function(){return _.Q(this,Eg,1)};var Hg=function(a){_.A(this,a,0,[])};_.y(Hg,_.z);var Ig=function(a){_.A(this,a,"capi:f_vcr",[])};_.y(Ig,_.z);_.D("capi:f_vcr",Ig);Ig.prototype.getState=function(){return _.Q(this,Hg,1)};var Jg=function(a){_.A(this,a,"capi:f_vcn",[])};_.y(Jg,_.z);_.D("capi:f_vcn",Jg);
Jg.prototype.getState=function(){return _.Q(this,Hg,1)};var Kg=function(a){_.A(this,a,0,[])};_.y(Kg,_.z);var Lg=function(a){_.A(this,a,"capi:f_vcor",[])};_.y(Lg,_.z);_.D("capi:f_vcor",Lg);Lg.prototype.getState=function(){return _.Q(this,Kg,1)};var Mg=function(a){_.A(this,a,"capi:f_vcon",[])};_.y(Mg,_.z);_.D("capi:f_vcon",Mg);Mg.prototype.getState=function(){return _.Q(this,Kg,1)};var Ng=function(a){_.A(this,a,0,[])};_.y(Ng,_.z);var Og=function(a){_.A(this,a,"capi:f_vfr",[])};_.y(Og,_.z);
_.D("capi:f_vfr",Og);Og.prototype.getState=function(){return _.Q(this,Ng,1)};var Pg=function(a){_.A(this,a,"capi:f_vfn",[])};_.y(Pg,_.z);_.D("capi:f_vfn",Pg);Pg.prototype.getState=function(){return _.Q(this,Ng,1)};var Qg=function(a){_.A(this,a,0,[])};_.y(Qg,_.z);var Rg=function(a){_.A(this,a,"capi:f_vmr",[])};_.y(Rg,_.z);_.D("capi:f_vmr",Rg);Rg.prototype.getState=function(){return _.Q(this,Qg,1)};var Sg=function(a){_.A(this,a,"capi:f_vmn",[])};_.y(Sg,_.z);_.D("capi:f_vmn",Sg);
Sg.prototype.getState=function(){return _.Q(this,Qg,1)};var Tg=function(a){_.A(this,a,0,[])};_.y(Tg,_.z);var Ug=function(a){_.A(this,a,"capi:f_vpr",[])};_.y(Ug,_.z);_.D("capi:f_vpr",Ug);Ug.prototype.getState=function(){return _.Q(this,Tg,1)};var Vg=function(a){_.A(this,a,"capi:f_vpn",[])};_.y(Vg,_.z);_.D("capi:f_vpn",Vg);Vg.prototype.getState=function(){return _.Q(this,Tg,1)};var Wg=function(a){_.A(this,a,"capi:f_vsr",[])};_.y(Wg,_.z);_.D("capi:f_vsr",Wg);
var Xg=function(a){_.A(this,a,"capi:f_vsn",[])};_.y(Xg,_.z);_.D("capi:f_vsn",Xg);var Yg=function(a){_.A(this,a,"capi:f_vtr",[])};_.y(Yg,_.z);_.D("capi:f_vtr",Yg);Yg.prototype.setTitle=function(a){_.Fd(this,1,a)};var Zg=function(a){_.A(this,a,"capi:f_vtn",[])};_.y(Zg,_.z);_.D("capi:f_vtn",Zg);Zg.prototype.setTitle=function(a){_.Fd(this,1,a)};var $g=function(a){_.A(this,a,0,[])};_.y($g,_.z);var ah=function(a){_.A(this,a,"capi:f_vvr",[])};_.y(ah,_.z);_.D("capi:f_vvr",ah);
ah.prototype.getState=function(){return _.Q(this,$g,1)};var bh=function(a){_.A(this,a,"capi:f_vvn",[])};_.y(bh,_.z);_.D("capi:f_vvn",bh);bh.prototype.getState=function(){return _.Q(this,$g,1)};var ch=function(a){_.A(this,a,0,[])};_.y(ch,_.z);var dh=function(a){_.A(this,a,"capi:f_uvor",[])};_.y(dh,_.z);_.D("capi:f_uvor",dh);var eh=function(a){_.A(this,a,"capi:f_uvon",[])};_.y(eh,_.z);_.D("capi:f_uvon",eh);var fh=function(a){_.A(this,a,0,[])};_.y(fh,_.z);var gh=function(a){_.A(this,a,"capi:f_sp",[])}; _.y(gh,_.z);_.D("capi:f_sp",gh);gh.prototype.getState=function(){return _.Q(this,fh,1)};var hh=function(a){_.A(this,a,"capi:f_spn",[])};_.y(hh,_.z);_.D("capi:f_spn",hh);hh.prototype.getState=function(){return _.Q(this,ch,1)};
var ih=function(a){_.A(this,a,"uvc",[])};_.y(ih,_.z);_.D("uvc",ih);var jh=function(a){_.A(this,a,"capi:clstup",[])};_.y(jh,_.z);_.D("capi:clstup",jh);var kh=function(a){_.A(this,a,"capi:r_clre",[])};_.y(kh,_.z);_.D("capi:r_clre",kh);var lh=function(a){_.A(this,a,"capi:r_rrst",[])};_.y(lh,_.z);_.D("capi:r_rrst",lh);var mh=function(a){_.A(this,a,"capi:r_rers",[])};_.y(mh,_.z);_.D("capi:r_rers",mh);var nh=function(a){_.A(this,a,"capi:r_recl",[])};_.y(nh,_.z);_.D("capi:r_recl",nh);var oh=function(a){_.A(this,a,"capi:r_rstr",[])};_.y(oh,_.z);_.D("capi:r_rstr",oh);
var ph=new _.L("nED8Yb"),qh=new _.L("xclgJb");var rh=function(a){_.A(this,a,"h_ec",[])};_.y(rh,_.z);_.D("h_ec",rh);var sh=function(a){_.A(this,a,"h_fr",[])};_.y(sh,_.z);_.D("h_fr",sh);var th=function(a){_.A(this,a,"capii_c_cel",[])};_.y(th,_.z);_.D("capii_c_cel",th);var uh=function(a){_.A(this,a,"capi:rfc",[])};_.y(uh,_.z);_.D("capi:rfc",uh);var vh=function(a){_.A(this,a,"capii_c_ucmc",[])};_.y(vh,_.z);_.D("capii_c_ucmc",vh);var wh=function(a){_.A(this,a,"capii_c_rc",[])};_.y(wh,_.z);_.D("capii_c_rc",wh);wh.prototype.Z=function(){return _.C(this,1)};
var xh=function(a){_.J.call(this);this.c=a.get(ph);this.a=this.f=0;this.e=this.b=!1;a=new _.I(this);_.G(this,a);a.listen(this.c.ta(),"capii_c_ucmc",this.g);this.c.sendMessage(new vh)};_.y(xh,_.J);xh.prototype.g=function(a){a=new vh(a.ab);this.b||(this.b=!0,this.e&&(_.N(a,5,!0),this.e=!1));var b=this.f!=_.C(a,1);this.f=Number(_.C(a,1));var c=this.a!=_.C(a,2);this.a=Number(_.C(a,2));_.C(a,5)?_.O(this,"g"):(b&&_.O(this,"i"),c&&_.O(this,"h"))};
var yh=function(a){_.A(this,a,"h_rha",[])};_.y(yh,_.z);_.D("h_rha",yh);var zh=function(a){_.A(this,a,"h_ssf",[])};_.y(zh,_.z);_.D("h_ssf",zh);var Ah=function(a,b){_.E.call(this);this.a=new _.I(this);_.G(this,this.a);this.a.listen(a.ta(),"h_ssf",function(a){a=new zh(a.ab);a=_.C(a,1);var c;if(null!=a&&JSON&&JSON.parse)try{c=JSON.parse(a)}catch(f){}b(c)});var c=new yh;_.N(c,1,1);Yf(a,c)};_.y(Ah,_.E);
var Bh=function(a){_.A(this,a,"h_ext",[])};_.y(Bh,_.z);_.D("h_ext",Bh);var Ch=function(a){_.A(this,a,"h_sru",[])};_.y(Ch,_.z);_.D("h_sru",Ch);var Fh=function(){_.I.call(this);this.b=new _.od;_.G(this,this.b);this.l=this.h=this.k=this.a=null;this.q=_.Jc("quasar",""+(new Date).getTime());this.c=[];this.e=new jg(this.q);_.G(this,this.e);this.f=null;this.e.connect();_.Lb(this,this.e,"message",this.J,!0,this);this.p=new hg;_.G(this,this.p);this.listen(window,"unload",this.C);this.listen(window,"load",this.v);Dh(this,(0,_.n)(function(){Eh(this,["onHostReady"],"extensionLibrary")},this))},Gh;_.y(Fh,_.I);var Dh=function(a,b){null==a.c?b():a.c.push(b)};
Fh.prototype.v=function(){var a=new _.Uc(_.Yc.ua().get("settings"));this.f=a.b[0];_.F(a);ig(this.p,this.f,(0,_.n)(function(){if(!this.D&&-1!=this.f.lastIndexOf("talkgadget/")){var a=new Lf;_.N(a,2,!0);var a=new _.Ib,c=Se(this.f),d=c.R;null!=c.ea&&(d+=":"+c.ea);_.N(a,1,d);_.N(a,2,23);d=window.chrome.i18n.getMessage("@@ui_locale");_.N(a,4,d);_.N(a,13,!0);_.N(a,17,!0);(d=this.p.b)&&_.N(a,3,d);c=_.ce(c,"jsmode");null!=c&&_.N(a,11,c);c=new Te;_.N(c,2,!0);_.N(c,1,!0);_.Fd(a,14,c);a=new eg(a,void 0,(0,_.n)(this.A,
this));_.p(void 0)&&(a.a.e=void 0);c=a.a;var e=a.a.ca,d=a.a.b,f=Se(e),g=f.N;if(0<=g.indexOf("/u/"))d=e;else{e=g.lastIndexOf("_/");if(0>e||e!=g.length-2)g+="_/";f.N="/u/"+d+g;d=f.toString()}c.ca=d;a.a.j=a.a.j.replace("notifierclient","chat");a.k||(c=xf(a.a.ca,a.a.a),a.k=new Sf(a.a,c,a.I,a.document,void 0),_.G(a,a.k));Tf(a.k,a.a.Ra,(0,_.n)(a.Wc,a),(0,_.n)(a.e,a,"_rosterIframeLoaded"));_.uc&&(a.b=a.document.createElement("IFRAME"),a.b.id="gth-talk-plugin-frame-id",a.b.name="gth-talk-plugin-frame-id",
a.b.src=a.a.ca+"blank",a.b.style.cssText="width: 0px; height: 0px; position: absolute; top: 0px; left: 0px; visibility:hidden;",a.document.documentElement.appendChild(a.b),a.l=(0,_.n)(a.Vc,a,a.b.parentNode),a.b.parentNode.addEventListener("DOMAttrModified",a.l,!0));Zf(a);this.a=a;this.b.a(ph,this.a);this.k=new qf(this.a);this.b.a(_.Pe,this.k);this.listen(this.k,"c",this.w);this.h=new xg(this.a);this.b.a(yg,this.h);this.l=new xh(this.b);this.b.a(qh,this.l);this.listen(this.l,"h",this.u);this.u();a=
new Ah(this.a,(0,_.n)(this.K,this));_.G(this,a);this.listen(this.a.ta(),"h_sru",this.L)}for(;this.c.length;)this.c.shift()();this.c=null},this))};Fh.prototype.A=function(a,b){if("extensionMessage"==a)if("__reload__"==b)window.chrome.runtime.reload();else{var c=new _.Lc;_.Mc(c,JSON.parse(b)||{});this.e.sendMessage(c)}};Fh.prototype.w=function(){var a;switch(this.k.getState()){case mf.LOADING:a=2;break;case mf.vc:a=4;break;case mf.uc:a=3;break;default:return}Eh(this,["changeDesktop",a],"desktopManager")};
Fh.prototype.J=function(a){Dh(this,(0,_.n)(function(){var b=a.message;switch(b.a){case "onSendHostMessage":var c=new Bh,b=b.content().toString();_.N(c,1,b);this.a.sendMessage(c);break;case "onOpenConversation":var b=b.content()[0],c=this.h,d=new rg;_.N(d,1,b);Yf(c.a,d);d=new ng;_.N(d,1,[b]);b=new sg;_.Fd(b,1,d);Yf(c.a,b);break;case "h_icr":c=b.content()[0],b=this.h,d=new _.Ne,_.N(d,1,c),Yf(b.a,d)}},this))};
var Eh=function(a,b,c){var d=new _.Lc;_.Nc(d,a.q,"p");_.Cd(d,"","e");_.Pc(d,b);null!=c&&(d.g=c);_.Oc(d,""+(0,_.m)());a.e.sendMessage(d)};Fh.prototype.K=function(){var a=_.Qe();window.open(a)};Fh.prototype.L=function(a){a=new Ch(a.ab);Eh(this,["setRosterUrl",_.C(a,2)],"dataChannelManager")};Fh.prototype.u=function(){Eh(this,["setUnreadIndicator",!!this.l.a],"desktopManager")};
if(!_.v(Gh)||null==Gh||Gh.D)Gh=new Fh;
}catch(e){_._DumpException(e)}
}).call(this,this.default_datachannel);
// Google Inc.
