"use strict";this.default_feedback=this.default_feedback||{};(function(_){var window=this;
try{
_.aa=_.aa||{};_.k=this;_.ba="closure_uid_"+(1E9*Math.random()>>>0);_.m=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
try{
var ca,ea;ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};ea=function(a,b,c){return a.call.apply(a.bind,arguments)};
_.fa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.n=function(a,b,c){_.n=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:ca;return _.n.apply(null,arguments)};_.ga=function(a){return"function"==_.fa(a)};_.p=function(a){return"string"==typeof a};
_.ha=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};_.r=Array.prototype;_.ia=_.r.indexOf?function(a,b,c){return _.r.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.p(a))return _.p(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.ja=_.r.lastIndexOf?function(a,b,c){return _.r.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(_.p(a))return _.p(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.s=_.r.forEach?function(a,b,c){_.r.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.p(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.ka=_.r.filter?function(a,b,c){return _.r.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=_.p(a)?a.split(""):a,l=0;l<d;l++)if(l in g){var q=g[l];b.call(c,q,l,a)&&(e[f++]=q)}return e};_.ma=_.r.map?function(a,b,c){return _.r.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.p(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
_.na=_.r.reduce?function(a,b,c,d){d&&(b=(0,_.n)(b,d));return _.r.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,_.s)(a,function(c,g){e=b.call(d,e,c,g,a)});return e};_.pa=_.r.some?function(a,b,c){return _.r.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.p(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};
_.qa="StopIteration"in _.k?_.k.StopIteration:Error("d");t:{var ra=_.k.navigator;if(ra){var sa=ra.userAgent;if(sa){_.t=sa;break t}}_.t=""};var wa,ya,Aa;_.ta=-1!=_.t.indexOf("Opera")||-1!=_.t.indexOf("OPR");_.u=-1!=_.t.indexOf("Trident")||-1!=_.t.indexOf("MSIE");_.ua=-1!=_.t.indexOf("Gecko")&&-1==_.t.toLowerCase().indexOf("webkit")&&!(-1!=_.t.indexOf("Trident")||-1!=_.t.indexOf("MSIE"));_.va=-1!=_.t.toLowerCase().indexOf("webkit");wa=_.k.navigator||null;_.xa=wa&&wa.platform||"";ya=function(){var a=_.k.document;return a?a.documentMode:void 0};
_.za=function(){var a="",b;if(_.ta&&_.k.opera)return a=_.k.opera.version,_.ga(a)?a():a;_.ua?b=/rv\:([^\);]+)(\)|;)/:_.u?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:_.va&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(_.t))?a[1]:"");return _.u&&(b=ya(),b>(0,window.parseFloat)(a))?String(b):a}();Aa=_.k.document;_.Ba=Aa&&_.u?ya()||("CSS1Compat"==Aa.compatMode?(0,window.parseInt)(_.za,10):5):void 0;
_.k.ace_i18n={chrome_ext_short_name:{message:"Hangouts"},chrome_ext_description:{message:"Hangouts brings conversations to life with photos, emoji, and even group video calls for free."},quasar_chat_toast_info:{message:"Click to go to page..."},quasar_answer_button_text:{message:"Answer"},quasar_decline_button_text:{message:"Decline"},quasar_help:{message:"Help"},quasar_legend_startup_shutdown:{message:"Application"},chrome_ext_run_at_browser_start:{message:"Sign in to Hangouts when Chrome starts"},
chrome_ext_run_after_browser_close:{message:"Allow background mode"},chrome_ext_new_windows_topmost:{message:"Keep Hangouts on top of other windows"},quasar_label_tray_icon:{message:"Show system tray icon"},quasar_legend_notifications:{message:"Notifications"},quasar_label_all_notification:{message:"Disable notifications"},quasar_label_chat_notification:{message:"Disable chat notifications"},quasar_label_toast_timeout_chat:{message:"Allow chat notifications to timeout automatically"},quasar_label_toast_duration_chat:{message:"Timeout length (in seconds):"},
quasar_button_save:{message:"Ok"},quasar_button_apply:{message:"Apply"},quasar_button_cancel:{message:"Cancel"},chrome_ext_menutext_feedback:{message:"Send feedback"},quasar_feedback_server_uri:{message:"https://www.google.com/tools/feedback"},chrome_ext_feedback_subtitle:{message:"Send feedback"},chrome_ext_feedback_comments:{message:"Comments"},quasar_feedback_system_legend:{message:"System Information"},quasar_feedback_platform_label:{message:"Platform:"},quasar_feedback_user_agent_label:{message:"User Agent:"},
quasar_feedback_privacy_legend:{message:"Privacy Statement"},quasar_feedback_privacy_text:{message:"The description, product information, additional information and your email address will be sent to Google. See the Google Feedback Terms of Service. By submitting this content you are granting to Google the right to use it to improve our products and services. See our Privacy Policy."},quasar_feedback_submit_button:{message:"Send Feedback"},quasar_feedback_cancel_button:{message:"Cancel"},quasar_video_title:{message:"Video call from $1...",
placeholders:{1:{content:"$1"}}},quasar_voice_title:{message:"Voice call from $1...",placeholders:{1:{content:"$1"}}},quasar_group_chat_title:{message:"From group chat..."},quasar_chat_title:{message:"$1 says...",placeholders:{1:{content:"$1"}}},quasar_hangout_title:{message:"$1 is hanging out",placeholders:{1:{content:"$1"}}},chrome_ext_oneonone_plus_hangout_details:{message:"is video calling you via Hangouts"},chrome_ext_group_plus_hangout_details:{message:"has invited you to a group Hangout video call"},
quasar_video_details:{message:"is calling you with video chat"},quasar_voice_details:{message:"is calling you"},quasar_tip_connected:{message:"Status: Connected"},chrome_ext_tip_connected_missed_messages:{message:"Status: Connected\nMissed messages"},quasar_tip_connecting:{message:"Status: Connecting"},quasar_tip_reconnecting:{message:"Status: Reconnecting"},quasar_tip_disconnected:{message:"Status: Disconnected"},quasar_tip_not_login:{message:"Status: Not logged in"},quasar_tip_not_load:{message:"Status: Loading error"},
chrome_ext_menutext_unsigned_user:{message:"Not signed in"},quasar_menutext_unknown_user:{message:"Unknown"},quasar_menutext_feedback:{message:"Feedback"},quasar_menutext_settings:{message:"Options"},quasar_menutext_quit:{message:"Exit"},quasar_menutext_signout:{message:"Sign out"},chrome_ext_cannot_connect:{message:"Unable to connect to Google. Please check your internet connection."},quasar_try_now:{message:"Try now"},quasar_sign_in_to_start_talking:{message:"Sign in to start talking with friends"},
quasar_sign_in:{message:"Sign in"},chrome_app_description:{message:"Always stay connected with the new desktop app for Hangouts on ChromeOS and Windows."},chrome_app_connection_error_title:{message:"Connection Error"},chrome_app_connection_error_detail:{message:"Make sure you are connected to the Internet and try again"},chrome_app_connection_error_button:{message:"Try again"},chrome_app_welcome_message:{message:"Enjoy private and group conversations with text, photos, gifs, voice, video and more."},
chrome_app_chrome_signin_message:{message:"Sign in to Chrome to get started."},chrome_app_learn_more_message:{message:"Learn more"},chrome_app_signin_button:{message:"Sign in"},chrome_app_outdated_title:{message:"Update your Hangouts Chrome app"},chrome_app_outdated_detail:{message:"This app is out of date. There's a newer version available."},chrome_app_exit_title:{message:"Are you sure you want to quit Hangouts?"},chrome_app_exit_title_2:{message:"Do you want to quit Hangouts?"},chrome_app_exit_detail:{message:"You will not receive new messages or calls on this device"},
chrome_app_exit_detail_2:{message:"You can also choose to minimize it and continue to receive messages and calls."},chrome_app_exit_no:{message:"No"},chrome_app_exit_quit:{message:"Quit"},chrome_app_exit_minimize:{message:"Minimize"},chrome_app_osx_warning_message:{message:"Hangouts Chrome app is not fully supported on Mac OSX."},chrome_app_osx_warning_ack:{message:"OK, GOT IT"}};

}catch(e){_._DumpException(e)}
try{
var Ca,Da,Ea,Ha,Ia;Ca=function(a,b){return a<b?-1:a>b?1:0};Da={};Ea=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};_.Fa=function(){};_.Fa.prototype.next=function(){throw _.qa;};_.Fa.prototype.ha=function(){return this};_.Ga=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};Ha=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};
Ia=function(a,b){for(var c=0,d=(0,_.ha)(String(a)).split("."),e=(0,_.ha)(String(b)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var l=d[g]||"",q=e[g]||"",B=RegExp("(\\d*)(\\D*)","g"),K=RegExp("(\\d*)(\\D*)","g");do{var da=B.exec(l)||["","",""],P=K.exec(q)||["","",""];if(0==da[0].length&&0==P[0].length)break;c=Ca(0==da[1].length?0:(0,window.parseInt)(da[1],10),0==P[1].length?0:(0,window.parseInt)(P[1],10))||Ca(0==da[2].length,0==P[2].length)||Ca(da[2],P[2])}while(0==c)}return c};
_.Ja=function(a){var b=_.fa(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.v=function(a){return void 0!==a};_.Ka=function(a){return Da[a]||(Da[a]=0<=Ia(_.za,a))};_.La=function(a){if("function"==typeof a.B)return a.B();if(_.p(a))return a.split("");if(_.Ja(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ha(a)};
_.w=function(a,b){this.b={};this.a=[];this.j=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("f");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){"undefined"!=typeof _.w&&a instanceof _.w?(c=a.M(),d=a.B()):(c=_.Ga(a),d=Ha(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.w.prototype.V=function(){return this.c};_.w.prototype.B=function(){Ma(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.w.prototype.M=function(){Ma(this);return this.a.concat()};
_.Na=function(a,b){return Ea(a.b,b)};_.w.prototype.P=function(){return 0==this.c};_.w.prototype.clear=function(){this.b={};this.j=this.c=this.a.length=0};_.w.prototype.remove=function(a){return Ea(this.b,a)?(delete this.b[a],this.c--,this.j++,this.a.length>2*this.c&&Ma(this),!0):!1};
var Ma=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Ea(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],Ea(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.h=_.w.prototype;_.h.get=function(a,b){return Ea(this.b,a)?this.b[a]:b};_.h.set=function(a,b){Ea(this.b,a)||(this.c++,this.a.push(a),this.j++);this.b[a]=b};_.h.forEach=function(a,b){for(var c=this.M(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};
_.h.clone=function(){return new _.w(this)};_.h.ha=function(a){Ma(this);var b=0,c=this.a,d=this.b,e=this.j,f=this,g=new _.Fa;g.next=function(){for(;;){if(e!=f.j)throw Error("g");if(b>=c.length)throw _.qa;var g=c[b++];return a?g:d[g]}};return g};_.x=function(a){return"array"==_.fa(a)};_.Oa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};
_.y=function(a,b){function c(){}c.prototype=b.prototype;a.t=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ad=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};
_.Pa=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(_.Ja(a)||_.p(a))(0,_.s)(a,b,c);else{var d;if("function"==typeof a.M)d=a.M();else if("function"!=typeof a.B)if(_.Ja(a)||_.p(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=_.Ga(a);else d=void 0;for(var e=_.La(a),f=e.length,g=0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};_.Qa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};_.Ra=function(a,b){var c=(0,_.ia)(a,b),d;(d=0<=c)&&_.r.splice.call(a,c,1);return d};
_.Sa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.Sa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.y(_.Sa,Error);_.Sa.prototype.name="CustomError";_.Ta=function(a,b){var c=a.split("."),d=_.k;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.v(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};
_.Ua=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.Va=function(a){return"number"==typeof a};_.Wa=function(){};_.Xa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
var Ya;_.z=function(){};_.A=function(a,b,c,d){a.a={};b||(b=c?[c]:[]);a.p=c?String(c):void 0;a.b=0===c?-1:0;a.G=b;t:{if(a.G.length&&(b=a.G.length-1,(c=a.G[b])&&"object"==typeof c&&"number"!=typeof c.length)){a.j=b-a.b;a.c=c;break t}a.j=Number.MAX_VALUE}if(d)for(b=0;b<d.length;b++)c=d[b],c<a.j?(c+=a.b,a.G[c]=a.G[c]||[]):a.c[c]=a.c[c]||[]};_.C=function(a,b){return b<a.j?a.G[b+a.b]:a.c[b]};_.z.prototype.toString=function(){return this.G.toString()};_.D=function(a,b){Ya[a]=b;b.messageId=a};Ya={};
_.E=function(){this.D=this.D;this.j=this.j};_.E.prototype.D=!1;_.E.prototype.yb=function(){return this.D};_.E.prototype.C=function(){this.D||(this.D=!0,this.n())};_.G=function(a,b){_.Za(a,_.Ua(_.F,b))};_.Za=function(a,b){a.j||(a.j=[]);a.j.push(_.v(void 0)?(0,_.n)(b,void 0):b)};_.E.prototype.n=function(){if(this.j)for(;this.j.length;)this.j.shift()()};_.F=function(a){a&&"function"==typeof a.C&&a.C()};
_.$a=!_.u||_.u&&9<=_.Ba;!_.ua&&!_.u||_.u&&_.u&&9<=_.Ba||_.ua&&_.Ka("1.9.1");_.u&&_.Ka("9");var ab=function(a){ab[" "](a);return a};ab[" "]=_.Wa;_.cb=function(a,b){try{return ab(a[b]),!0}catch(c){}return!1};var db,eb;db=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;_.gb=function(a){if(eb){eb=!1;var b=_.k.location;if(b){var c=b.href;if(c&&(c=_.fb(c))&&c!=b.hostname)throw eb=!0,Error();}}return a.match(db)};eb=_.va;_.fb=function(a){return(a=_.gb(a)[3]||null)?(0,window.decodeURI)(a):a};
var hb=!_.u||_.u&&9<=_.Ba,ib=_.u&&!_.Ka("9");!_.va||_.Ka("528");_.ua&&_.Ka("1.9b")||_.u&&_.Ka("8")||_.ta&&_.Ka("9.5")||_.va&&_.Ka("528");_.ua&&!_.Ka("8")||_.u&&_.Ka("9");_.H=function(a,b){this.type=a;this.a=this.target=b;this.pc=!0};_.H.prototype.C=function(){};_.H.prototype.b=function(){this.pc=!1};var jb=function(a,b){_.H.call(this,a?a.type:"");this.a=this.target=null;this.clientY=this.clientX=0;this.c=this.state=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;c&&_.ua&&_.cb(c,"nodeName");this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.state=a.state;this.c=a;a.defaultPrevented&&this.b()}};_.y(jb,_.H); jb.prototype.b=function(){jb.t.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,ib)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var kb,mb;kb="closure_listenable_"+(1E6*Math.random()|0);_.lb=function(a){return!(!a||!a[kb])};mb=0;var nb=function(a,b,c,d,e){this.qa=a;this.proxy=null;this.src=b;this.type=c;this.Ua=!!d;this.$a=e;this.key=++mb;this.removed=this.Ta=!1},ob=function(a){a.removed=!0;a.qa=null;a.proxy=null;a.src=null;a.$a=null};var pb=function(a){this.src=a;this.a={};this.b=0};pb.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=qb(a,b,d,e);-1<g?(b=a[g],c||(b.Ta=!1)):(b=new nb(b,this.src,f,!!d,e),b.Ta=c,a.push(b));return b};pb.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=qb(e,b,c,d);return-1<b?(ob(e[b]),_.r.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var rb=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=_.Ra(a.a[c],b);d&&(ob(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d};pb.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,ob(d[e]);delete this.a[c];this.b--}return b}; var sb=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=qb(a,c,d,e));return-1<b?a[b]:null},qb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.qa==b&&f.Ua==!!c&&f.$a==d)return e}return-1};
var tb,ub,vb,Ab,Bb,Gb,Fb,Cb,zb,Hb;tb="closure_lm_"+(1E6*Math.random()|0);ub={};vb=0;_.wb=function(a,b,c,d,e){if(_.x(b)){for(var f=0;f<b.length;f++)_.wb(a,b[f],c,d,e);return null}c=_.xb(c);return _.lb(a)?a.listen(b,c,d,e):_.yb(a,b,c,!1,d,e)};_.yb=function(a,b,c,d,e,f){if(!b)throw Error("l");var g=!!e,l=zb(a);l||(a[tb]=l=new pb(a));c=l.add(b,c,d,e,f);if(c.proxy)return c;d=Ab();c.proxy=d;d.src=a;d.qa=c;a.addEventListener?a.addEventListener(b.toString(),d,g):a.attachEvent(Bb(b.toString()),d);vb++;return c};
Ab=function(){var a=Cb,b=hb?function(c){return a.call(b.src,b.qa,c)}:function(c){c=a.call(b.src,b.qa,c);if(!c)return c};return b};_.Db=function(a,b,c,d,e){if(_.x(b))for(var f=0;f<b.length;f++)_.Db(a,b[f],c,d,e);else c=_.xb(c),_.lb(a)?a.Fb(b,c,d,e):a&&(a=zb(a))&&(b=sb(a,b,c,!!d,e))&&_.Eb(b)};
_.Eb=function(a){if(_.Va(a)||!a||a.removed)return!1;var b=a.src;if(_.lb(b))return rb(b.U,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.Ua):b.detachEvent&&b.detachEvent(Bb(c),d);vb--;(c=zb(b))?(rb(c,a),0==c.b&&(c.src=null,b[tb]=null)):ob(a);return!0};Bb=function(a){return a in ub?ub[a]:ub[a]="on"+a};Gb=function(a,b,c,d){var e=1;if(a=zb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Ua==c&&!f.removed&&(e&=!1!==Fb(f,d))}return Boolean(e)};
Fb=function(a,b){var c=a.qa,d=a.$a||a.src;a.Ta&&_.Eb(a);return c.call(d,b)};
Cb=function(a,b){if(a.removed)return!0;if(!hb){var c;if(!(c=b))t:{c=["window","event"];for(var d=_.k,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break t}c=d}e=c;c=new jb(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){t:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break t}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,l=e.length-1;0<=l;l--)c.a=e[l],d&=Gb(e[l],f,!0,c);for(l=0;l<e.length;l++)c.a=e[l],d&=Gb(e[l],f,!1,c)}return d}return Fb(a, new jb(b,this))};zb=function(a){a=a[tb];return a instanceof pb?a:null};Hb="__closure_events_fn_"+(1E9*Math.random()>>>0);_.xb=function(a){if(_.ga(a))return a;a[Hb]||(a[Hb]=function(b){return a.handleEvent(b)});return a[Hb]};
_.Ib=function(a){_.A(this,a,"h_cc",[])};_.y(_.Ib,_.z);_.D("h_cc",_.Ib);_.Ib.prototype.Z=function(){return _.C(this,19)};_.I=function(a){_.E.call(this);this.I=a;this.g={}};_.y(_.I,_.E);var Jb=[];_.I.prototype.listen=function(a,b,c,d){return _.Lb(this,a,b,c,d)};_.Lb=function(a,b,c,d,e,f){_.x(c)||(c&&(Jb[0]=c.toString()),c=Jb);for(var g=0;g<c.length;g++){var l=_.wb(b,c[g],d||a.handleEvent,e||!1,f||a.I||a);if(!l)break;a.g[l.key]=l}return a};
_.I.prototype.Fb=function(a,b,c,d,e){if(_.x(b))for(var f=0;f<b.length;f++)this.Fb(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.I||this,c=_.xb(c),d=!!d,b=_.lb(a)?sb(a.U,String(b),c,d,e):a?(a=zb(a))?sb(a,b,c,d,e):null:null,b&&(_.Eb(b),delete this.g[b.key]);return this};_.I.prototype.removeAll=function(){_.Qa(this.g,_.Eb);this.g={}};_.I.prototype.n=function(){_.I.t.n.call(this);this.removeAll()};_.I.prototype.handleEvent=function(){throw Error("m");};
var Mb,Nb,Ob;Mb=function(a){_.k.setTimeout(function(){throw a;},0)};_.Pb=function(a,b){var c=a;b&&(c=(0,_.n)(a,b));!_.ga(_.k.setImmediate)||_.k.Window&&_.k.Window.prototype.setImmediate==_.k.setImmediate?(Nb||(Nb=Ob()),Nb(c)):_.k.setImmediate(c)};
Ob=function(){var a=_.k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(a=function(){var a=window.document.createElement("iframe");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.n)(function(a){if(("*"==d||a.origin==d)&&
a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&-1==_.t.indexOf("Trident")&&-1==_.t.indexOf("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.v(c.next)){c=c.next;var a=c.Rb;c.Rb=null;a()}};return function(a){d.next={Rb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("script")? function(a){var b=window.document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.k.setTimeout(a,0)}};
var Vb=function(a,b){Qb||Rb();Sb||(Qb(),Sb=!0);Tb.push(new Ub(a,b))},Qb,Rb=function(){if(_.k.Promise&&_.k.Promise.resolve){var a=_.k.Promise.resolve();Qb=function(){a.then(Wb)}}else Qb=function(){_.Pb(Wb)}},Sb=!1,Tb=[],Wb=function(){for(;Tb.length;){var a=Tb;Tb=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.a.call(c.b)}catch(d){Mb(d)}}}Sb=!1},Ub=function(a,b){this.a=a;this.b=b};
_.J=function(){_.E.call(this);this.U=new pb(this);this.L=this;this.u=null};_.y(_.J,_.E);_.J.prototype[kb]=!0;_.h=_.J.prototype;_.h.addEventListener=function(a,b,c,d){_.wb(this,a,b,c,d)};_.h.removeEventListener=function(a,b,c,d){_.Db(this,a,b,c,d)};_.h.n=function(){_.J.t.n.call(this);this.U&&this.U.removeAll(void 0);this.u=null};_.h.listen=function(a,b,c,d){return this.U.add(String(a),b,!1,c,d)};_.h.Fb=function(a,b,c,d){return this.U.remove(String(a),b,c,d)}; _.h.da=function(a,b,c){a=this.U.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.Ua==b){var g=f.qa,l=f.$a||f.src;f.Ta&&rb(this.U,f);d=!1!==g.call(l,c)&&d}}return d&&0!=c.pc};
var Xb=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},Yb=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var $b;$b=function(a,b){this.b=0;this.f=void 0;this.a=this.c=null;this.j=this.e=!1;try{var c=this;a.call(b,function(a){Zb(c,2,a)},function(a){Zb(c,3,a)})}catch(d){Zb(this,3,d)}};_.bc=function(){var a,b=new $b(function(b){a=b});return new ac(b,a)};$b.prototype.then=function(a,b,c){return cc(this,_.ga(a)?a:null,_.ga(b)?b:null,c)};Xb($b);
var fc=function(a){0==a.b&&Vb(function(){var a=new dc(void 0);ec(this,a)},a)},ec=function(a,b){if(0==a.b)if(a.c){var c=a.c;if(c.a){for(var d=0,e=-1,f=0,g;g=c.a[f];f++)if(g=g.Ea)if(d++,g==a&&(e=f),0<=e&&1<d)break;0<=e&&(0==c.b&&1==d?ec(c,b):(d=c.a.splice(e,1)[0],gc(c,d,3,b)))}}else Zb(a,3,b)},ic=function(a,b){a.a&&a.a.length||2!=a.b&&3!=a.b||hc(a);a.a||(a.a=[]);a.a.push(b)},cc=function(a,b,c,d){var e={Ea:null,jc:null,lc:null};e.Ea=new $b(function(a,g){e.jc=b?function(c){try{var e=b.call(d,c);a(e)}catch(B){g(B)}}:
a;e.lc=c?function(b){try{var e=c.call(d,b);!_.v(e)&&b instanceof dc?g(b):a(e)}catch(B){g(B)}}:g});e.Ea.c=a;ic(a,e);return e.Ea};$b.prototype.g=function(a){this.b=0;Zb(this,2,a)};$b.prototype.h=function(a){this.b=0;Zb(this,3,a)};
var Zb=function(a,b,c){if(0==a.b){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(Yb(c)){a.b=1;c.then(a.g,a.h,a);return}if(_.Oa(c))try{var d=c.then;if(_.ga(d)){jc(a,c,d);return}}catch(e){b=3,c=e}}a.f=c;a.b=b;hc(a);3!=b||c instanceof dc||kc(a,c)}},jc=function(a,b,c){a.b=1;var d=!1,e=function(b){d||(d=!0,a.g(b))},f=function(b){d||(d=!0,a.h(b))};try{c.call(b,e,f)}catch(g){f(g)}},hc=function(a){a.e||(a.e=!0,Vb(a.k,a))};
$b.prototype.k=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;b++)gc(this,a[b],this.b,this.f)}this.e=!1};var gc=function(a,b,c,d){if(2==c)b.jc(d);else{if(b.Ea)for(;a&&a.j;a=a.c)a.j=!1;b.lc(d)}},kc=function(a,b){a.j=!0;Vb(function(){a.j&&lc.call(null,b)})},lc=Mb,dc=function(a){_.Sa.call(this,a)};_.y(dc,_.Sa);dc.prototype.name="cancel";var ac=function(a,b){this.b=a;this.a=b};
var mc,nc,oc,pc,qc,rc,sc,vc,wc,xc,yc,zc,Ac;sc=rc=qc=pc=oc=nc=mc=!1;var tc=_.t;tc&&(-1!=tc.indexOf("Firefox")?mc=!0:-1!=tc.indexOf("Camino")?nc=!0:-1!=tc.indexOf("iPad")?pc=!0:-1!=tc.indexOf("iPhone")||-1!=tc.indexOf("iPod")?oc=!0:-1!=tc.indexOf("Chrome")?rc=!0:-1!=tc.indexOf("Android")?qc=!0:-1!=tc.indexOf("Safari")&&(sc=!0));_.uc=mc;vc=nc;wc=oc;xc=pc;yc=qc;zc=rc;Ac=sc;
_.L=function(a){this.a=a};_.L.prototype.toString=function(){return this.a};_.Bc=new _.L("fJuxOc");_.Cc=new _.L("ZtVrH");_.Dc=new _.L("zZa4xc");_.Ec=new _.L("pVbxBc");_.Fc=new _.L("byfTOb");_.Gc=new _.L("LEikZe");_.Hc=new _.L("rJmJrc");_.Ic=new _.L("a");_.Jc=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")};_.Kc=function(){return 0<=window.navigator.userAgent.indexOf("CrOS")};_.Lc=function(a,b){this.j=a||"e";this.c=null!=a&&"p"==a?"e":"p";this.b=this.e=null;this.h=b||"u";this.a=this.g=null;this.f=[]};_.Lc.prototype.message=function(){var a={};a.i=this.a;a.m=this.f;a.r=this.h;a.o=this.g;a.s=this.b;a.st=this.c;a.d=this.e;a.dt=this.j;return a};_.Ta("ace.base.Message.prototype.message",_.Lc.prototype.message);
_.Mc=function(a,b){for(var c in b)switch(c){case "r":a.h=b[c];break;case "i":a.a=b[c];break;case "m":a.f=b[c];break;case "o":a.g=b[c];break;case "s":a.b=b[c];break;case "d":a.e=b[c];break;case "st":a.c=b[c];break;case "dt":a.j=b[c]}return a};_.Nc=function(a,b,c){null!=b&&(a.b=b,null!=c&&(a.c=c))};_.Oc=function(a,b){null!=b&&(a.a=b)};_.Pc=function(a,b){"object"==typeof b?a.f=b:a.f=[b]};_.Lc.prototype.source=function(){return this.b};_.Lc.prototype.target=function(){return this.e}; _.Lc.prototype.content=function(){return this.f};
_.Qc=function(a,b,c,d,e){_.E.call(this);this.b=a;this.Qa=b;this.a=typeof b;this.Ab=c?c:!1;this.ba=!0;this.wb=d?d:!1;this.pb=e?e:!1};_.y(_.Qc,_.E);_.h=_.Qc.prototype;_.h.n=function(){_.Qc.t.n.call(this);this.b="";this.Qa=null;this.a=""};_.h.id=function(){return this.b};_.h.type=function(){return this.a};_.h.F=function(){return this.Qa};_.h.setEnabled=function(a){this.ba=a};
var Rc=function(a){return(a=a.exec(_.t))?a[1]:""},Sc=function(){if(_.uc)return Rc(/Firefox\/([0-9.]+)/);if(_.u||_.ta)return _.za;if(zc)return Rc(/Chrome\/([0-9.]+)/);if(Ac)return Rc(/Version\/([0-9.]+)/);if(wc||xc){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.t))return a[1]+"."+a[2]}else{if(yc)return(a=Rc(/Android\s+([0-9.]+)/))?a:Rc(/Version\/([0-9.]+)/);if(vc)return Rc(/Camino\/([0-9.]+)/)}return""}();
_.Uc=function(a){_.E.call(this);this.a=new _.w;this.b=["https://talkgadget.google.com/talkgadget/notifier-js","","https://test.talkgadget.google.com/talkgadget/notifier-js?jsmode=debug_unobfuscated"];a&&_.Tc(this,a)};_.y(_.Uc,_.E);_.Vc=0<=Ia(Sc,"23.0.1262.0")&&!_.Kc();_.Uc.prototype.n=function(){_.Uc.t.n.call(this);for(var a=this.a.M(),b=0;b<a.length;++b)_.F(this.a.get(a[b]));delete this.a};_.Uc.prototype.getItem=function(a){return _.Na(this.a,a)?this.a.get(a):null};
_.Uc.prototype.setItem=function(a){this.a.set(a.id(),a)};_.Tc=function(a,b){for(var c in b){var d=b[c],e=null;_.Na(a.a,c)?(e=a.a.get(c),e.Qa=d.value,d.changed&&(e.pb=d.changed)):(e=new _.Qc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
_.Yc=function(){this.c=new _.w;this.a=null;this.b=!1;this.a=new Wc;this.b=!0;_.Xc(this)};_.Yc.ua=function(){return _.Yc.a?_.Yc.a:_.Yc.a=new _.Yc};_.Xc=function(a,b){var c=b||_.Wa;a.b?c():window.chrome.storage.local.get((0,_.n)(function(a){if(!this.b){for(var b in a)this.c.set(b,a[b]);this.b=!0}c()},a))};_.Yc.prototype.get=function(a){return this.a.get(a)};_.Yc.prototype.set=function(a,b){var c=_.bc();this.a.set(a,b);c.a(void 0);return c.b};_.Yc.prototype.remove=function(a){this.a.remove(a)};
_.Yc.prototype.clear=function(){this.a.clear()};var Wc=function(){this.a=window.localStorage};Wc.prototype.clear=function(){this.a.clear()};Wc.prototype.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=Ya[a[0]];if(!b)throw Error("i`"+a[0]);a=new b(a)}}else a=null;return a};Wc.prototype.set=function(a,b){var c=null;b instanceof _.z&&(b=b.G,c="jspb");var d={};d.data=b;d.timestamp=(0,_.m)();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}}; Wc.prototype.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
_.Zc=function(a,b){this.b=a;this.a=b;this.constructor.Pb||(this.constructor.Pb={});this.constructor.Pb[this.toString()]=this};_.Zc.prototype.toString=function(){this.c||(this.c=this.b.a+":"+this.a);return this.c};_.M=function(a,b){_.Zc.call(this,a,b)};_.y(_.M,_.Zc);_.$c=function(a){this.a=a};_.ad=new _.$c("lib");/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.bd=function(a,b){this.j=[];this.u=b||null;this.b=this.a=!1;this.c=void 0;this.l=this.p=this.f=!1;this.e=0;this.h=null;this.q=0};_.bd.prototype.k=function(a,b){this.f=!1;_.cd(this,a,b)};_.cd=function(a,b,c){a.a=!0;a.c=c;a.b=!b;dd(a)};_.fd=function(a){if(a.a){if(!a.l)throw new ed;a.l=!1}};_.bd.prototype.g=function(a){_.fd(this);_.cd(this,!0,a)};_.gd=function(a,b,c,d){a.j.push([b,c,d]);a.a&&dd(a)};
_.bd.prototype.then=function(a,b,c){var d,e,f=new $b(function(a,b){d=a;e=b});_.gd(this,d,function(a){"undefined"!=typeof _.hd&&a instanceof _.hd?fc(f):e(a)});return f.then(a,b,c)};Xb(_.bd);
var id=function(a){return(0,_.pa)(a.j,function(a){return _.ga(a[1])})},dd=function(a){if(a.e&&a.a&&id(a)){var b=a.e,c=jd[b];c&&(_.k.clearTimeout(c.Wa),delete jd[b]);a.e=0}a.h&&(a.h.q--,delete a.h);for(var b=a.c,d=c=!1;a.j.length&&!a.f;){var e=a.j.shift(),f=e[0],g=e[1],e=e[2];if(f=a.b?g:f)try{var l=f.call(e||a.u,b);_.v(l)&&(a.b=a.b&&(l==b||l instanceof Error),a.c=b=l);Yb(b)&&(d=!0,a.f=!0)}catch(q){b=q,a.b=!0,id(a)||(c=!0)}}a.c=b;d&&(l=(0,_.n)(a.k,a,!0),d=(0,_.n)(a.k,a,!1),b instanceof _.bd?(_.gd(b,
l,d),b.p=!0):b.then(l,d));c&&(b=new kd(b),jd[b.Wa]=b,a.e=b.Wa)},ed=function(){_.Sa.call(this)};_.y(ed,_.Sa);ed.prototype.message="Deferred has already fired";ed.prototype.name="AlreadyCalledError";var kd=function(a){this.Wa=_.k.setTimeout((0,_.n)(this.b,this),0);this.a=a};kd.prototype.b=function(){delete jd[this.Wa];throw this.a;};var jd={};

}catch(e){_._DumpException(e)}
try{
var ud,vd,wd,xd,yd,zd,Gd,Hd,Md,Ld,Pd,Qd,Rd,Sd,Td,Ud,Vd,$d,he;ud={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};vd=function(a,b){b.push('"',a.replace(_.Xa,function(a){if(a in ud)return ud[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return ud[a]=e+b.toString(16)}),'"')};
wd=function(a,b,c){switch(typeof b){case "string":vd(b,c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(_.x(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),wd(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],"function"!=typeof f&&(c.push(d),vd(e,c),c.push(":"),
wd(a,f,c),d=","));c.push("}");break;case "function":break;default:throw Error("h`"+typeof b);}};xd=function(){};yd="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");zd=function(a,b,c,d,e){if(_.x(b)){for(var f=0;f<b.length;f++)zd(a,b[f],c,d,e);return null}c=_.xb(c);return _.lb(a)?a.U.add(String(b),c,!0,d,e):_.yb(a,b,c,!0,d,e)};_.N=function(a,b,c){b<a.j?a.G[b+a.b]=c:a.c[b]=c};_.Ad=function(a){var b=[];wd(new xd,a,b);return b.join("")};
_.Bd=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<yd.length;f++)c=yd[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};_.Cd=function(a,b,c){null!=b&&(a.e=b,null!=c&&(a.j=c))};
_.O=function(a,b){var c,d=a.u;if(d)for(c=[];d;d=d.u)c.push(d);var d=a.L,e=b,f=e.type||e;if(_.p(e))e=new _.H(e,d);else if(e instanceof _.H)e.target=e.target||d;else{var g=e,e=new _.H(f,d);_.Bd(e,g)}var g=!0,l;if(c)for(var q=c.length-1;0<=q;q--)l=e.a=c[q],g=l.da(f,!0,e)&&g;l=e.a=d;g=l.da(f,!0,e)&&g;g=l.da(f,!1,e)&&g;if(c)for(q=0;q<c.length;q++)l=e.a=c[q],g=l.da(f,!1,e)&&g};
_.Ed=function(a,b,c,d,e,f){if(_.x(c))for(var g=0;g<c.length;g++)_.Ed(a,b,c[g],d,e,f);else{b=zd(b,c,d||a.handleEvent,e,f||a.I||a);if(!b)return a;a.g[b.key]=b}return a};_.Fd=function(a,b,c){var d=c?c.G:c;a.a[b]=c;_.N(a,b,d)};_.Q=function(a,b,c){if(!a.a[c]){var d=_.C(a,c);d&&(a.a[c]=new b(d))}return a.a[c]};Gd=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};Hd=function(a,b){return a?b?(0,window.decodeURI)(a):(0,window.decodeURIComponent)(a):""};
_.Id=function(a){return _.r.concat.apply(_.r,arguments)};_.Jd=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};_.Kd=function(a,b,c){this.a=a||null;this.b=!!c};
Md=function(a){if(!a.H&&(a.H=new _.w,a.O=0,a.a))for(var b=a.a.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),e=null,f=null;0<=d?(e=b[c].substring(0,d),f=b[c].substring(d+1)):e=b[c];e=(0,window.decodeURIComponent)(e.replace(/\+/g," "));e=Ld(a,e);a.add(e,f?(0,window.decodeURIComponent)(f.replace(/\+/g," ")):"")}};_.h=_.Kd.prototype;_.h.H=null;_.h.O=null;_.h.V=function(){Md(this);return this.O};
_.h.add=function(a,b){Md(this);this.a=null;a=Ld(this,a);var c=this.H.get(a);c||this.H.set(a,c=[]);c.push(b);this.O++;return this};_.h.remove=function(a){Md(this);a=Ld(this,a);return _.Na(this.H,a)?(this.a=null,this.O-=this.H.get(a).length,this.H.remove(a)):!1};_.h.clear=function(){this.H=this.a=null;this.O=0};_.h.P=function(){Md(this);return 0==this.O};var Nd=function(a,b){Md(a);b=Ld(a,b);return _.Na(a.H,b)};
_.Kd.prototype.M=function(){Md(this);for(var a=this.H.B(),b=this.H.M(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};_.Kd.prototype.B=function(a){Md(this);var b=[];if(_.p(a))Nd(this,a)&&(b=_.Id(b,this.H.get(Ld(this,a))));else{a=this.H.B();for(var c=0;c<a.length;c++)b=_.Id(b,a[c])}return b};_.Kd.prototype.set=function(a,b){Md(this);this.a=null;a=Ld(this,a);Nd(this,a)&&(this.O-=this.H.get(a).length);this.H.set(a,[b]);this.O++;return this};
_.Kd.prototype.get=function(a,b){var c=a?this.B(a):[];return 0<c.length?String(c[0]):b};_.Od=function(a,b,c){a.remove(b);0<c.length&&(a.a=null,a.H.set(Ld(a,b),_.Jd(c)),a.O+=c.length)};_.Kd.prototype.toString=function(){if(this.a)return this.a;if(!this.H)return"";for(var a=[],b=this.H.M(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.B(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(g)}return this.a=a.join("&")};
_.Kd.prototype.clone=function(){var a=new _.Kd;a.a=this.a;this.H&&(a.H=this.H.clone(),a.O=this.O);return a};Ld=function(a,b){var c=String(b);a.b&&(c=c.toLowerCase());return c};Pd=function(a,b){b&&!a.b&&(Md(a),a.a=null,a.H.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),_.Od(this,e,a))},a));a.b=b};Qd=/#/g;Rd=/[\#\?@]/g;Sd=/[\#\?]/g;Td=/[\#\?:]/g;Ud=/[#\/\?@]/g;
Vd=function(a,b,c){return _.p(a)?(a=(0,window.encodeURI)(a).replace(b,Gd),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};_.Wd=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.m)()).toString(36)};
_.Xd=function(a,b){var c;"undefined"!=typeof _.Xd&&a instanceof _.Xd?(this.ma=_.v(b)?b:a.ma,_.Yd(this,a.fa),this.sa=a.sa,this.R=a.R,_.Zd(this,a.ea),this.N=a.N,$d(this,a.a.clone()),this.la=a.la):a&&(c=_.gb(String(a)))?(this.ma=!!b,_.Yd(this,c[1]||"",!0),this.sa=Hd(c[2]||""),this.R=Hd(c[3]||"",!0),_.Zd(this,c[4]),this.N=Hd(c[5]||"",!0),$d(this,c[6]||"",!0),this.la=Hd(c[7]||"")):(this.ma=!!b,this.a=new _.Kd(null,0,this.ma))};_.h=_.Xd.prototype;_.h.fa="";_.h.sa="";_.h.R="";_.h.ea=null;_.h.N="";
_.h.la="";_.h.ma=!1;_.h.toString=function(){var a=[],b=this.fa;b&&a.push(Vd(b,Ud,!0),":");if(b=this.R){a.push("//");var c=this.sa;c&&a.push(Vd(c,Ud,!0),"@");a.push((0,window.encodeURIComponent)(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.ea;null!=b&&a.push(":",String(b))}if(b=this.N)this.R&&"/"!=b.charAt(0)&&a.push("/"),a.push(Vd(b,"/"==b.charAt(0)?Sd:Td,!0));(b=this.a.toString())&&a.push("?",b);(b=this.la)&&a.push("#",Vd(b,Qd));return a.join("")};
_.ae=function(a,b){var c=a.clone(),d=!!b.fa;d?_.Yd(c,b.fa):d=!!b.sa;d?c.sa=b.sa:d=!!b.R;d?c.R=b.R:d=null!=b.ea;var e=b.N;if(d)_.Zd(c,b.ea);else if(d=!!b.N){if("/"!=e.charAt(0))if(a.R&&!a.N)e="/"+e;else{var f=c.N.lastIndexOf("/");-1!=f&&(e=c.N.substr(0,f+1)+e)}f=e;if(".."==f||"."==f)e="";else if(-1!=f.indexOf("./")||-1!=f.indexOf("/.")){for(var e=0==f.lastIndexOf("/",0),f=f.split("/"),g=[],l=0;l<f.length;){var q=f[l++];"."==q?e&&l==f.length&&g.push(""):".."==q?((1<g.length||1==g.length&&""!=g[0])&&
g.pop(),e&&l==f.length&&g.push("")):(g.push(q),e=!0)}e=g.join("/")}else e=f}d?c.N=e:d=""!==b.a.toString();d?$d(c,Hd(b.a.toString())):d=!!b.la;d&&(c.la=b.la);return c};_.Xd.prototype.clone=function(){return new _.Xd(this)};_.Yd=function(a,b,c){a.fa=c?Hd(b,!0):b;a.fa&&(a.fa=a.fa.replace(/:$/,""))};_.Zd=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("j`"+b);a.ea=b}else a.ea=null};$d=function(a,b,c){b instanceof _.Kd?(a.a=b,Pd(a.a,a.ma)):(c||(b=Vd(b,Rd)),a.a=new _.Kd(b,0,a.ma))};
_.R=function(a,b,c){a.a.set(b,c)};_.be=function(a,b,c){_.x(c)||(c=[String(c)]);_.Od(a.a,b,c)};_.ce=function(a,b){return a.a.get(b)};_.de=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};_.ee=function(a,b){return 0<=(0,_.ia)(a,b)};
_.fe=function(a,b,c){if(_.ga(a))c&&(a=(0,_.n)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.n)(a.handleEvent,a);else throw Error("n");return 2147483647<b?-1:_.k.setTimeout(a,b||0)};_.ge=function(a){_.k.clearTimeout(a)};he=function(a){var b=arguments.length;if(1==b&&_.x(arguments[0]))return he.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};_.ie=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
_.je=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c],e;if(_.x(d)||(e=_.Ja(d))&&Object.prototype.hasOwnProperty.call(d,"callee"))a.push.apply(a,d);else if(e)for(var f=a.length,g=d.length,l=0;l<g;l++)a[f+l]=d[l];else a.push(d)}};_.ke=function(a,b){var c;t:{c=a.length;for(var d=_.p(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break t}c=-1}return 0>c?null:_.p(a)?a.charAt(c):a[c]};
he("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));he("action","cite","data","formaction","href","manifest","poster","src");he("embed","iframe","link","script","style","template");var oe,me,ne,pe;_.le=function(){};oe=function(a){var b=a.ia,c=function(a){c.t.constructor.call(this,a);var b=this.T.length;this.a=[];for(var d=0;d<b;++d)this.T[d].Cd||(this.a[d]=new this.T[d](a))};_.y(c,b);for(var d=[];a;){if(b=a.ia){b.T&&_.je(d,b.T);var b=b.prototype,e;for(e in b)if(b.hasOwnProperty(e)&&_.ga(b[e])&&b[e]!==a){var f=!!b[e].Mc,g=me(e,b,d,f);(f=ne(e,b,g,f))&&(c.prototype[e]=f)}}a=a.t&&a.t.constructor}c.prototype.T=d;return c};
me=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||(e.push(f),!d));++f);return e};
ne=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.T[c[0]].prototype[a].apply(this,arguments)}:b[a].Oc?e=function(b){var d;t:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var q=this.a[c[e]];if(q=q?q[a].apply(q,d):this.T[c[e]].prototype[a].apply(this,d)){d=q;break t}}d=!1}return d}:b[a].Nc?e=function(b){var d;t:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var q=this.a[c[e]],q=q?q[a].apply(q,
d):this.T[c[e]].prototype[a].apply(this,d);if(null!=q){d=q;break t}}d=void 0}return d}:b[a].hc?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var q=this.a[c[e]];q?q[a].apply(q,d):this.T[c[e]].prototype[a].apply(this,d)}}:e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],q=0;q<c.length;++q){var B=this.a[c[q]];e.push(B?B[a].apply(B,d):this.T[c[q]].prototype[a].apply(this,d))}return e}:d||b[a].Oc||b[a].Nc||b[a].hc?e=null:e=pe;return e};pe=function(){return[]}; _.le.prototype.tb=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};
var qe;_.re=function(a){if(!a.qb){var b;for(b=a.constructor;b&&!b.ia;)b=b.t&&b.t.constructor;b.ia.Ub||(b.ia.Ub=oe(b));b=new b.ia.Ub(a);a.qb=b;a.tb||(a.tb=qe)}};qe=function(a){return this.qb.tb(a)};var se=function(){};se.prototype.a=null;var ue=function(a){var b;(b=a.a)||(b={},te(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var ve,we=function(){};_.y(we,se);var xe=function(a){return(a=te(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},te=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("t");}return a.b};ve=new we;
var ze,Ce,He,Je,Ie,Ee;_.ye=function(a){_.J.call(this);this.A=new _.w;this.k=a||null;this.b=!1;this.h=this.a=null;this.q="";this.e=0;this.c=this.p=this.f=this.l=!1;this.v=0;this.g=null;this.I="";this.w=this.aa=!1};_.y(_.ye,_.J);ze=/^https?$/i;_.Ae=["POST","PUT"];_.Be=[];_.ye.prototype.S=function(){this.C();_.Ra(_.Be,this)};
_.ye.prototype.send=function(a,b,c,d){if(this.a)throw Error("u`"+this.q+"`"+a);b=b?b.toUpperCase():"GET";this.q=a;this.e=0;this.l=!1;this.b=!0;this.a=this.k?xe(this.k):xe(ve);this.h=this.k?ue(this.k):ue(ve);this.a.onreadystatechange=(0,_.n)(this.J,this);try{this.p=!0,this.a.open(b,String(a),!0),this.p=!1}catch(e){Ce(this);return}a=c||"";var f=this.A.clone();d&&_.Pa(d,function(a,b){f.set(b,a)});d=_.ke(f.M(),De);c=_.k.FormData&&a instanceof _.k.FormData;!_.ee(_.Ae,b)||d||c||f.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
f.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.I&&(this.a.responseType=this.I);"withCredentials"in this.a&&(this.a.withCredentials=this.aa);try{Ee(this),0<this.v&&((this.w=Fe(this.a))?(this.a.timeout=this.v,this.a.ontimeout=(0,_.n)(this.K,this)):this.g=_.fe(this.K,this.v,this)),this.f=!0,this.a.send(a),this.f=!1}catch(g){Ce(this)}};var Fe=function(a){return _.u&&_.Ka(9)&&_.Va(a.timeout)&&_.v(a.ontimeout)},De=function(a){return"content-type"==a.toLowerCase()};
_.ye.prototype.K=function(){"undefined"!=typeof _.aa&&this.a&&(this.e=8,_.O(this,"timeout"),_.Ge(this,8))};Ce=function(a){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);a.e=5;He(a);Ie(a)};He=function(a){a.l||(a.l=!0,_.O(a,"complete"),_.O(a,"error"))};_.Ge=function(a,b){a.a&&a.b&&(a.b=!1,a.c=!0,a.a.abort(),a.c=!1,a.e=b||7,_.O(a,"complete"),_.O(a,"abort"),Ie(a))};_.ye.prototype.n=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),Ie(this,!0));_.ye.t.n.call(this)};
_.ye.prototype.J=function(){this.D||(this.p||this.f||this.c?Je(this):this.W())};_.ye.prototype.W=function(){Je(this)};Je=function(a){if(a.b&&"undefined"!=typeof _.aa&&(!a.h[1]||4!=(a.a?a.a.readyState:0)||2!=_.Ke(a)))if(a.f&&4==(a.a?a.a.readyState:0))_.fe(a.J,0,a);else if(_.O(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{_.Le(a)?(_.O(a,"complete"),_.O(a,"success")):(a.e=6,He(a))}finally{Ie(a)}}};
Ie=function(a,b){if(a.a){Ee(a);var c=a.a,d=a.h[0]?_.Wa:null;a.a=null;a.h=null;b||_.O(a,"ready");try{c.onreadystatechange=d}catch(e){}}};Ee=function(a){a.a&&a.w&&(a.a.ontimeout=null);_.Va(a.g)&&(_.ge(a.g),a.g=null)};
_.Le=function(a){var b=_.Ke(a),c;t:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break t;default:c=!1}if(!c){if(b=0===b)a=_.gb(String(a.q))[1]||null,!a&&window.self.location&&(a=window.self.location.protocol,a=a.substr(0,a.length-1)),b=!ze.test(a?a.toLowerCase():"");c=b}return c};_.Ke=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}};_.Me=function(a){try{return a.a?a.a.responseText:""}catch(b){return""}};
_.Ne=function(a){_.A(this,a,"h_icr",[])};_.y(_.Ne,_.z);_.D("h_icr",_.Ne);_.Oe=function(a){_.A(this,a,"h_cs",[])};_.y(_.Oe,_.z);_.D("h_cs",_.Oe);_.Oe.prototype.getState=function(){return _.C(this,1)};_.Pe=new _.L("HwdKC");
}catch(e){_._DumpException(e)}
try{
_.Hh=function(a){for(var b=a.a.M(),c={},d=0;d<b.length;d++){var e=b[d],f=a.a.get(e);c[e]={value:f.F(),type:f.type(),multiple:f.Ab,disabled:!f.ba,inverse:f.wb,changed:f.pb}}return c};_.Ih=function(a,b){return _.p(b)?a.getElementById(b):b};_.S=function(a){return _.Ih(window.document,a)}; _.T=function(a){var b;b=b||[];b.length||(b[0]="");var c=window.chrome.i18n.getMessage(a,b);if(c)return c;(c=(c=_.k.ace_i18n[a.toLowerCase()])?c.message:_.k.ace_i18n["MSG_"+a])&&(c=c.replace("$1",b[0]).replace("$2",b[1]).replace("$3",b[2]));return c};

}catch(e){_._DumpException(e)}
try{
var Jh,Kh,Lh,Mh,Nh,Ph,Rh,Sh,Th,Uh,Vh,Wh,Xh,Yh,Zh,$h,ai,ci,di,ei,ki,mi,oi;Jh=function(a){return a.b[0]};Kh=function(a){return(a=a.a.get("TopMost"))&&a.ba?a.F():!0};Lh=function(){return!0};Mh={};Nh=0;_.Oh=function(a){a&&a!=window.chrome.windows.WINDOW_ID_NONE&&window.chrome.windows.update(a,{focused:!0})};Ph=function(a){if(Mh[a])return Mh[a];a=String(a);if(!Mh[a]){var b=/function ([^\(]+)/.exec(a);Mh[a]=b?b[1]:"[Anonymous]"}return Mh[a]};_.Qh=function(a){return a[_.ba]||(a[_.ba]=++Nh)};
Rh=function(a){window.chrome.windows.getAll({populate:!0},function(b){for(var c=0;c<b.length;++c){var d=b[c].tabs;if(null!=d)for(var e=0;e<d.length;++e)if(d[e].selected&&d[e].url==a){_.Oh(b[c].id);return}}})};Sh=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};Th=function(){return null!=window.navigator.platform.match(/Mac.*/)};Uh=function(){return!_.Kc()&&null!=window.navigator.platform.match(/Linux.*/)};Vh=function(a){this.a=a||_.k.document||window.document};
Vh.prototype.Zb=function(){var a=this.a;return a.parentWindow||a.defaultView};Vh.prototype.contains=_.de;
Wh=function(a,b){var c=[];if(_.ee(b,a))c.push("[...circular reference...]");else if(a&&50>b.length){c.push(Ph(a)+"(");for(var d=a.arguments,e=0;d&&e<d.length;e++){0<e&&c.push(", ");var f;f=d[e];switch(typeof f){case "object":f=f?"object":"null";break;case "string":break;case "number":f=String(f);break;case "boolean":f=f?"true":"false";break;case "function":f=(f=Ph(f))?f:"[fn]";break;default:f=typeof f}40<f.length&&(f=f.substr(0,40)+"...");c.push(f)}b.push(a);c.push(")\n");try{c.push(Wh(a.caller,b))}catch(g){c.push("[exception trying to get caller]\n")}}else a?
c.push("[...long stack...]"):c.push("[end]");return c.join("")};Xh=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+_.Qh(a):b.substr(0,1)+a};Yh=function(a){if(a instanceof _.Fa)return a;if("function"==typeof a.ha)return a.ha(!1);if(_.Ja(a)){var b=0,c=new _.Fa;c.next=function(){for(;;){if(b>=a.length)throw _.qa;if(b in a)return a[b++];b++}};return c}throw Error("e");};Zh=function(a,b){return a>b?1:a<b?-1:0};
$h=function(a,b){null!=a&&(window.open(a,"winid_"+(new Date).getTime(),b),_.fe((0,_.n)(Rh,null,a),1E3))};ai=function(a){null!=a&&(a=window.chrome.runtime.getURL("images_4/"+a));return a};_.bi=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};_.bi.prototype.clone=function(){return new _.bi(this.left,this.top,this.width,this.height)};
_.bi.prototype.contains=function(a){return"undefined"!=typeof _.bi&&a instanceof _.bi?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};_.bi.prototype.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
_.bi.prototype.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};ci=[/^https?:\/\/.*.google.com(:[0-9]+)?\/talkgadget\/success/,/^https:\/\/accounts.google.com\/ServiceLogin/];di=[1E4,12E4,144E5];ei=[200,2E3,3E5];_.U=function(a){return _.U.b(a)};_.U.b=function(a){return a+"_"};_.U.g=function(){throw Error("o");};
_.U.e=function(a){if(a&&a.constructor&&a.constructor.toString()===Object.toString()){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[_.U.b(c)]=a[c]);return b}throw Error("p");};_.U.c=!0;_.U.j=function(a){return a};_.U.f=function(){return!0};_.fi=function(a,b){_.J.call(this);this.c=a||1;this.b=b||_.k;this.f=(0,_.n)(this.h,this);this.g=(0,_.m)()};_.y(_.fi,_.J);_.fi.prototype.e=!1;_.fi.prototype.a=null;_.fi.prototype.setInterval=function(a){this.c=a;this.a&&this.e?(this.stop(),_.gi(this)):this.a&&this.stop()};
_.fi.prototype.h=function(){if(this.e){var a=(0,_.m)()-this.g;0<a&&a<.8*this.c?this.a=this.b.setTimeout(this.f,this.c-a):(this.a&&(this.b.clearTimeout(this.a),this.a=null),_.O(this,"tick"),this.e&&(this.a=this.b.setTimeout(this.f,this.c),this.g=(0,_.m)()))}};_.gi=function(a){a.e=!0;a.a||(a.a=a.b.setTimeout(a.f,a.c),a.g=(0,_.m)())};_.fi.prototype.stop=function(){this.e=!1;this.a&&(this.b.clearTimeout(this.a),this.a=null)};_.fi.prototype.n=function(){_.fi.t.n.call(this);this.stop();delete this.b};
var hi=function(a,b){this.width=a;this.height=b};hi.prototype.clone=function(){return new hi(this.width,this.height)};hi.prototype.P=function(){return!(this.width*this.height)};hi.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};hi.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};_.ii=function(a,b,c){c=c||[];for(var d=[],e=0;e<c.length;e++)d[e]=c[e].G;a.a[b]=c;_.N(a,b,d)};
_.ji=function(a,b,c){if(!a.a[c]){for(var d=_.C(a,c),e=[],f=0;f<d.length;f++)e[f]=new b(d[f]);a.a[c]=e}return a.a[c]};ki=function(a){var b;b||(b=Wh(a||arguments.callee.caller,[]));return b};_.li=function(a){this.a=new _.w;if(a){a=_.La(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])}};_.h=_.li.prototype;_.h.V=function(){return this.a.V()};_.h.add=function(a){this.a.set(Xh(a),a)};_.h.removeAll=function(a){a=_.La(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};_.h.remove=function(a){return this.a.remove(Xh(a))};
_.h.clear=function(){this.a.clear()};_.h.P=function(){return this.a.P()};_.h.contains=function(a){return _.Na(this.a,Xh(a))};_.h.B=function(){return this.a.B()};_.h.clone=function(){return new _.li(this)};_.h.ha=function(){return this.a.ha(!1)};mi=function(a,b){if(_.Ja(a))try{(0,_.s)(a,b,void 0)}catch(c){if(c!==_.qa)throw c;}else{a=Yh(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(d){if(d!==_.qa)throw d;}}};_.ni=function(a,b){a.sort(b||Zh)}; oi=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;return b};
var pi=function(a){_.A(this,a,"dpgi",[])};_.y(pi,_.z);_.D("dpgi",pi);var qi=function(a){_.A(this,a,"dri",[])};_.y(qi,_.z);_.D("dri",qi);_.ri=function(a){_.A(this,a,"di",[6,7,10,11,12])};_.y(_.ri,_.z);_.D("di",_.ri);_.si=function(a){_.A(this,a,"e",[])};_.y(_.si,_.z);_.D("e",_.si);_.ti=function(a){_.A(this,a,"f.ri",[])};_.y(_.ti,_.z);_.D("f.ri",_.ti);var ui=function(){_.E.call(this)},vi;_.y(ui,_.E);
_.xi=function(a,b){var c=vi;if(!(c.D||"undefined"!=typeof _.hd&&b instanceof _.hd))if(c.b){var c=c.b,d=wi();d["call-stack"]=ki();a&&(d.message=a);var e;b instanceof Error?e=b:e=b||"";var f,g="";e&&(g=(e.lineNumber||"unknown")+":"+oi(e.fileName||"unknown")+":"+oi(e.message||"unknown"));var l="";for(f in d){var q;q="call-stack"==f?d[f].replace(/\(.*\)/g,""):d[f];l=l+f+":"+q+":"}f=g+"::"+l;g=c.c[f];g||(g={time:0,count:0},c.c[f]=g);if(1E4>(0,_.m)()-g.time)g.count++,1==g.count&&(d=wi(),d.message="Throttling: "+ f,c.a.a(e,d));else{g.count&&(d["dropped-instances"]=g.count);g.time=(0,_.m)();for(f=g.count=0;f<c.b.length;f++)c.b[f](e,d);c.a.a(e,d)}}else c.a&&10>c.a.length&&c.a.push([a,b])};vi=new ui;
_.yi=function(a){var b=window;if(!b.location){var c;try{c=_.Ad(b)}catch(d){c=_.Ga(b).toString()}_.xi(null,Error("x`"+c))}c=b.location&&b.location.ancestorOrigins;if(_.v(c))return c&&c.length?c[a?0:c.length-1]==b.location.origin:!0;try{return _.v((a?b.parent:b.top).location.href)}catch(e){return!1}};
var zi={},wi=function(){var a={};a.location=window.document.location.toString();if(_.yi(!1))try{a["top.location"]=window.top.location.toString()}catch(b){a["top.location"]="[external]"}else a["top.location"]="[external]";for(var c in zi)try{a[c]=zi[c].call()}catch(d){a[c]="[error] "+d.message}return a};
var Ai={},Bi=function(){delete Ai.X},Ci=function(){Ai.X(1)};var Di=function(a,b){if(a)this.focused=a.focused,this.alwaysOnTop=a.alwaysOnTop,this.top=a.top,this.left=a.left,this.width=a.width,this.height=a.height,this.state=a.state;else if(b){this.focused=b.contentWindow.document.hasFocus();this.alwaysOnTop=b.isAlwaysOnTop();var c=b.getBounds();this.top=c.top;this.left=c.left;this.width=c.width;this.height=c.height;this.state=b.isMinimized()?"minimized":"normal"}else this.alwaysOnTop=this.focused=!1,this.height=this.width=this.left=this.top=0,this.state=""}; Di.prototype.isMinimized=function(){return"minimized"==this.state};
var Ei=function(){_.E.call(this);this.a=new _.li};_.y(Ei,_.E);Ei.prototype.da=function(a){var b,c=Array.prototype.slice.call(arguments);(0,_.s)(this.a.B(),function(a){b=a.apply(null,c)});return b};Ei.prototype.addListener=function(a){this.a.add(a)};Ei.prototype.removeListener=function(a){this.a.remove(a)};Ei.prototype.n=function(){this.a.clear();Ei.t.n.call(this)};
var Hi=function(){_.E.call(this);this.b=[];this.h=new Ei;_.G(this,this.h);this.f=new Ei;_.G(this,this.f);this.onClosed=new Ei;this.g=!1;this.c=null;this.k=(0,_.n)(this.A,this);Fi.addListener(this.k);this.l=(0,_.n)(this.w,this);Gi.addListener(this.l)};_.y(Hi,_.E);Hi.prototype.n=function(){Ii(this)||void 0!=this.a&&window.chrome.windows.remove(this.a);Ji(this);this.k&&(Fi.removeListener(this.k),Gi.removeListener(this.l));_.F(this.onClosed);Hi.t.n.call(this)};
var Fi=window.chrome.windows&&window.chrome.windows.onRemoved,Gi=window.chrome.windows&&window.chrome.windows.onFocusChanged;Hi.prototype.create=function(a){window.chrome.windows.create(a,(0,_.n)(function(a){this.D?window.chrome.windows.remove(a.id):(this.a=a.id,Ki(this))},this))};
var Ki=function(a){if(null!=a.b&&Li(a))if(Ii(a))Ji(a);else{for(;a.b.length&&!Ii(a);)a.b.shift()(a);a.b=null}},Li=function(a){return!(!_.Va(a.a)||!a.e)},Mi=function(a,b){Ii(a)?Ji(a):null==a.b?b(a):a.b.push(b)},Ii=function(a){return!(!a.e||!a.e.closed)};Hi.prototype.A=function(){Ii(this)&&Ji(this)};var Ji=function(a){if(!a.g){var b=a.onClosed;a.onClosed=new Ei;_.fe((0,_.n)(function(){this.g||(this.g=!0,b.da(this));_.F(b)},a))}};
Hi.prototype.w=function(a){if(a!=this.a){if(null===this.c||this.c)this.c&&(this.c=!1),this.f.da(this)}else this.c=!0,this.h.da(this)};var Ni=function(a){var b;b=a.a?a.e:null;return!b||Ii(a)?null:b};Hi.prototype.isMinimized=function(){return this.u.isMinimized()};Hi.prototype.isMaximized=function(){return this.u.isMaximized()};Hi.prototype.minimize=function(){Mi(this,(0,_.n)(function(){window.chrome.windows.update(this.a,{state:"minimized"})},this))};
Hi.prototype.focus=function(){Mi(this,(0,_.n)(function(){window.chrome.windows.update(this.a,{focused:!0})},this))};var Oi=function(a,b){Mi(a,(0,_.n)(function(){window.chrome.windows.update(this.a,{drawAttention:b})},a))};Hi.prototype.getProperties=function(a){Mi(this,_.Ua(Pi,[this],function(b){a(b[0])}))}; var Pi=function(a,b){window.chrome.windows.getAll(function(c){var d={};(0,_.s)(c,function(a){d[a.id]=a});var e=[];(0,_.s)(a,function(a){var b;a&&Li(a)&&!Ii(a)&&(b=d[a.a]);var c;b&&(c=new Di(b));e.push(c)});b(e)})};
_.Qi=new _.L("b");_.Ri=new _.L("c");_.Si=new _.L("d");_.Ti=new _.L("e");_.Ui=new _.L("f");_.Vi=new _.L("g");_.Wi=new _.L("h");_.rd=new _.L("i");_.Xi=new _.L("j");_.Yi=function(a){this.c=a;this.a=new _.Uc;this.b=a.get(_.Ic);this.a.setItem(new _.Qc("StartOnBrowserLaunch",!0,!1,!1));_.Vc&&this.a.setItem(new _.Qc("TopMost",!0));a=new _.Qc("StopOnBrowserClose",!1,!1,!1);a.setEnabled(!1);this.a.setItem(a);a=new _.Qc("TrayIcon",!0,!1,!1);a.setEnabled(null!=window.navigator.platform.match(/Win.*/)||Uh()||Th());this.a.setItem(a);(a=this.b.get("settings"))&&_.Tc(this.a,a);this.b.set("settings",_.Hh(this.a))};_.Ta("ace.core.SettingsManager",_.Yi);
var Zi=window.chrome.runtime&&window.chrome.runtime.getURL&&window.chrome.runtime.getURL("settingsdialog.html")||"";_.Yi.prototype.e=function(){this.b.set("settings",_.Hh(this.a));var a=_.V.e("setting");if(a&&0!=a.length)$i(a[0],"focus");else{var a=Math.floor((window.screen.height-200)/2),b=Math.floor((window.screen.width-520)/2),c=["width=520"];c.push("height=200");c.push("top="+a);c.push("left="+b);c.push("location=no");$h(Zi,c.join(","))}};_.Yi.prototype.launchSettingsDialog=_.Yi.prototype.e;
_.Yi.prototype.f=function(){var a=new _.Uc(_.Hh(this.a)),b=this.b.get("settings");_.Tc(this.a,b);var c=new _.Uc(b),b=c.getItem("StopOnBrowserClose"),a=a.getItem("TrayIcon"),c=c.getItem("TrayIcon");a.ba&&(c.F()||b.F()?(b=this.c.get(_.Ri),aj(b),bj(b)):c.F()||b.F()||cj(this.c.get(_.Ri)))};_.Yi.prototype.updateSettingsFromStorage=_.Yi.prototype.f;_.Yi.prototype.j=function(){var a=_.V.e("setting");if(a)for(var b=0;b<a.length;++b)$i(a[b],"close")};_.Yi.prototype.closeUI=_.Yi.prototype.j; var $i=function(a,b){var c=new _.Lc;_.Oc(c,b);_.Pc(c,[]);_.V.b(a).sendMessage(c)};
var W=new _.$c("act"),dj=new _.$c("impr"),ej=new _.$c("tran"),fj=new _.$c("perf");new _.M(W,1);new _.M(W,2);new _.M(W,3);new _.M(W,4);new _.M(W,5);new _.M(W,6);new _.M(W,7);new _.M(W,8);new _.M(W,9);new _.M(W,10);new _.M(W,11);new _.M(W,12);new _.M(W,25);new _.M(W,13);new _.M(W,14);new _.M(W,15);new _.M(W,22);new _.M(W,16);new _.M(W,17);new _.M(W,18);new _.M(W,19);new _.M(W,20);new _.M(W,21);new _.M(W,23);new _.M(W,24);_.gj=new _.M(dj,1E3);new _.M(ej,1001);new _.M(fj,1002);
_.hj=new _.L("k");_.X=function(a){this.k=a;this.p=a.get(_.Wi);this.b=a.get(_.Ic);this.a=1;this.e=this.h=null;this.g=this.c=!1;this.l=(0,_.n)(this.q,this);aj(this);bj(this);null!=this.b.a.get("UnreadIndicator")&&this.b.remove("UnreadIndicator");null!=this.b.a.get("app_status")&&this.b.remove("app_status");null!=this.b.a.get("user_id")&&this.b.remove("user_id");null!=this.b.a.get("client_state")&&this.b.remove("client_state")};_.y(_.X,_.E);_.Ta("ace.core.DesktopManager",_.X);_.X.prototype.n=function(){cj(this);_.X.t.n.call(this)};
_.X.prototype.f=function(a,b){this.a!=b&&(this.a=b,bj(this),ij(this),1==this.a&&(this.e=this.h=null,this.g=this.c=!1,cj(this),this.p.j(),this.k.get(_.Ui).b()),_.V.g())};_.X.prototype.changeDesktop=_.X.prototype.f;_.X.prototype.u=function(a,b){this.c!=b&&(this.c=b,bj(this),ij(this))};_.X.prototype.setMainUiShowing=_.X.prototype.u;
var aj=function(a){var b=a.p.a,c;if(c=null!=window.navigator.platform.match(/Win.*/)||Uh()||Th())c=b.a.get("StopOnBrowserClose"),(c=c&&c.ba?c.F():!1)||(c=(b=b.a.get("TrayIcon"))&&b.ba?b.F():!1);c&&window.chrome.systemIndicator&&(window.chrome.systemIndicator.enable(),window.chrome.systemIndicator.onClicked.addListener(a.l))},cj=function(a){window.chrome.systemIndicator&&(window.chrome.systemIndicator.disable(),window.chrome.systemIndicator.onClicked.removeListener(a.l))},ij=function(a){var b;switch(a.a){case 2:b=
_.T("QUASAR_TIP_CONNECTING");break;case 3:b=_.T("QUASAR_TIP_NOT_LOGIN");break;case 4:case 9:case 8:b=a.c?a.g?_.T("CHROME_EXT_TIP_CONNECTED_MISSED_MESSAGES"):_.T("QUASAR_TIP_CONNECTED"):_.T("QUASAR_TIP_NOT_LOGIN");break;case 6:b=_.T("QUASAR_TIP_NOT_LOAD");break;default:b=_.T("QUASAR_TIP_DISCONNECTED")}a=a.e?"\n"+a.e:"";(b=_.T("CHROME_EXT_SHORT_NAME")+a+"\n"+b)&&window.chrome.browserAction.setTitle({title:b})};
_.X.prototype.w=function(a,b,c){1!=this.a&&(a=b||_.T("QUASAR_MENUTEXT_UNKNOWN_USER"),a!=this.h&&(this.h=a),this.e=c)};_.X.prototype.updateUserName=_.X.prototype.w;_.X.prototype.v=function(a,b){this.g!=b&&(this.g=b,bj(this),ij(this))};_.X.prototype.setUnreadIndicator=_.X.prototype.v;
var bj=function(a){window.chrome.browserAction.setIcon(jj(a,!0));window.chrome.systemIndicator&&window.chrome.systemIndicator.setIcon(jj(a))},kj=function(a){switch(a.a){case 2:return"offline_working";case 4:case 9:case 8:return a.c?a.g?"available_missed":"available":"offline";case 6:return"offline_unknown";default:return"offline"}},jj=function(a,b){var c=!b&&Th()?"_mac_":"_",d=kj(a),e=window.chrome.runtime.getURL("images_4/presence/"+d+c+"19.png"),c=window.chrome.runtime.getURL("images_4/presence/"+ d+c+"38.png");return{path:{19:e,38:c}}};_.X.prototype.q=function(){var a=_.V.a();this.k.get(_.hj).a("qstcl");a.mb();a.b("onTrayClick",[1])};
var lj=function(a,b,c){_.J.call(this);this.a=b.createElement("IFRAME");b.body.appendChild(this.a);this.a.src=a;c&&(this.a.id=c,this.a.name=c);a=new _.I(this);_.G(this,a);a=_.Ed(a,this.a,"load",this.c,void 0);_.Ed(a,this.a,"error",Ci,void 0).listen(b.defaultView,"focus",this.b).listen(b.body,"focus",this.b)};_.y(lj,_.J);lj.prototype.b=function(){_.Pb(this.a.focus,this.a)};lj.prototype.c=function(){this.b()};lj.prototype.n=function(){this.a.parentElement.removeChild(this.a);this.a=null;lj.t.n.call(this)};
var qj=function(a,b){_.I.call(this);this.b=a;_.Jc("viewer",""+(new Date).getTime());this.e=this.f=null;this.l=_.V;this.u=(0,_.m)();this.k=a.get(_.Ri);var c=a.get(_.Vi),d=_.T("CHROME_EXT_SHORT_NAME"),e=ai("viewer-14.png"),f=ai("viewer-28.png"),d=mj(c,"viewer","viewer","viewer.html?viewer",d,e,f),e=b?_.Q(b,_.nj,2).Ja():null,e=oj(c,new hi(260,460),!0,e);pj(c,d.id,e);this.a=d;this.a.onClosed.addListener((0,_.n)(this.C,this));Mi(this.a,(0,_.n)(this.p,this))};_.y(qj,_.I);
qj.prototype.n=function(){this.b.b(_.rd)==this&&this.b.u();this.removeAll();qj.t.n.call(this)};var rj=function(a){_.F(a.f);a.f=null;_.F(a.e);a.e=null;_.Ih(a.c.a,"retryInfo").style.display="none"};qj.prototype.close=function(){_.F(this.a);this.b.b(_.rd)==this&&this.b.u()};
qj.prototype.p=function(){this.c=new Vh(Ni(this.a).document);this.a.setTitle(_.T("CHROME_EXT_SHORT_NAME"));_.Ih(this.c.a,"retryMessage").textContent=_.T("CHROME_EXT_CANNOT_CONNECT");var a=_.Ih(this.c.a,"retryLink");a.textContent=_.T("QUASAR_TRY_NOW");this.listen(a,"click",this.q);this.listen(this.l,"onStatusChange",this.h);this.h()};qj.prototype.q=function(a){a.b();this.b.get(_.Qi).f()};
qj.prototype.h=function(){switch(this.k.a){case 3:if(!this.f){rj(this);var a;a=this.b.get(_.Wi).a;a=new _.Xd(a.b[0]);var b=new _.Xd("/talkgadget/qsignin");_.R(b,"passive","1");_.R(b,"hl",window.chrome.i18n.getMessage("@@ui_locale"));a=_.ae(a,b).toString();this.f=new lj(a,this.c.a)}break;case 2:rj(this);break;case 6:rj(this);_.Ih(this.c.a,"retryInfo").style.display="block";break;default:sj(this)}}; var sj=function(a){a.e||(rj(a),tj(a.b.get(_.Qi)).then(function(a){this.e=new lj(a,this.c.a,"popoutRoster")},void 0,a))};
var uj=function(a,b){this.b=_.Jd(a);this.a=0;this.c=b||!1};uj.prototype.F=function(a){var b=this.b[this.a],b=(.5+1*Math.random())*b;a&&vj(this);return b};var vj=function(a){a.c&&a.a==a.b.length-1||a.a++};var wj=function(a,b,c){_.E.call(this);this.b=a;this.e=b||0;this.c=c;this.X=(0,_.n)(this.f,this)};_.y(wj,_.E);wj.prototype.a=0;wj.prototype.n=function(){wj.t.n.call(this);this.stop();delete this.b;delete this.c};var xj=function(a,b){a.stop();a.a=_.fe(a.X,_.v(b)?b:a.e)};wj.prototype.stop=function(){0!=this.a&&_.ge(this.a);this.a=0};wj.prototype.f=function(){this.a=0;this.b&&this.b.call(this.c)};
var yj=function(a,b,c){_.E.call(this);this.c=a;this.b=b;this.a=c;this.X=(0,_.n)(this.Sc,this)};_.y(yj,_.E);_.h=yj.prototype;_.h.Pa=!1;_.h.na=null;_.h.stop=function(){this.na&&(_.ge(this.na),this.na=null,this.Pa=!1)};_.h.n=function(){yj.t.n.call(this);this.stop()};_.h.Sc=function(){this.na=null;this.Pa&&(this.Pa=!1,zj(this))};var zj=function(a){a.na=_.fe(a.X,a.b);a.c.call(a.a)};
_.Y=function(a){_.I.call(this);this.a=a;this.c=a.get(_.Ri);this.S=a.b(_.Vi);this.L=_.bc();this.l=null;this.J=new yj(this.f,6E4,this);_.G(this,this.J);a=(0,_.n)(this.dd,this);Ai.X=a;_.Za(this,Bi);this.h=!1;this.q=new uj(di,!0);this.K=new wj(this.rd,this.q.F(),this);_.G(this,this.K);this.k=new wj(this.oc,2E4,this);_.G(this,this.k);this.listen(window,"online",this.kd);this.w=this.A=0;this.b=new uj(ei);this.e=new wj(this.Aa,this.b.F(),this);_.G(this,this.e);window.chrome.cookies.onChanged.addListener((0,_.n)(this.Ba,
this));this.v=(0,_.n)(this.aa,this);this.u=(0,_.n)(this.W,this);window.chrome.tabs.onUpdated.addListener(this.v);window.chrome.tabs.onCreated.addListener(this.u)};_.y(_.Y,_.I);_.Ta("ace.core.DataChannelManager",_.Y);_.Y.prototype.n=function(){window.chrome.tabs.onCreated.removeListener(this.u);window.chrome.tabs.onUpdated.removeListener(this.v);delete this.u;delete this.v;_.F(this.l);_.Y.t.n.call(this)};
_.Y.prototype.p=function(a,b){_.Aj(this);t:{var c=this.a,d=c.b(_.rd);if(d){if(Li(d.a)?!Ii(d.a):1E3>(0,_.m)()-d.u){d.a.focus();break t}d.close()}d=new qj(c,b);c.a(_.rd,d,!0)}};_.Y.prototype.showViewer=_.Y.prototype.p;_.Y.prototype.Ra=function(a,b){this.L.a(b||"")};_.Y.prototype.setRosterUrl=_.Y.prototype.Ra;var tj=function(a){return a.L.b};_.Y.prototype.za=function(){this.c.f(0,1);var a=this.a.b(_.rd);a&&a.close();Bj(this);this.h=!1};_.Y.prototype.terminateApplication=_.Y.prototype.za;
_.Aj=function(a){a.h||(a.listen(_.V,"onStatusChange",a.Hc),a.f(),a.a.get(_.Wi),a.h=!0)};_.Y.prototype.f=function(){this.D||(this.c.f(0,2),Bj(this),this.l=new lj(window.chrome.runtime.getURL("datachannel.html"),window.document,"centralRoster"))};var Bj=function(a){a.S.f();a.a.get(_.Ui).b();_.F(a.l);a.l=null;a.L=_.bc()},Dj=function(a,b){var c=Jh(a.a.get(_.Wi).a);window.chrome.cookies.getAll({url:c},(0,_.n)(function(a){a=a&&Cj("SID",a)&&Cj("SSID",a)&&Cj("SAPISID",a);b(a)},a))};
_.Y.prototype.Ca=function(a){var b=this.c.a;if(a){if(3==b){if(a=0==this.e.a)a=this.b,a=a.a<a.b.length;a&&xj(this.e,this.b.F())}}else 3!=b&&this.f()};_.Y.prototype.Ba=function(a){"SSID"!=a.cookie.name&&"SAPISID"!=a.cookie.name||".google.com"!=a.cookie.domain||Dj(this,(0,_.n)(this.Ca,this))};var Cj=function(a,b){return(0,_.pa)(b,function(b){var d=b.expirationDate&&b.expirationDate<(0,_.m)()/1E3;return b.name==a&&".google.com"==b.domain&&!d})};_.h=_.Y.prototype;
_.h.Hc=function(){this.K.stop();this.k.stop();switch(this.c.a){case 2:xj(this.k);break;case 6:xj(this.K,this.q.F());break;case 4:case 9:case 8:case 5:this.q.a=0,this.e.stop()}};_.h.kd=function(){if(4!=this.c.a){var a=this.J;a.na?a.Pa=!0:zj(a)}};_.h.rd=function(){vj(this.q);this.f()};_.h.dd=function(a){Bj(this);switch(a){case 1:this.oc();break;case 2:a=this.J,a.na?a.Pa=!0:zj(a)}};_.h.oc=function(){this.D||(this.k.stop(),this.c.f(0,6))};
var Ej=function(a){a.w++;var b=a.a.get(_.hj);1==a.w?b.a("qccro"):2==a.w?b.a("qccrt"):b.a("qccrm")};_.Y.prototype.Aa=function(){vj(this.b);Ej(this);Dj(this,(0,_.n)(function(a){a&&this.f()},this))};_.Y.prototype.aa=function(a,b){b.url&&Fj(this,b.url)};_.Y.prototype.W=function(a){a.url&&Fj(this,a.url)}; var Gj=function(a){a.A++;var b=a.a.get(_.hj);1==a.A?b.a("qctro"):2==a.A?b.a("qctrt"):b.a("qctrm")},Fj=function(a,b){(0,_.pa)(ci,function(a){return a.test(b)})&&0!=a.b.a&&(a.b.a=0,Gj(a),0!=a.e.a&&xj(a.e,a.b.F()))};
var Hj=function(a,b){this.a=a;this.h=b;this.k=window.chrome.runtime.getURL("images_4/icon-128x128.png");this.j=this.g=this.l="";this.e=0;this.b=[];this.f=""},Ij=function(a){this.name=a;this.title=""};Hj.prototype.setTitle=function(a){a&&(this.l=a)};
var Jj=function(a){return a.replace(/^(\<br\>)+/,"")},Kj=function(a){var b=a.l;a.g&&(b+=" "+a.g);var c=Jj(a.j||7!=a.h?a.j||"":_.T("CHROME_EXT_ONEONONE_PLUS_HANGOUT_DETAILS")),d=(0,_.ma)(a.b,function(a){var b;if(!(b=a.title))t:{switch(a.name){case "join hangout":b=_.T("QUASAR_ANSWER_BUTTON_TEXT");break t;case "ignore":b=_.T("QUASAR_DECLINE_BUTTON_TEXT");break t}b=""}return{title:b}},a);return{type:"basic",iconUrl:a.k,title:b,message:c,buttons:d,priority:2}};
var Lj=function(){this.b=new _.w;this.a=new _.fi(18E5);_.wb(this.a,"tick",(0,_.n)(this.c,this,this.b,0,200));_.gi(this.a)};_.y(Lj,_.E);Lj.prototype.n=function(){this.a.C()};var Mj=function(a,b){var c=null!=b.c?b.a+b.c:null;return null!=c?_.Na(a.b,c):!1};Lj.prototype.add=function(a){var b=null!=a.c?a.a+a.c:null;null!=b&&!Mj(this,a)&&this.b.set(b,(0,_.m)()+18E5)};
Lj.prototype.c=function(a,b,c){var d=a.V();if(0!=d){var e=0;null!=b&&0<b&&(e=b<d?b:d);b=d;null!=c&&c<d&&(b=0<c?c:0);e>b&&(e=b);var f=[];c=a.ha(!0);mi(c,function(b){f.push([b,a.get(b)])});f.sort(function(a,b){return a[1]-b[1]});if(31536E7<f[d-1][1]-f[0][1])a.clear();else{c=0;b=d-b;for(var d=d-e,e=(0,_.m)(),g=0;g<f.length;++g)if(c<b||c<d&&f[g][1]<=e)a.remove(f[g][0]),c+=1;else break}}};
var Nj=function(a){_.A(this,a,"acr:bcr",[])};_.y(Nj,_.z);_.D("acr:bcr",Nj);var Oj=function(a){_.A(this,a,"acr:srs",[])};_.y(Oj,_.z);_.D("acr:srs",Oj);var Pj=function(a){_.A(this,a,"acr:rss",[])};_.y(Pj,_.z);_.D("acr:rss",Pj);var Qj=function(a){_.A(this,a,"acr:rrs",[])};_.y(Qj,_.z);_.D("acr:rrs",Qj);var Rj=function(a){_.A(this,a,"acr:rsr",[])};_.y(Rj,_.z);_.D("acr:rsr",Rj);_.Sj=function(a){_.A(this,a,"acr:wrs",[1])};_.y(_.Sj,_.z);_.D("acr:wrs",_.Sj);var Tj=function(a){_.A(this,a,0,[])};_.y(Tj,_.z); Tj.prototype.Z=function(){return _.C(this,2)};Tj.prototype.Ia=function(){return _.C(this,11)};
var Wj;_.Uj=function(a){_.A(this,a,"acq:rs",[3])};_.y(_.Uj,_.z);_.D("acq:rs",_.Uj);var Vj=function(a){_.A(this,a,0,[])};_.y(Vj,_.z);Vj.prototype.getState=function(){return _.C(this,6)};_.nj=function(a){_.A(this,a,0,[])};_.y(_.nj,_.z);_.nj.prototype.Ja=function(){return _.Q(this,Vj,1)};Wj=function(a,b){_.Fd(a,1,b)};_.Xj=function(a){_.A(this,a,0,[])};_.y(_.Xj,_.z);_.Xj.prototype.Z=function(){return _.C(this,1)};_.Xj.prototype.Ja=function(){return _.Q(this,Vj,2)};var Yj=function(a,b){_.Fd(a,2,b)}; _.Xj.prototype.Ia=function(){return _.C(this,3)};
var Zj,dk,ck;Zj=function(a){this.c=a;this.a={};this.b=a.get(_.Ic)};_.ak=function(a,b){return(null!=a?a:"null")+"-"+(null!=b?b:"null")};
dk=function(a,b){_.fe(a.reload,6E4,a);var c=[],d={},e=a.c.get(_.Vi),f=_.ji(b,Tj,1)||[];(0,_.s)(f,function(a){c.push(_.C(a,1));d[_.ak(a.Z(),a.Ia())]=a});var g=c.length;c.push("viewer");bk(e,c,(0,_.n)(function(a){for(var c=[],e=0;e<f.length;e++){var K=a[e];if(K){var da=f[e],P=new _.Xj;_.N(P,3,da.Ia());_.N(P,1,da.Z());Yj(P,ck(K));c.push(P)}}_.ni(c,function(a,b){var c=b.Ja(),c=_.C(c,2),d=a.Ja();return c-_.C(d,2)});(0,_.s)(c,function(a,b){_.N(d[_.ak(a.Z(),a.Ia())],3,b)});a=a[g];e=new _.Uj;a&&(K=new _.nj,
Wj(K,ck(a)),_.Fd(e,2,K));_.ii(e,3,c);_.ii(b,1,f);_.Fd(e,1,b);this.b.set("ReloadState",e.G);_.V.a().b("eventReloadStateSaved",[])},a))};ck=function(a){var b=new Vj;_.N(b,1,a.top);_.N(b,2,a.left);_.N(b,3,a.width);_.N(b,4,a.height);_.N(b,5,a.focused);_.N(b,6,a.state);_.N(b,7,a.alwaysOnTop);return b};Zj.prototype.read=function(){var a=this.j;this.j=null;_.V.a().b("eventReloadStateRead",[a&&a.G||null])};Zj.prototype.reload=function(){window.chrome.runtime.reload()};
_.Z=function(a){this.a=new Zj(a);this.b=a;window.chrome.runtime.onUpdateAvailable.addListener((0,_.n)(this.g,this))};_.Ta("ace.core.ExtensionLibrary",_.Z);_.Z.prototype.g=function(){_.V.a().b("eventReloadClient",[]);_.fe(this.a.reload,864E5+288E5*Math.random(),this.a)};_.Z.prototype.q=function(a,b,c,d){a=_.V.b(b);null!=a&&_.v(d)&&d&&(d=a.h,null!=d&&null!=d.id&&(window.chrome.tabs.update(d.id,{selected:!0}),c&&window.chrome.tabs.get(d.id,function(a){_.Oh(a.windowId)})))};_.Z.prototype.selectTab=_.Z.prototype.q;
_.Z.prototype.h=function(a,b,c){c?$h(b,"width=500,height=400"):window.chrome.tabs.create({url:b,selected:!0},function(a){null!=a?_.fe(function(){window.chrome.tabs.get(a.id,function(a){_.Oh(a.windowId)})},2E3):$h(b)})};_.Z.prototype.openUrl=_.Z.prototype.h;_.Z.prototype.f=function(a,b){this.c=this.b.get(_.Vi);this.c.focus(b)};_.Z.prototype.focusMoleByFrameId=_.Z.prototype.f;_.Z.prototype.e=function(){_.V.a().mb()};_.Z.prototype.showApplication=_.Z.prototype.e;
_.Z.prototype.p=function(a,b){var c=new _.Sj(b);dk(this.a,c)};_.Z.prototype.saveReloadState=_.Z.prototype.p;_.Z.prototype.k=function(){this.a.read()};_.Z.prototype.readReloadState=_.Z.prototype.k;_.Z.prototype.l=function(){this.a.reload()};_.Z.prototype.reloadExtension=_.Z.prototype.l;_.Z.prototype.j=function(){_.V.a().Fc()};_.Z.prototype.onHostReady=_.Z.prototype.j;
var ek=function(a,b,c){this.a=c||new Di;c||(this.a.alwaysOnTop=Kh(a.get(_.Wi).a))};ek.prototype.getProperties=function(){return this.a};var gk=function(a,b,c){(b=b.f)?fk(a.get(_.Vi),b,function(b){c(new ek(a,0,b))}):c(new ek(a))};var hk=function(){Hi.call(this)};_.y(hk,Hi);hk.prototype.setTitle=function(a){Mi(this,(0,_.n)(function(){Ni(this).document.title=a},this))};
var jk=function(a,b){a.q=b;Mi(a,(0,_.n)(function(){ik(this)},a))},kk=function(a,b){a.v=b;Mi(a,(0,_.n)(function(){ik(this)},a))},ik=function(a){var b=Ni(a).document,c=b.querySelector("HEAD"),d=c.querySelectorAll("link[rel='shortcut icon']"),e=ai("icon-24x24.png");a=[a.q||e,a.v];for(var e=_.Kc()?2:1,f="",g=0;g<e;++g)if(a[g]&&a!=f){var f=a[g],l=d[g];l||(l=b.createElement("LINK"),c.appendChild(l));l.rel="shortcut icon";var q=a[g];l.type=Sh(q,".ico")?"image/x-icon":Sh(q,".gif")?"image/gif":"image/png"; l.href=a[g]}};
var nk,lk,ok;_.mk=function(a){this.a={};if(a)for(var b=0;b<a.length;b++)this.a[lk(a[b])]=null;for(var c in Object.prototype);};nk={};lk=function(a){return a in nk||32==String(a).charCodeAt(0)?" "+a:a};ok=function(a){return 32==a.charCodeAt(0)?a.substr(1):a};_.h=_.mk.prototype;_.h.add=function(a){this.a[lk(a)]=null};_.h.clear=function(){this.a={}};_.h.clone=function(){var a=new _.mk,b;for(b in this.a)a.a[b]=null;return a};_.h.contains=function(a){return lk(a)in this.a};
_.h.forEach=function(a,b){for(var c in this.a)a.call(b,ok(c),void 0,this)};_.h.V=Object.keys?function(){return Object.keys(this.a).length}:function(){var a=0,b;for(b in this.a)a++;return a};_.h.B=Object.keys?function(){return Object.keys(this.a).map(ok,this)}:function(){var a=[],b;for(b in this.a)a.push(ok(b));return a};_.h.P=function(){for(var a in this.a)return!1;return!0};_.h.remove=function(a){a=lk(a);return a in this.a?(delete this.a[a],!0):!1};_.h.ha=function(){return Yh(this.B())};
_.$=function(a){_.E.call(this);this.h=a;this.a={};this.c={};this.b=new _.mk;_.Ta("__onPanelLoad",(0,_.n)(this.I,this));this.p=a.get(_.Ri);a=new _.I(this);_.G(this,a);a.listen(_.V,"onStatusChange",this.u)};_.y(_.$,_.E);_.Ta("ace.core.PanelsManager",_.$);_.$.prototype.n=function(){for(var a in this.a)this.fb(this.a[a]);_.$.t.n.call(this)};
_.$.prototype.isMaximized=function(a,b){var c=function(a){a=a?!a.isMinimized():null;_.V.a().b("eventIsMinimizedResponse",[b,a])},d=this.a[b];d?d.getProperties(c):c(void 0)};_.$.prototype.isMaximized=_.$.prototype.isMaximized;
_.$.prototype.J=function(a,b,c,d,e,f,g,l,q,B){a="panel.html?"+b;d=d||_.T("CHROME_EXT_SHORT_NAME");b=mj(this,b,l||b,a,d,e,g);Mi(b,(0,_.n)(this.k,this,c));c=new hi(280,420);q||B?(q=q||null,e=B||null,B=this.h.get(_.Si).a,q=_.ak(q,e),(e=B.a[q])&&delete B.a[q],B=e?e.Ja():null):B=null;f=oj(this,c,!!f,B);pj(this,b.id,f)};_.$.prototype.openPanel=_.$.prototype.J;
_.$.prototype.v=function(a,b,c,d,e,f,g){a="dialog.html?"+b;d=d||_.T("CHROME_EXT_SHORT_NAME");b=mj(this,b,b,a,d);Mi(b,(0,_.n)(this.k,this,c));c=oj(this,new hi(f,g),e,null);c.Xc=!0;pj(this,b.id,c);return b};_.$.prototype.openDialog=_.$.prototype.v;var mj=function(a,b,c,d,e,f,g){a.a[b]&&a.fb(a.a[b]);var l=new hk;l.id=b;l.key=c;l.url=d;l.setTitle(e);jk(l,f);kk(l,g);a.a[b]=l;a.c[c]=b;return l};_.$.prototype.k=function(a,b){b.p=new lj(a,Ni(b).document);_.G(b,b.p)};
var oj=function(a,b,c,d){b={focus:c,ya:null,width:b.width,height:b.height,minimize:!1};if(d){b.top=_.C(d,1);b.left=_.C(d,2);c=_.C(d,3);var e=_.C(d,4);_.C(d,7)?(b.width=Math.max(b.width,c),b.height=Math.max(b.height,e)):(b.width=c,b.height=e);"minimized"==d.getState()&&(b.minimize=!0);b.ya=_.C(d,7);b.focus=_.C(d,5)}b.ya="boolean"==typeof b.ya?b.ya:Kh(a.h.get(_.Wi).a);return b},pj=function(a,b,c){var d=a.a[b];d.onClosed.addListener((0,_.n)(a.fb,a));d.h.addListener((0,_.n)(a.A,a));d.f.addListener((0,_.n)(a.w,
a));c.minimize&&d.minimize();b="panel";c.ya||(b=Uh()?"popup":"detached_panel");c.Xc&&(b="popup");var e={type:b,url:d.url,focused:c.focus,width:c.width,height:c.height};if(b=null!=c.top&&null!=c.left)e.top=c.top,e.left=c.left;b||c.ya?d.create(e):bk(a,Object.keys(a.c),(0,_.n)(function(a){var b=window.screen,c;c=new hi(260,460);var q=new hi(280,420);c=new hi(Math.max(c.width,q.width),Math.max(c.height,q.height));for(var B=b.availWidth,K=b.availHeight-50,q=b.availTop+K%c.height,b=b.availLeft+B%c.width,
B=Math.floor(B/c.width),da=Math.floor(K/c.height),K=Array(B*da),P=0;P<a.length;P++){var la=a[P];if(la){for(var Kb=[la.left,la.left+la.width-1],la=[la.top,la.top+la.height-1],oa=0;2>oa;oa++)Kb[oa]=Math.floor(Math.max(0,Kb[oa]-b)/c.width),la[oa]=Math.floor(Math.max(0,la[oa]-q)/c.height);for(oa=Kb[0];oa<=Kb[1];oa++)for(var bb=la[0];bb<=la[1];bb++)oa<B&&bb<da&&(K[oa+bb*B]=1)}}a=K.length-1;for(P=K.length-1;0<=P;P--)if(!K[P]){a=P;break}K=a%B*c.width;e.top=q+Math.floor(a/B)*c.height+(c.height-e.height);
e.left=b+K+(c.width-e.width);d.create(e)},a))};_.$.prototype.g=function(a,b){var c=this.a[b];c&&_.F(c)};_.$.prototype.closePanel=_.$.prototype.g;_.$.prototype.f=function(){for(var a in this.a)0==this.a[a].url.indexOf("panel.html")&&this.g(0,a)};_.$.prototype.closeAllPanels=_.$.prototype.f;_.$.prototype.setTitle=function(a,b,c){(a=this.a[b])&&a.setTitle(c)};_.$.prototype.setTitle=_.$.prototype.setTitle;_.$.prototype.q=function(a,b,c){this.a[b]&&Oi(this.a[b],c)};_.$.prototype.drawAttention=_.$.prototype.q;
_.$.prototype.focus=function(a){if(this.a[a]){var b=this.a[a];b.getProperties((0,_.n)(function(a){if(a&&(a=Ni(b),0==a.outerWidth&&0==a.outerHeight)){this.fb(b);return}b.focus()},this))}};_.$.prototype.L=function(a,b,c){this.a[b]&&jk(this.a[b],c)};_.$.prototype.setPresence=_.$.prototype.L;_.$.prototype.K=function(a,b,c){this.a[b]&&kk(this.a[b],c)};_.$.prototype.setAvatar=_.$.prototype.K;_.$.prototype.e=function(a,b,c){for(var d in this.a)(b||this.b.contains(d))&&this.l(0,d,b,c);b||this.b.clear()};
_.$.prototype.minimizeAllPanelsIfTopmost=_.$.prototype.e;_.$.prototype.l=function(a,b,c,d){var e=this.a[b];e&&e.getProperties((0,_.n)(function(a){if(a&&a.alwaysOnTop&&!this.D)if(c){var g;(g=!d)||(g=new _.bi(a.left,a.top,a.width,a.height),g=g.left<=d.left+d.width&&d.left<=g.left+g.width&&g.top<=d.top+d.height&&d.top<=g.top+g.height);g&&!a.isMinimized()&&(e.minimize(),this.b.add(b))}else window.chrome.windows.update(e.a,{state:"normal"}),this.b.remove(b)},this))};
_.$.prototype.minimizePanelIfTopmost=_.$.prototype.l;_.$.prototype.I=function(a){var b=this.a[a.location.search.substring(1)];b&&(b.e=a,Ki(b))};var fk=function(a,b,c){a=a.a[a.c[b]];!a||Ii(a)?c(void 0):a.getProperties(c)},bk=function(a,b,c){var d=[];(0,_.s)(b,(0,_.n)(function(a){d.push(this.a[this.c[a]])},a));Pi(d,c)};_.$.prototype.fb=function(a){this.a[a.id]==a&&(this.b.remove(a.id),delete this.c[a.key],delete this.a[a.id],_.F(a))};_.$.prototype.A=function(a){this.a[a.id]==a&&this.b.remove(a.id)}; _.$.prototype.w=function(a){this.a[a.id]==a&&_.V.a().b("eventBlurred",[a.id])};_.$.prototype.u=function(){3==this.p.a&&this.f()};
_.pk=function(a){_.E.call(this);this.k=a;this.a=new _.w;this.h=new _.w;this.c=new Lj;_.G(this,this.c);this.g=(0,_.n)(this.$c,this);window.chrome.notifications.onClosed.addListener(this.g);this.e=(0,_.n)(this.Ic,this);window.chrome.notifications.onClicked.addListener(this.e);this.f=(0,_.n)(this.Zc,this);window.chrome.notifications.onButtonClicked.addListener(this.f)};_.y(_.pk,_.E);_.Ta("ace.core.NotificationManager",_.pk);
_.pk.prototype.n=function(){_.s(this.a.B(),_.F);this.a.clear();window.chrome.notifications.onClosed.removeListener(this.g);window.chrome.notifications.onClicked.removeListener(this.e);window.chrome.notifications.onButtonClicked.removeListener(this.f);_.pk.t.n.call(this)};
_.pk.prototype.p=function(a,b){var c;if(b&&b.Content){c=[b.Id.ServiceUrl,b.Id.ServiceId].join(";");0==c.indexOf("bc")?c=new Hj(c,2):0==c.indexOf("hangout")?(c=new Hj(c,7),c.b.push(new Ij("join hangout")),c.b.push(new Ij("ignore"))):c=void 0;c.setTitle(b.Content.TitleText);c.g=b.Content.SubtitleText;c.j=b.Content.BodyText;c.c=b.Content.BodyTextId;var d=0;b.Content.EndTimeMs&&(d=b.Content.EndTimeMs,(0,window.isNaN)(d)||!(0,window.isFinite)(d))&&(d=0);d=d||(0,_.m)()+1E4;c.e=d;if(b.Content.ServiceIcon){var d=
c,e=b.Content.ServiceIcon;e&&(0==e.indexOf("images_4/")&&(e=window.chrome.runtime.getURL(e)),d.k=e)}b.Content.FrameId&&(c.f=b.Content.FrameId)}else c=null;c&&(_.V.a().b("eventLogImpression",["qnop"]),Mj(this.c,c)||(this.c.add(c),qk(this,c)))};_.pk.prototype.registerNotification=_.pk.prototype.p;
var qk=function(a,b){2==b.h||b.f?gk(a.k,b,function(c){c=c.getProperties();c.focused||c.alwaysOnTop||rk(a,b)}):rk(a,b)},rk=function(a,b){var c=b.a,d=b.e-(0,_.m)();0>=d?a.bc(c):(a.a.set(c,b),window.chrome.notifications.create(c,Kj(b),function(){_.V.a().b("eventLogImpression",["qtod"])}),_.ge(a.h.get(c,null)),b.e!=Number.MAX_VALUE&&a.h.set(c,_.fe((0,_.n)(a.bc,a,c),d)),_.V.a().b("eventLogImpression",["qnst"]))};_.pk.prototype.b=function(){(0,_.s)((0,_.ka)(this.a.B(),Lh),this.Fa,this)};
_.pk.prototype.cleanAllNotifications=_.pk.prototype.b;_.pk.prototype.l=function(a,b){var c=this.a.get(b);c&&this.Fa(c)};_.pk.prototype.cleanANotification=_.pk.prototype.l;_.h=_.pk.prototype;_.h.Fa=function(a){a=a.a;window.chrome.notifications.clear(a,_.Wa);this.a.remove(a)};_.h.$c=function(a,b){b&&this.a.get(a)&&(this.a.remove(a),sk(a,"toastEventOnClose"))};_.h.Ic=function(a){var b=this.a.get(a);b&&(sk(a,"toastEventOnBody"),this.Fa(b))};
_.h.Zc=function(a,b){var c=this.a.get(a);c&&(sk(a,"toastEventOnButton",c.b[b].name),this.Fa(c))};_.h.bc=function(a){var b=this.a.get(a);b&&(sk(a,"toastEventOnTimeout"),this.Fa(b))};var sk=function(a,b,c){var d=_.V;(d=d&&d.a())&&!d.D&&_.V.a().b(b,[a,c,"",!1])};
_.tk=function(a){_.A(this,a,"f.mt",[])};_.y(_.tk,_.z);_.D("f.mt",_.tk);_.uk=function(a){_.A(this,a,"er",[])};_.y(_.uk,_.z);_.D("er",_.uk);_.uk.prototype.vb=function(){return _.C(this,9)};_.uk.prototype.getData=function(){return _.C(this,4)};new _.li;_.u&&_.Ka(8);var vk=function(){throw Error("y");};vk.prototype.a=null;vk.prototype.toString=function(){return this.content};var wk=function(){vk.call(this)};_.y(wk,vk);(function(a){function b(a){this.content=a}b.prototype=a.prototype;return function(a,d){var e=new b(String(a));void 0!==d&&(e.a=d);return e}})(wk);(function(a){function b(a){this.content=a}b.prototype=a.prototype;return function(a,d){var e=String(a);if(!e)return"";e=new b(e);void 0!==d&&(e.a=d);return e}})(wk);
var xk=function(a,b){_.Zc.call(this,a,b)};_.y(xk,_.Zc);_.yk=function(a){this.a=a?_.C(a,1)||-1:-1};_.zk=new _.yk;_.Ak=function(){};_.y(_.Ak,_.le);_.Ak.prototype.b=function(){};_.Ak.prototype.b.hc=!0;_.Ak.t||_.y(_.Ak,_.le);_.U.a={};_.U.a.kb="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";_.U.a.ib=_.U.a.kb+"0123456789";_.U.a.lb=_.U.a.kb.length;_.U.a.jb=_.U.a.ib.length;_.U.a.Gb=-2147483648;_.U.a.sd=function(a){for(var b=0,c=a.length-1;0<=c;c--)b=b*(0==c?_.U.a.lb:_.U.a.jb)+_.U.a.ib.indexOf(a.charAt(c));return b+_.U.a.Gb};_.U.a.toString=function(a){var b=[],c=0;a-=_.U.a.Gb;b[c++]=_.U.a.kb.charAt(a%_.U.a.lb);for(a=Math.floor(a/_.U.a.lb);0<a;)b[c++]=_.U.a.ib.charAt(a%_.U.a.jb),a=Math.floor(a/_.U.a.jb);return b.join("")};
new xk(_.ad,"f_req");
}catch(e){_._DumpException(e)}
try{
var on=function(a,b,c){a.timeOfStartCall=(new Date).getTime();if(b&&JSON&&JSON.stringify){var d=JSON.stringify(b);200>=d.length&&(a.psdJson=d)}d=c||_.k;d.GOOGLE_FEEDBACK_START_ARGUMENTS=arguments;var e=a.serverUri||"//www.google.com/tools/feedback",f=d.GOOGLE_FEEDBACK_START;if(f)f.apply(d,arguments);else{var e=e+"/load.js?",g;for(g in a)f=a[g],null!=f&&!_.Oa(f)&&(e+=(0,window.encodeURIComponent)(g)+"="+(0,window.encodeURIComponent)(f)+"&");g=d.document;d=g.createElement("script");d.src=e;g.body.appendChild(d)}}; _.Ta("userfeedback.api.startFeedback",on);
var pn=function(){_.I.call(this);this.listen(window,"unload",this.C);window.document.title=_.T("CHROME_EXT_SHORT_NAME")+": "+_.T("CHROME_EXT_FEEDBACK_SUBTITLE");_.S("system-legend").innerText=_.T("QUASAR_FEEDBACK_SYSTEM_LEGEND");_.S("system-platform-label").innerText=_.T("QUASAR_FEEDBACK_PLATFORM_LABEL");_.S("system-platform-value").innerText=window.navigator.platform;_.S("system-user-agent-label").innerText=_.T("QUASAR_FEEDBACK_USER_AGENT_LABEL");_.S("system-user-agent-value").innerText=window.navigator.userAgent;
_.S("user-legend").innerText=_.T("CHROME_EXT_FEEDBACK_COMMENTS");_.S("privacy-legend").innerText=_.T("QUASAR_FEEDBACK_PRIVACY_LEGEND");_.S("privacy-text").innerText=_.T("QUASAR_FEEDBACK_PRIVACY_TEXT");var a=_.S("submit-button");a.innerText=_.T("QUASAR_FEEDBACK_SUBMIT_BUTTON");this.listen(a,"click",this.b);a=_.S("cancel-button");a.innerText=_.T("QUASAR_FEEDBACK_CANCEL_BUTTON");this.listen(a,"click",this.a);_.S("user-text-value").focus()};_.y(pn,_.I);
pn.prototype.b=function(){var a=_.S("user-text-value").value;if(a&&(a=a.trim())){var a={flow:"submit",serverUri:_.T("QUASAR_FEEDBACK_SERVER_URI"),productId:83052,locale:window.chrome.i18n.getMessage("@@ui_locale"),report:{description:a},callback:this.a},b={version:window.chrome.runtime.getManifest().version,build:window.chrome.runtime.id};_.S("submit-button").disabled=!0;on(a,b)}};pn.prototype.a=function(){window.close()};window.addEventListener("load",function(){new pn},!1);

}catch(e){_._DumpException(e)}
}).call(this,this.default_feedback);
// Google Inc.
