"use strict";this.default_panel=this.default_panel||{};(function(_){var window=this;
try{
_.aa=_.aa||{};_.k=this;_.ba="closure_uid_"+(1E9*Math.random()>>>0);_.m=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
try{
var ca,ea;ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};ea=function(a,b,c){return a.call.apply(a.bind,arguments)};
_.fa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.n=function(a,b,c){_.n=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:ca;return _.n.apply(null,arguments)};_.ga=function(a){return"function"==_.fa(a)};_.p=function(a){return"string"==typeof a};
_.ha=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};_.r=Array.prototype;_.ia=_.r.indexOf?function(a,b,c){return _.r.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.p(a))return _.p(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.ja=_.r.lastIndexOf?function(a,b,c){return _.r.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(_.p(a))return _.p(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.s=_.r.forEach?function(a,b,c){_.r.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.p(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.ka=_.r.filter?function(a,b,c){return _.r.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=_.p(a)?a.split(""):a,l=0;l<d;l++)if(l in g){var q=g[l];b.call(c,q,l,a)&&(e[f++]=q)}return e};_.ma=_.r.map?function(a,b,c){return _.r.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.p(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
_.na=_.r.reduce?function(a,b,c,d){d&&(b=(0,_.n)(b,d));return _.r.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,_.s)(a,function(c,g){e=b.call(d,e,c,g,a)});return e};_.pa=_.r.some?function(a,b,c){return _.r.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.p(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};
_.qa="StopIteration"in _.k?_.k.StopIteration:Error("d");t:{var ra=_.k.navigator;if(ra){var sa=ra.userAgent;if(sa){_.t=sa;break t}}_.t=""};var wa,ya,Aa;_.ta=-1!=_.t.indexOf("Opera")||-1!=_.t.indexOf("OPR");_.u=-1!=_.t.indexOf("Trident")||-1!=_.t.indexOf("MSIE");_.ua=-1!=_.t.indexOf("Gecko")&&-1==_.t.toLowerCase().indexOf("webkit")&&!(-1!=_.t.indexOf("Trident")||-1!=_.t.indexOf("MSIE"));_.va=-1!=_.t.toLowerCase().indexOf("webkit");wa=_.k.navigator||null;_.xa=wa&&wa.platform||"";ya=function(){var a=_.k.document;return a?a.documentMode:void 0};
_.za=function(){var a="",b;if(_.ta&&_.k.opera)return a=_.k.opera.version,_.ga(a)?a():a;_.ua?b=/rv\:([^\);]+)(\)|;)/:_.u?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:_.va&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(_.t))?a[1]:"");return _.u&&(b=ya(),b>(0,window.parseFloat)(a))?String(b):a}();Aa=_.k.document;_.Ba=Aa&&_.u?ya()||("CSS1Compat"==Aa.compatMode?(0,window.parseInt)(_.za,10):5):void 0;
_.k.ace_i18n={chrome_ext_short_name:{message:"Hangouts"},chrome_ext_description:{message:"Hangouts brings conversations to life with photos, emoji, and even group video calls for free."},quasar_chat_toast_info:{message:"Click to go to page..."},quasar_answer_button_text:{message:"Answer"},quasar_decline_button_text:{message:"Decline"},quasar_help:{message:"Help"},quasar_legend_startup_shutdown:{message:"Application"},chrome_ext_run_at_browser_start:{message:"Sign in to Hangouts when Chrome starts"},
chrome_ext_run_after_browser_close:{message:"Allow background mode"},chrome_ext_new_windows_topmost:{message:"Keep Hangouts on top of other windows"},quasar_label_tray_icon:{message:"Show system tray icon"},quasar_legend_notifications:{message:"Notifications"},quasar_label_all_notification:{message:"Disable notifications"},quasar_label_chat_notification:{message:"Disable chat notifications"},quasar_label_toast_timeout_chat:{message:"Allow chat notifications to timeout automatically"},quasar_label_toast_duration_chat:{message:"Timeout length (in seconds):"},
quasar_button_save:{message:"Ok"},quasar_button_apply:{message:"Apply"},quasar_button_cancel:{message:"Cancel"},chrome_ext_menutext_feedback:{message:"Send feedback"},quasar_feedback_server_uri:{message:"https://www.google.com/tools/feedback"},chrome_ext_feedback_subtitle:{message:"Send feedback"},chrome_ext_feedback_comments:{message:"Comments"},quasar_feedback_system_legend:{message:"System Information"},quasar_feedback_platform_label:{message:"Platform:"},quasar_feedback_user_agent_label:{message:"User Agent:"},
quasar_feedback_privacy_legend:{message:"Privacy Statement"},quasar_feedback_privacy_text:{message:"The description, product information, additional information and your email address will be sent to Google. See the Google Feedback Terms of Service. By submitting this content you are granting to Google the right to use it to improve our products and services. See our Privacy Policy."},quasar_feedback_submit_button:{message:"Send Feedback"},quasar_feedback_cancel_button:{message:"Cancel"},quasar_video_title:{message:"Video call from $1...",
placeholders:{1:{content:"$1"}}},quasar_voice_title:{message:"Voice call from $1...",placeholders:{1:{content:"$1"}}},quasar_group_chat_title:{message:"From group chat..."},quasar_chat_title:{message:"$1 says...",placeholders:{1:{content:"$1"}}},quasar_hangout_title:{message:"$1 is hanging out",placeholders:{1:{content:"$1"}}},chrome_ext_oneonone_plus_hangout_details:{message:"is video calling you via Hangouts"},chrome_ext_group_plus_hangout_details:{message:"has invited you to a group Hangout video call"},
quasar_video_details:{message:"is calling you with video chat"},quasar_voice_details:{message:"is calling you"},quasar_tip_connected:{message:"Status: Connected"},chrome_ext_tip_connected_missed_messages:{message:"Status: Connected\nMissed messages"},quasar_tip_connecting:{message:"Status: Connecting"},quasar_tip_reconnecting:{message:"Status: Reconnecting"},quasar_tip_disconnected:{message:"Status: Disconnected"},quasar_tip_not_login:{message:"Status: Not logged in"},quasar_tip_not_load:{message:"Status: Loading error"},
chrome_ext_menutext_unsigned_user:{message:"Not signed in"},quasar_menutext_unknown_user:{message:"Unknown"},quasar_menutext_feedback:{message:"Feedback"},quasar_menutext_settings:{message:"Options"},quasar_menutext_quit:{message:"Exit"},quasar_menutext_signout:{message:"Sign out"},chrome_ext_cannot_connect:{message:"Unable to connect to Google. Please check your internet connection."},quasar_try_now:{message:"Try now"},quasar_sign_in_to_start_talking:{message:"Sign in to start talking with friends"},
quasar_sign_in:{message:"Sign in"},chrome_app_description:{message:"Always stay connected with the new desktop app for Hangouts on ChromeOS and Windows."},chrome_app_connection_error_title:{message:"Connection Error"},chrome_app_connection_error_detail:{message:"Make sure you are connected to the Internet and try again"},chrome_app_connection_error_button:{message:"Try again"},chrome_app_welcome_message:{message:"Enjoy private and group conversations with text, photos, gifs, voice, video and more."},
chrome_app_chrome_signin_message:{message:"Sign in to Chrome to get started."},chrome_app_learn_more_message:{message:"Learn more"},chrome_app_signin_button:{message:"Sign in"},chrome_app_outdated_title:{message:"Update your Hangouts Chrome app"},chrome_app_outdated_detail:{message:"This app is out of date. There's a newer version available."},chrome_app_exit_title:{message:"Are you sure you want to quit Hangouts?"},chrome_app_exit_title_2:{message:"Do you want to quit Hangouts?"},chrome_app_exit_detail:{message:"You will not receive new messages or calls on this device"},
chrome_app_exit_detail_2:{message:"You can also choose to minimize it and continue to receive messages and calls."},chrome_app_exit_no:{message:"No"},chrome_app_exit_quit:{message:"Quit"},chrome_app_exit_minimize:{message:"Minimize"},chrome_app_osx_warning_message:{message:"Hangouts Chrome app is not fully supported on Mac OSX."},chrome_app_osx_warning_ack:{message:"OK, GOT IT"}};

}catch(e){_._DumpException(e)}
try{
window.addEventListener("load",function(){window.chrome.runtime.getBackgroundPage(function(a){a.__onPanelLoad(window)})},!1);
}catch(e){_._DumpException(e)}
}).call(this,this.default_panel);
// Google Inc.
