"use strict";this.default_settings=this.default_settings||{};(function(_){var window=this;
try{
_.aa=_.aa||{};_.k=this;_.ba="closure_uid_"+(1E9*Math.random()>>>0);_.m=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
try{
var ca,ea;ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};ea=function(a,b,c){return a.call.apply(a.bind,arguments)};
_.fa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.n=function(a,b,c){_.n=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:ca;return _.n.apply(null,arguments)};_.ga=function(a){return"function"==_.fa(a)};_.p=function(a){return"string"==typeof a};
_.ha=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};_.r=Array.prototype;_.ia=_.r.indexOf?function(a,b,c){return _.r.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.p(a))return _.p(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.ja=_.r.lastIndexOf?function(a,b,c){return _.r.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(_.p(a))return _.p(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.s=_.r.forEach?function(a,b,c){_.r.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.p(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.ka=_.r.filter?function(a,b,c){return _.r.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=_.p(a)?a.split(""):a,l=0;l<d;l++)if(l in g){var q=g[l];b.call(c,q,l,a)&&(e[f++]=q)}return e};_.ma=_.r.map?function(a,b,c){return _.r.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.p(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
_.na=_.r.reduce?function(a,b,c,d){d&&(b=(0,_.n)(b,d));return _.r.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,_.s)(a,function(c,g){e=b.call(d,e,c,g,a)});return e};_.pa=_.r.some?function(a,b,c){return _.r.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.p(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};
_.qa="StopIteration"in _.k?_.k.StopIteration:Error("d");t:{var ra=_.k.navigator;if(ra){var sa=ra.userAgent;if(sa){_.t=sa;break t}}_.t=""};var wa,ya,Aa;_.ta=-1!=_.t.indexOf("Opera")||-1!=_.t.indexOf("OPR");_.u=-1!=_.t.indexOf("Trident")||-1!=_.t.indexOf("MSIE");_.ua=-1!=_.t.indexOf("Gecko")&&-1==_.t.toLowerCase().indexOf("webkit")&&!(-1!=_.t.indexOf("Trident")||-1!=_.t.indexOf("MSIE"));_.va=-1!=_.t.toLowerCase().indexOf("webkit");wa=_.k.navigator||null;_.xa=wa&&wa.platform||"";ya=function(){var a=_.k.document;return a?a.documentMode:void 0};
_.za=function(){var a="",b;if(_.ta&&_.k.opera)return a=_.k.opera.version,_.ga(a)?a():a;_.ua?b=/rv\:([^\);]+)(\)|;)/:_.u?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:_.va&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(_.t))?a[1]:"");return _.u&&(b=ya(),b>(0,window.parseFloat)(a))?String(b):a}();Aa=_.k.document;_.Ba=Aa&&_.u?ya()||("CSS1Compat"==Aa.compatMode?(0,window.parseInt)(_.za,10):5):void 0;
_.k.ace_i18n={chrome_ext_short_name:{message:"Hangouts"},chrome_ext_description:{message:"Hangouts brings conversations to life with photos, emoji, and even group video calls for free."},quasar_chat_toast_info:{message:"Click to go to page..."},quasar_answer_button_text:{message:"Answer"},quasar_decline_button_text:{message:"Decline"},quasar_help:{message:"Help"},quasar_legend_startup_shutdown:{message:"Application"},chrome_ext_run_at_browser_start:{message:"Sign in to Hangouts when Chrome starts"},
chrome_ext_run_after_browser_close:{message:"Allow background mode"},chrome_ext_new_windows_topmost:{message:"Keep Hangouts on top of other windows"},quasar_label_tray_icon:{message:"Show system tray icon"},quasar_legend_notifications:{message:"Notifications"},quasar_label_all_notification:{message:"Disable notifications"},quasar_label_chat_notification:{message:"Disable chat notifications"},quasar_label_toast_timeout_chat:{message:"Allow chat notifications to timeout automatically"},quasar_label_toast_duration_chat:{message:"Timeout length (in seconds):"},
quasar_button_save:{message:"Ok"},quasar_button_apply:{message:"Apply"},quasar_button_cancel:{message:"Cancel"},chrome_ext_menutext_feedback:{message:"Send feedback"},quasar_feedback_server_uri:{message:"https://www.google.com/tools/feedback"},chrome_ext_feedback_subtitle:{message:"Send feedback"},chrome_ext_feedback_comments:{message:"Comments"},quasar_feedback_system_legend:{message:"System Information"},quasar_feedback_platform_label:{message:"Platform:"},quasar_feedback_user_agent_label:{message:"User Agent:"},
quasar_feedback_privacy_legend:{message:"Privacy Statement"},quasar_feedback_privacy_text:{message:"The description, product information, additional information and your email address will be sent to Google. See the Google Feedback Terms of Service. By submitting this content you are granting to Google the right to use it to improve our products and services. See our Privacy Policy."},quasar_feedback_submit_button:{message:"Send Feedback"},quasar_feedback_cancel_button:{message:"Cancel"},quasar_video_title:{message:"Video call from $1...",
placeholders:{1:{content:"$1"}}},quasar_voice_title:{message:"Voice call from $1...",placeholders:{1:{content:"$1"}}},quasar_group_chat_title:{message:"From group chat..."},quasar_chat_title:{message:"$1 says...",placeholders:{1:{content:"$1"}}},quasar_hangout_title:{message:"$1 is hanging out",placeholders:{1:{content:"$1"}}},chrome_ext_oneonone_plus_hangout_details:{message:"is video calling you via Hangouts"},chrome_ext_group_plus_hangout_details:{message:"has invited you to a group Hangout video call"},
quasar_video_details:{message:"is calling you with video chat"},quasar_voice_details:{message:"is calling you"},quasar_tip_connected:{message:"Status: Connected"},chrome_ext_tip_connected_missed_messages:{message:"Status: Connected\nMissed messages"},quasar_tip_connecting:{message:"Status: Connecting"},quasar_tip_reconnecting:{message:"Status: Reconnecting"},quasar_tip_disconnected:{message:"Status: Disconnected"},quasar_tip_not_login:{message:"Status: Not logged in"},quasar_tip_not_load:{message:"Status: Loading error"},
chrome_ext_menutext_unsigned_user:{message:"Not signed in"},quasar_menutext_unknown_user:{message:"Unknown"},quasar_menutext_feedback:{message:"Feedback"},quasar_menutext_settings:{message:"Options"},quasar_menutext_quit:{message:"Exit"},quasar_menutext_signout:{message:"Sign out"},chrome_ext_cannot_connect:{message:"Unable to connect to Google. Please check your internet connection."},quasar_try_now:{message:"Try now"},quasar_sign_in_to_start_talking:{message:"Sign in to start talking with friends"},
quasar_sign_in:{message:"Sign in"},chrome_app_description:{message:"Always stay connected with the new desktop app for Hangouts on ChromeOS and Windows."},chrome_app_connection_error_title:{message:"Connection Error"},chrome_app_connection_error_detail:{message:"Make sure you are connected to the Internet and try again"},chrome_app_connection_error_button:{message:"Try again"},chrome_app_welcome_message:{message:"Enjoy private and group conversations with text, photos, gifs, voice, video and more."},
chrome_app_chrome_signin_message:{message:"Sign in to Chrome to get started."},chrome_app_learn_more_message:{message:"Learn more"},chrome_app_signin_button:{message:"Sign in"},chrome_app_outdated_title:{message:"Update your Hangouts Chrome app"},chrome_app_outdated_detail:{message:"This app is out of date. There's a newer version available."},chrome_app_exit_title:{message:"Are you sure you want to quit Hangouts?"},chrome_app_exit_title_2:{message:"Do you want to quit Hangouts?"},chrome_app_exit_detail:{message:"You will not receive new messages or calls on this device"},
chrome_app_exit_detail_2:{message:"You can also choose to minimize it and continue to receive messages and calls."},chrome_app_exit_no:{message:"No"},chrome_app_exit_quit:{message:"Quit"},chrome_app_exit_minimize:{message:"Minimize"},chrome_app_osx_warning_message:{message:"Hangouts Chrome app is not fully supported on Mac OSX."},chrome_app_osx_warning_ack:{message:"OK, GOT IT"}};

}catch(e){_._DumpException(e)}
try{
var Ca,Da,Ea,Ha,Ia;Ca=function(a,b){return a<b?-1:a>b?1:0};Da={};Ea=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};_.Fa=function(){};_.Fa.prototype.next=function(){throw _.qa;};_.Fa.prototype.ha=function(){return this};_.Ga=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};Ha=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};
Ia=function(a,b){for(var c=0,d=(0,_.ha)(String(a)).split("."),e=(0,_.ha)(String(b)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var l=d[g]||"",q=e[g]||"",B=RegExp("(\\d*)(\\D*)","g"),K=RegExp("(\\d*)(\\D*)","g");do{var da=B.exec(l)||["","",""],P=K.exec(q)||["","",""];if(0==da[0].length&&0==P[0].length)break;c=Ca(0==da[1].length?0:(0,window.parseInt)(da[1],10),0==P[1].length?0:(0,window.parseInt)(P[1],10))||Ca(0==da[2].length,0==P[2].length)||Ca(da[2],P[2])}while(0==c)}return c};
_.Ja=function(a){var b=_.fa(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.v=function(a){return void 0!==a};_.Ka=function(a){return Da[a]||(Da[a]=0<=Ia(_.za,a))};_.La=function(a){if("function"==typeof a.B)return a.B();if(_.p(a))return a.split("");if(_.Ja(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ha(a)};
_.w=function(a,b){this.b={};this.a=[];this.j=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("f");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){"undefined"!=typeof _.w&&a instanceof _.w?(c=a.M(),d=a.B()):(c=_.Ga(a),d=Ha(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.w.prototype.V=function(){return this.c};_.w.prototype.B=function(){Ma(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.w.prototype.M=function(){Ma(this);return this.a.concat()};
_.Na=function(a,b){return Ea(a.b,b)};_.w.prototype.P=function(){return 0==this.c};_.w.prototype.clear=function(){this.b={};this.j=this.c=this.a.length=0};_.w.prototype.remove=function(a){return Ea(this.b,a)?(delete this.b[a],this.c--,this.j++,this.a.length>2*this.c&&Ma(this),!0):!1};
var Ma=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Ea(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],Ea(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.h=_.w.prototype;_.h.get=function(a,b){return Ea(this.b,a)?this.b[a]:b};_.h.set=function(a,b){Ea(this.b,a)||(this.c++,this.a.push(a),this.j++);this.b[a]=b};_.h.forEach=function(a,b){for(var c=this.M(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};
_.h.clone=function(){return new _.w(this)};_.h.ha=function(a){Ma(this);var b=0,c=this.a,d=this.b,e=this.j,f=this,g=new _.Fa;g.next=function(){for(;;){if(e!=f.j)throw Error("g");if(b>=c.length)throw _.qa;var g=c[b++];return a?g:d[g]}};return g};_.x=function(a){return"array"==_.fa(a)};_.Oa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};
_.y=function(a,b){function c(){}c.prototype=b.prototype;a.t=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ad=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};
_.Pa=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(_.Ja(a)||_.p(a))(0,_.s)(a,b,c);else{var d;if("function"==typeof a.M)d=a.M();else if("function"!=typeof a.B)if(_.Ja(a)||_.p(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=_.Ga(a);else d=void 0;for(var e=_.La(a),f=e.length,g=0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};_.Qa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};_.Ra=function(a,b){var c=(0,_.ia)(a,b),d;(d=0<=c)&&_.r.splice.call(a,c,1);return d};
_.Sa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.Sa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.y(_.Sa,Error);_.Sa.prototype.name="CustomError";_.Ta=function(a,b){var c=a.split("."),d=_.k;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.v(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};
_.Ua=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.Va=function(a){return"number"==typeof a};_.Wa=function(){};_.Xa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
var Ya;_.z=function(){};_.A=function(a,b,c,d){a.a={};b||(b=c?[c]:[]);a.p=c?String(c):void 0;a.b=0===c?-1:0;a.G=b;t:{if(a.G.length&&(b=a.G.length-1,(c=a.G[b])&&"object"==typeof c&&"number"!=typeof c.length)){a.j=b-a.b;a.c=c;break t}a.j=Number.MAX_VALUE}if(d)for(b=0;b<d.length;b++)c=d[b],c<a.j?(c+=a.b,a.G[c]=a.G[c]||[]):a.c[c]=a.c[c]||[]};_.C=function(a,b){return b<a.j?a.G[b+a.b]:a.c[b]};_.z.prototype.toString=function(){return this.G.toString()};_.D=function(a,b){Ya[a]=b;b.messageId=a};Ya={};
_.E=function(){this.D=this.D;this.j=this.j};_.E.prototype.D=!1;_.E.prototype.yb=function(){return this.D};_.E.prototype.C=function(){this.D||(this.D=!0,this.n())};_.G=function(a,b){_.Za(a,_.Ua(_.F,b))};_.Za=function(a,b){a.j||(a.j=[]);a.j.push(_.v(void 0)?(0,_.n)(b,void 0):b)};_.E.prototype.n=function(){if(this.j)for(;this.j.length;)this.j.shift()()};_.F=function(a){a&&"function"==typeof a.C&&a.C()};
_.$a=!_.u||_.u&&9<=_.Ba;!_.ua&&!_.u||_.u&&_.u&&9<=_.Ba||_.ua&&_.Ka("1.9.1");_.u&&_.Ka("9");var ab=function(a){ab[" "](a);return a};ab[" "]=_.Wa;_.cb=function(a,b){try{return ab(a[b]),!0}catch(c){}return!1};var db,eb;db=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;_.gb=function(a){if(eb){eb=!1;var b=_.k.location;if(b){var c=b.href;if(c&&(c=_.fb(c))&&c!=b.hostname)throw eb=!0,Error();}}return a.match(db)};eb=_.va;_.fb=function(a){return(a=_.gb(a)[3]||null)?(0,window.decodeURI)(a):a};
var hb=!_.u||_.u&&9<=_.Ba,ib=_.u&&!_.Ka("9");!_.va||_.Ka("528");_.ua&&_.Ka("1.9b")||_.u&&_.Ka("8")||_.ta&&_.Ka("9.5")||_.va&&_.Ka("528");_.ua&&!_.Ka("8")||_.u&&_.Ka("9");_.H=function(a,b){this.type=a;this.a=this.target=b;this.pc=!0};_.H.prototype.C=function(){};_.H.prototype.b=function(){this.pc=!1};var jb=function(a,b){_.H.call(this,a?a.type:"");this.a=this.target=null;this.clientY=this.clientX=0;this.c=this.state=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;c&&_.ua&&_.cb(c,"nodeName");this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.state=a.state;this.c=a;a.defaultPrevented&&this.b()}};_.y(jb,_.H); jb.prototype.b=function(){jb.t.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,ib)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var kb,mb;kb="closure_listenable_"+(1E6*Math.random()|0);_.lb=function(a){return!(!a||!a[kb])};mb=0;var nb=function(a,b,c,d,e){this.qa=a;this.proxy=null;this.src=b;this.type=c;this.Ua=!!d;this.$a=e;this.key=++mb;this.removed=this.Ta=!1},ob=function(a){a.removed=!0;a.qa=null;a.proxy=null;a.src=null;a.$a=null};var pb=function(a){this.src=a;this.a={};this.b=0};pb.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=qb(a,b,d,e);-1<g?(b=a[g],c||(b.Ta=!1)):(b=new nb(b,this.src,f,!!d,e),b.Ta=c,a.push(b));return b};pb.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=qb(e,b,c,d);return-1<b?(ob(e[b]),_.r.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var rb=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=_.Ra(a.a[c],b);d&&(ob(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d};pb.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,ob(d[e]);delete this.a[c];this.b--}return b}; var sb=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=qb(a,c,d,e));return-1<b?a[b]:null},qb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.qa==b&&f.Ua==!!c&&f.$a==d)return e}return-1};
var tb,ub,vb,Ab,Bb,Gb,Fb,Cb,zb,Hb;tb="closure_lm_"+(1E6*Math.random()|0);ub={};vb=0;_.wb=function(a,b,c,d,e){if(_.x(b)){for(var f=0;f<b.length;f++)_.wb(a,b[f],c,d,e);return null}c=_.xb(c);return _.lb(a)?a.listen(b,c,d,e):_.yb(a,b,c,!1,d,e)};_.yb=function(a,b,c,d,e,f){if(!b)throw Error("l");var g=!!e,l=zb(a);l||(a[tb]=l=new pb(a));c=l.add(b,c,d,e,f);if(c.proxy)return c;d=Ab();c.proxy=d;d.src=a;d.qa=c;a.addEventListener?a.addEventListener(b.toString(),d,g):a.attachEvent(Bb(b.toString()),d);vb++;return c};
Ab=function(){var a=Cb,b=hb?function(c){return a.call(b.src,b.qa,c)}:function(c){c=a.call(b.src,b.qa,c);if(!c)return c};return b};_.Db=function(a,b,c,d,e){if(_.x(b))for(var f=0;f<b.length;f++)_.Db(a,b[f],c,d,e);else c=_.xb(c),_.lb(a)?a.Fb(b,c,d,e):a&&(a=zb(a))&&(b=sb(a,b,c,!!d,e))&&_.Eb(b)};
_.Eb=function(a){if(_.Va(a)||!a||a.removed)return!1;var b=a.src;if(_.lb(b))return rb(b.U,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.Ua):b.detachEvent&&b.detachEvent(Bb(c),d);vb--;(c=zb(b))?(rb(c,a),0==c.b&&(c.src=null,b[tb]=null)):ob(a);return!0};Bb=function(a){return a in ub?ub[a]:ub[a]="on"+a};Gb=function(a,b,c,d){var e=1;if(a=zb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Ua==c&&!f.removed&&(e&=!1!==Fb(f,d))}return Boolean(e)};
Fb=function(a,b){var c=a.qa,d=a.$a||a.src;a.Ta&&_.Eb(a);return c.call(d,b)};
Cb=function(a,b){if(a.removed)return!0;if(!hb){var c;if(!(c=b))t:{c=["window","event"];for(var d=_.k,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break t}c=d}e=c;c=new jb(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){t:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break t}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,l=e.length-1;0<=l;l--)c.a=e[l],d&=Gb(e[l],f,!0,c);for(l=0;l<e.length;l++)c.a=e[l],d&=Gb(e[l],f,!1,c)}return d}return Fb(a, new jb(b,this))};zb=function(a){a=a[tb];return a instanceof pb?a:null};Hb="__closure_events_fn_"+(1E9*Math.random()>>>0);_.xb=function(a){if(_.ga(a))return a;a[Hb]||(a[Hb]=function(b){return a.handleEvent(b)});return a[Hb]};
_.Ib=function(a){_.A(this,a,"h_cc",[])};_.y(_.Ib,_.z);_.D("h_cc",_.Ib);_.Ib.prototype.Z=function(){return _.C(this,19)};_.I=function(a){_.E.call(this);this.I=a;this.g={}};_.y(_.I,_.E);var Jb=[];_.I.prototype.listen=function(a,b,c,d){return _.Lb(this,a,b,c,d)};_.Lb=function(a,b,c,d,e,f){_.x(c)||(c&&(Jb[0]=c.toString()),c=Jb);for(var g=0;g<c.length;g++){var l=_.wb(b,c[g],d||a.handleEvent,e||!1,f||a.I||a);if(!l)break;a.g[l.key]=l}return a};
_.I.prototype.Fb=function(a,b,c,d,e){if(_.x(b))for(var f=0;f<b.length;f++)this.Fb(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.I||this,c=_.xb(c),d=!!d,b=_.lb(a)?sb(a.U,String(b),c,d,e):a?(a=zb(a))?sb(a,b,c,d,e):null:null,b&&(_.Eb(b),delete this.g[b.key]);return this};_.I.prototype.removeAll=function(){_.Qa(this.g,_.Eb);this.g={}};_.I.prototype.n=function(){_.I.t.n.call(this);this.removeAll()};_.I.prototype.handleEvent=function(){throw Error("m");};
var Mb,Nb,Ob;Mb=function(a){_.k.setTimeout(function(){throw a;},0)};_.Pb=function(a,b){var c=a;b&&(c=(0,_.n)(a,b));!_.ga(_.k.setImmediate)||_.k.Window&&_.k.Window.prototype.setImmediate==_.k.setImmediate?(Nb||(Nb=Ob()),Nb(c)):_.k.setImmediate(c)};
Ob=function(){var a=_.k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(a=function(){var a=window.document.createElement("iframe");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.n)(function(a){if(("*"==d||a.origin==d)&&
a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&-1==_.t.indexOf("Trident")&&-1==_.t.indexOf("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.v(c.next)){c=c.next;var a=c.Rb;c.Rb=null;a()}};return function(a){d.next={Rb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("script")? function(a){var b=window.document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.k.setTimeout(a,0)}};
var Vb=function(a,b){Qb||Rb();Sb||(Qb(),Sb=!0);Tb.push(new Ub(a,b))},Qb,Rb=function(){if(_.k.Promise&&_.k.Promise.resolve){var a=_.k.Promise.resolve();Qb=function(){a.then(Wb)}}else Qb=function(){_.Pb(Wb)}},Sb=!1,Tb=[],Wb=function(){for(;Tb.length;){var a=Tb;Tb=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.a.call(c.b)}catch(d){Mb(d)}}}Sb=!1},Ub=function(a,b){this.a=a;this.b=b};
_.J=function(){_.E.call(this);this.U=new pb(this);this.L=this;this.u=null};_.y(_.J,_.E);_.J.prototype[kb]=!0;_.h=_.J.prototype;_.h.addEventListener=function(a,b,c,d){_.wb(this,a,b,c,d)};_.h.removeEventListener=function(a,b,c,d){_.Db(this,a,b,c,d)};_.h.n=function(){_.J.t.n.call(this);this.U&&this.U.removeAll(void 0);this.u=null};_.h.listen=function(a,b,c,d){return this.U.add(String(a),b,!1,c,d)};_.h.Fb=function(a,b,c,d){return this.U.remove(String(a),b,c,d)}; _.h.da=function(a,b,c){a=this.U.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.Ua==b){var g=f.qa,l=f.$a||f.src;f.Ta&&rb(this.U,f);d=!1!==g.call(l,c)&&d}}return d&&0!=c.pc};
var Xb=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},Yb=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var $b;$b=function(a,b){this.b=0;this.f=void 0;this.a=this.c=null;this.j=this.e=!1;try{var c=this;a.call(b,function(a){Zb(c,2,a)},function(a){Zb(c,3,a)})}catch(d){Zb(this,3,d)}};_.bc=function(){var a,b=new $b(function(b){a=b});return new ac(b,a)};$b.prototype.then=function(a,b,c){return cc(this,_.ga(a)?a:null,_.ga(b)?b:null,c)};Xb($b);
var fc=function(a){0==a.b&&Vb(function(){var a=new dc(void 0);ec(this,a)},a)},ec=function(a,b){if(0==a.b)if(a.c){var c=a.c;if(c.a){for(var d=0,e=-1,f=0,g;g=c.a[f];f++)if(g=g.Ea)if(d++,g==a&&(e=f),0<=e&&1<d)break;0<=e&&(0==c.b&&1==d?ec(c,b):(d=c.a.splice(e,1)[0],gc(c,d,3,b)))}}else Zb(a,3,b)},ic=function(a,b){a.a&&a.a.length||2!=a.b&&3!=a.b||hc(a);a.a||(a.a=[]);a.a.push(b)},cc=function(a,b,c,d){var e={Ea:null,jc:null,lc:null};e.Ea=new $b(function(a,g){e.jc=b?function(c){try{var e=b.call(d,c);a(e)}catch(B){g(B)}}:
a;e.lc=c?function(b){try{var e=c.call(d,b);!_.v(e)&&b instanceof dc?g(b):a(e)}catch(B){g(B)}}:g});e.Ea.c=a;ic(a,e);return e.Ea};$b.prototype.g=function(a){this.b=0;Zb(this,2,a)};$b.prototype.h=function(a){this.b=0;Zb(this,3,a)};
var Zb=function(a,b,c){if(0==a.b){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(Yb(c)){a.b=1;c.then(a.g,a.h,a);return}if(_.Oa(c))try{var d=c.then;if(_.ga(d)){jc(a,c,d);return}}catch(e){b=3,c=e}}a.f=c;a.b=b;hc(a);3!=b||c instanceof dc||kc(a,c)}},jc=function(a,b,c){a.b=1;var d=!1,e=function(b){d||(d=!0,a.g(b))},f=function(b){d||(d=!0,a.h(b))};try{c.call(b,e,f)}catch(g){f(g)}},hc=function(a){a.e||(a.e=!0,Vb(a.k,a))};
$b.prototype.k=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;b++)gc(this,a[b],this.b,this.f)}this.e=!1};var gc=function(a,b,c,d){if(2==c)b.jc(d);else{if(b.Ea)for(;a&&a.j;a=a.c)a.j=!1;b.lc(d)}},kc=function(a,b){a.j=!0;Vb(function(){a.j&&lc.call(null,b)})},lc=Mb,dc=function(a){_.Sa.call(this,a)};_.y(dc,_.Sa);dc.prototype.name="cancel";var ac=function(a,b){this.b=a;this.a=b};
var mc,nc,oc,pc,qc,rc,sc,vc,wc,xc,yc,zc,Ac;sc=rc=qc=pc=oc=nc=mc=!1;var tc=_.t;tc&&(-1!=tc.indexOf("Firefox")?mc=!0:-1!=tc.indexOf("Camino")?nc=!0:-1!=tc.indexOf("iPad")?pc=!0:-1!=tc.indexOf("iPhone")||-1!=tc.indexOf("iPod")?oc=!0:-1!=tc.indexOf("Chrome")?rc=!0:-1!=tc.indexOf("Android")?qc=!0:-1!=tc.indexOf("Safari")&&(sc=!0));_.uc=mc;vc=nc;wc=oc;xc=pc;yc=qc;zc=rc;Ac=sc;
_.L=function(a){this.a=a};_.L.prototype.toString=function(){return this.a};_.Bc=new _.L("fJuxOc");_.Cc=new _.L("ZtVrH");_.Dc=new _.L("zZa4xc");_.Ec=new _.L("pVbxBc");_.Fc=new _.L("byfTOb");_.Gc=new _.L("LEikZe");_.Hc=new _.L("rJmJrc");_.Ic=new _.L("a");_.Jc=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")};_.Kc=function(){return 0<=window.navigator.userAgent.indexOf("CrOS")};_.Lc=function(a,b){this.j=a||"e";this.c=null!=a&&"p"==a?"e":"p";this.b=this.e=null;this.h=b||"u";this.a=this.g=null;this.f=[]};_.Lc.prototype.message=function(){var a={};a.i=this.a;a.m=this.f;a.r=this.h;a.o=this.g;a.s=this.b;a.st=this.c;a.d=this.e;a.dt=this.j;return a};_.Ta("ace.base.Message.prototype.message",_.Lc.prototype.message);
_.Mc=function(a,b){for(var c in b)switch(c){case "r":a.h=b[c];break;case "i":a.a=b[c];break;case "m":a.f=b[c];break;case "o":a.g=b[c];break;case "s":a.b=b[c];break;case "d":a.e=b[c];break;case "st":a.c=b[c];break;case "dt":a.j=b[c]}return a};_.Nc=function(a,b,c){null!=b&&(a.b=b,null!=c&&(a.c=c))};_.Oc=function(a,b){null!=b&&(a.a=b)};_.Pc=function(a,b){"object"==typeof b?a.f=b:a.f=[b]};_.Lc.prototype.source=function(){return this.b};_.Lc.prototype.target=function(){return this.e}; _.Lc.prototype.content=function(){return this.f};
_.Qc=function(a,b,c,d,e){_.E.call(this);this.b=a;this.Qa=b;this.a=typeof b;this.Ab=c?c:!1;this.ba=!0;this.wb=d?d:!1;this.pb=e?e:!1};_.y(_.Qc,_.E);_.h=_.Qc.prototype;_.h.n=function(){_.Qc.t.n.call(this);this.b="";this.Qa=null;this.a=""};_.h.id=function(){return this.b};_.h.type=function(){return this.a};_.h.F=function(){return this.Qa};_.h.setEnabled=function(a){this.ba=a};
var Rc=function(a){return(a=a.exec(_.t))?a[1]:""},Sc=function(){if(_.uc)return Rc(/Firefox\/([0-9.]+)/);if(_.u||_.ta)return _.za;if(zc)return Rc(/Chrome\/([0-9.]+)/);if(Ac)return Rc(/Version\/([0-9.]+)/);if(wc||xc){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.t))return a[1]+"."+a[2]}else{if(yc)return(a=Rc(/Android\s+([0-9.]+)/))?a:Rc(/Version\/([0-9.]+)/);if(vc)return Rc(/Camino\/([0-9.]+)/)}return""}();
_.Uc=function(a){_.E.call(this);this.a=new _.w;this.b=["https://talkgadget.google.com/talkgadget/notifier-js","","https://test.talkgadget.google.com/talkgadget/notifier-js?jsmode=debug_unobfuscated"];a&&_.Tc(this,a)};_.y(_.Uc,_.E);_.Vc=0<=Ia(Sc,"23.0.1262.0")&&!_.Kc();_.Uc.prototype.n=function(){_.Uc.t.n.call(this);for(var a=this.a.M(),b=0;b<a.length;++b)_.F(this.a.get(a[b]));delete this.a};_.Uc.prototype.getItem=function(a){return _.Na(this.a,a)?this.a.get(a):null};
_.Uc.prototype.setItem=function(a){this.a.set(a.id(),a)};_.Tc=function(a,b){for(var c in b){var d=b[c],e=null;_.Na(a.a,c)?(e=a.a.get(c),e.Qa=d.value,d.changed&&(e.pb=d.changed)):(e=new _.Qc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
_.Yc=function(){this.c=new _.w;this.a=null;this.b=!1;this.a=new Wc;this.b=!0;_.Xc(this)};_.Yc.ua=function(){return _.Yc.a?_.Yc.a:_.Yc.a=new _.Yc};_.Xc=function(a,b){var c=b||_.Wa;a.b?c():window.chrome.storage.local.get((0,_.n)(function(a){if(!this.b){for(var b in a)this.c.set(b,a[b]);this.b=!0}c()},a))};_.Yc.prototype.get=function(a){return this.a.get(a)};_.Yc.prototype.set=function(a,b){var c=_.bc();this.a.set(a,b);c.a(void 0);return c.b};_.Yc.prototype.remove=function(a){this.a.remove(a)};
_.Yc.prototype.clear=function(){this.a.clear()};var Wc=function(){this.a=window.localStorage};Wc.prototype.clear=function(){this.a.clear()};Wc.prototype.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=Ya[a[0]];if(!b)throw Error("i`"+a[0]);a=new b(a)}}else a=null;return a};Wc.prototype.set=function(a,b){var c=null;b instanceof _.z&&(b=b.G,c="jspb");var d={};d.data=b;d.timestamp=(0,_.m)();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}}; Wc.prototype.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
_.Zc=function(a,b){this.b=a;this.a=b;this.constructor.Pb||(this.constructor.Pb={});this.constructor.Pb[this.toString()]=this};_.Zc.prototype.toString=function(){this.c||(this.c=this.b.a+":"+this.a);return this.c};_.M=function(a,b){_.Zc.call(this,a,b)};_.y(_.M,_.Zc);_.$c=function(a){this.a=a};_.ad=new _.$c("lib");/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.bd=function(a,b){this.j=[];this.u=b||null;this.b=this.a=!1;this.c=void 0;this.l=this.p=this.f=!1;this.e=0;this.h=null;this.q=0};_.bd.prototype.k=function(a,b){this.f=!1;_.cd(this,a,b)};_.cd=function(a,b,c){a.a=!0;a.c=c;a.b=!b;dd(a)};_.fd=function(a){if(a.a){if(!a.l)throw new ed;a.l=!1}};_.bd.prototype.g=function(a){_.fd(this);_.cd(this,!0,a)};_.gd=function(a,b,c,d){a.j.push([b,c,d]);a.a&&dd(a)};
_.bd.prototype.then=function(a,b,c){var d,e,f=new $b(function(a,b){d=a;e=b});_.gd(this,d,function(a){"undefined"!=typeof _.hd&&a instanceof _.hd?fc(f):e(a)});return f.then(a,b,c)};Xb(_.bd);
var id=function(a){return(0,_.pa)(a.j,function(a){return _.ga(a[1])})},dd=function(a){if(a.e&&a.a&&id(a)){var b=a.e,c=jd[b];c&&(_.k.clearTimeout(c.Wa),delete jd[b]);a.e=0}a.h&&(a.h.q--,delete a.h);for(var b=a.c,d=c=!1;a.j.length&&!a.f;){var e=a.j.shift(),f=e[0],g=e[1],e=e[2];if(f=a.b?g:f)try{var l=f.call(e||a.u,b);_.v(l)&&(a.b=a.b&&(l==b||l instanceof Error),a.c=b=l);Yb(b)&&(d=!0,a.f=!0)}catch(q){b=q,a.b=!0,id(a)||(c=!0)}}a.c=b;d&&(l=(0,_.n)(a.k,a,!0),d=(0,_.n)(a.k,a,!1),b instanceof _.bd?(_.gd(b,
l,d),b.p=!0):b.then(l,d));c&&(b=new kd(b),jd[b.Wa]=b,a.e=b.Wa)},ed=function(){_.Sa.call(this)};_.y(ed,_.Sa);ed.prototype.message="Deferred has already fired";ed.prototype.name="AlreadyCalledError";var kd=function(a){this.Wa=_.k.setTimeout((0,_.n)(this.b,this),0);this.a=a};kd.prototype.b=function(){delete jd[this.Wa];throw this.a;};var jd={};

}catch(e){_._DumpException(e)}
try{
var md;_.ld=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)};md=function(a,b){for(var c=_.p(a)?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)};_.od=function(a){_.E.call(this);this.c={};this.h={};this.k={};this.e={};this.l={};this.q={};this.p=a?a.ta():new _.J;this.w=!a;this.f=null;a?(this.f=a,this.k=a.k,this.e=a.e,this.h=a.h,this.l=a.l):(0,_.m)();a=nd(this);this!=a&&(a.g?a.g.push(this):a.g=[this])};_.y(_.od,_.E);var nd=function(a){for(;a.f;)a=a.f;return a};_.od.prototype.get=function(a){var b=this.b(a);if(null==b)throw new pd(a);return b};
_.od.prototype.b=function(a){for(var b=this;b;b=b.f){if(b.D)throw Error("q");if(b.c[a])return b.c[a][0];if(b.q[a])break}if(b=this.k[a]){b=b(this);if(null==b)throw Error("r`"+a);this.a(a,b);return b}return null};_.od.prototype.a=function(a,b,c){if(this.D)c||_.F(b);else{this.c[a]=[b,!c];b=qd(this,this,a);for(c=0;c<b.length;c++)b[c].g(null);delete this.h[a]}};_.od.prototype.u=function(){var a=_.rd;if(!this.c[a])throw Error("s`"+a);var b=this.c[a];delete this.c[a];b[1]&&_.F(b[0])};
var qd=function(a,b,c){var d=[],e=a.e[c];e&&(md(e,function(a){var c;t:{for(c=a.Qb;c;){if(c==b){c=!0;break t}c=c.f}c=!1}c&&(d.push(a.Bd),_.Ra(e,a))}),0==e.length&&delete a.e[c]);return d},sd=function(a,b){a.e&&_.Pa(a.e,function(a,d,e){md(a,function(d){d.Qb==b&&_.Ra(a,d)});0==a.length&&delete e[d]})};
_.od.prototype.n=function(){if(nd(this)==this){var a=this.g;if(a)for(;a.length;)a[0].C()}else for(var a=nd(this).g,b=0;b<a.length;b++)if(a[b]==this){a.splice(b,1);break}for(var c in this.c)a=this.c[c],a[1]&&"undefined"!=typeof a[0].C&&a[0].C();this.c=null;this.w&&this.p.C();sd(this,this);this.e=null;_.F(this.v);this.q=this.v=null;_.od.t.n.call(this)};_.od.prototype.ta=function(){return this.p};var pd=function(a){_.Sa.call(this);this.id=a;this.message='Service for "'+a+'" is not registered'}; _.y(pd,_.Sa);var td=new _.$c("fva");new _.M(td,1);

}catch(e){_._DumpException(e)}
try{
_.Qe=function(){return window.chrome.runtime.getURL("feedbackdialog.html")};
}catch(e){_._DumpException(e)}
try{
_.Hh=function(a){for(var b=a.a.M(),c={},d=0;d<b.length;d++){var e=b[d],f=a.a.get(e);c[e]={value:f.F(),type:f.type(),multiple:f.Ab,disabled:!f.ba,inverse:f.wb,changed:f.pb}}return c};_.Ih=function(a,b){return _.p(b)?a.getElementById(b):b};_.S=function(a){return _.Ih(window.document,a)}; _.T=function(a){var b;b=b||[];b.length||(b[0]="");var c=window.chrome.i18n.getMessage(a,b);if(c)return c;(c=(c=_.k.ace_i18n[a.toLowerCase()])?c.message:_.k.ace_i18n["MSG_"+a])&&(c=c.replace("$1",b[0]).replace("$2",b[1]).replace("$3",b[2]));return c};

}catch(e){_._DumpException(e)}
try{
var qn=function(a,b){for(var c=a.split("%s"),d="",e=Array.prototype.slice.call(arguments,1);e.length&&1<c.length;)d+=c.shift()+e.shift();return d+c.join("%s")},rn=function(a){_.E.call(this);this.e=_.Jc("setting",""+(0,_.m)());this.c=null;this.b=new _.I;_.G(this,this.b);this.a=new _.w;this.f=a.get(_.Ic);this.b.listen(window,"unload",this.C)};_.y(rn,_.E);_.Ta("ace.ui.SettingsDialog",rn);_.Ta("ace.ui.SettingsDialog",rn);
rn.prototype.h=function(){window.document.title=_.T("CHROME_EXT_SHORT_NAME");this.c=window.chrome.runtime.connect({name:this.e});var a=this;this.c.onMessage.addListener(function(b){switch(_.Mc(new _.Lc,b).a){case "focus":sn(a);a.sendMessage("extensionLibrary",["selectTab",a.e,!0,!0]);window.focus();break;case "close":a.g()}});this.a.set("StartOnBrowserLaunch",["BrowserStartup",1]);this.a.set("StopOnBrowserClose",["Shutdown",1]);this.a.set("TopMost",["TopMost",1]);this.a.set("TrayIcon",["TrayIcon",
1]);_.ld(_.S("fieldsetDestPage"));un("legendApp",_.T("QUASAR_LEGEND_STARTUP_SHUTDOWN"));un("legendNotice",_.T("QUASAR_LEGEND_NOTIFICATIONS"));vn(this,"StartOnBrowserLaunch",_.T("CHROME_EXT_RUN_AT_BROWSER_START"));vn(this,"StopOnBrowserClose",_.T("CHROME_EXT_RUN_AFTER_BROWSER_CLOSE"));vn(this,"TrayIcon",_.T("QUASAR_LABEL_TRAY_ICON"));_.Vc?vn(this,"TopMost",_.T("CHROME_EXT_NEW_WINDOWS_TOPMOST")):wn(this,"TopMost");_.Kc()&&wn(this,"TrayIcon");sn(this);var b=_.S("feedbackLink");b.innerText=_.T("CHROME_EXT_MENUTEXT_FEEDBACK");
b.href=_.Qe();b=_.S("helpLink");b.innerText=_.T("QUASAR_HELP");b.href=qn("https://support.google.com/hangouts?p=help&hl=%s",window.chrome.i18n.getMessage("@@ui_locale"));this.l=_.S("buttonSave");this.l.innerText=_.T("QUASAR_BUTTON_SAVE");this.b.listen(this.l,"click",(0,_.n)(this.p,this),!1);this.k=_.S("buttonCancel");this.k.innerText=_.T("QUASAR_BUTTON_CANCEL");this.b.listen(this.k,"click",(0,_.n)(this.g,this),!1)};rn.prototype.init=rn.prototype.h;
var xn=function(a,b,c){var d=[];b=b+a.a.get(c)[0];a=a.a.get(c)[1];if(1<a)for(c=0;c<a;c++)d.push(_.S(b+c));else d.push(_.S(b));return d},sn=function(a){for(var b=new _.Uc(a.f.get("settings")),c=a.a.M(),d=0;d<c.length;d++){var e=b.getItem(c[d]);if(e){var f=xn(a,"field",c[d]);if(e.Ab){var g=e.F();0<=g&&f[g]&&(f[g].checked=!0)}else f[0]&&("boolean"==e.a?e.wb?f[0].checked=!e.F():f[0].checked=e.F():f[0].value=e.F());if(!e.ba)for(e=xn(a,"label",c[d]),g=0;g<e.length;g++)e[g]&&(e[g].disabled=!0),f[g]&&(f[g].disabled=
!0)}}},un=function(a,b){var c=_.S(a);c&&(c.innerText=b)},vn=function(a,b,c){var d=a.a.get(b)[0];a=a.a.get(b)[1];if(1<a)for(b=0;b<a;b++){var e=_.S("label"+d+b);e&&c&&(e.innerText=c[b])}else(e=_.S("label"+d))&&c&&(e.innerText=c)},wn=function(a,b){var c=a.a.get(b)[0],d=_.S("field"+c);(d=(c=(c=_.S("label"+c)||d)&&c.parentNode)&&c.parentNode)&&d.removeChild(c)};
rn.prototype.p=function(){for(var a=new _.Uc(this.f.get("settings")),b=this.a.M(),c=0;c<b.length;c++){var d=a.getItem(b[c]);if(d){var e=xn(this,"field",b[c]),f=d.F();if(d.Ab){for(var g=-1,l=0;l<e.length;l++)if(e[l]&&e[l].checked){g=l;break}-1==g&&(g=0);d.Qa=g}else e[0]&&(d.Qa="boolean"==d.a?d.wb?!e[0].checked:e[0].checked:e[0].value);f!=d.F()&&(d.pb=!0,a.setItem(d))}}this.f.set("settings",_.Hh(a));this.g()};
rn.prototype.g=function(){this.sendMessage("settingsManager",["updateSettingsFromStorage"]);window.close()};rn.prototype.sendMessage=function(a,b,c){c=c?c:""+(0,_.m)();var d=new _.Lc;_.Nc(d,this.e,"p");null!=a&&(d.g=a);_.Oc(d,c);_.Pc(d,b);this.c&&this.c.postMessage(d.message())};
window.addEventListener("load",function(){_.Xc(_.Yc.ua(),function(){var a=new _.od;a.a(_.Ic,_.Yc.ua());(new rn(a)).h()})},!1);
}catch(e){_._DumpException(e)}
}).call(this,this.default_settings);
// Google Inc.
