// Generated by CoffeeScript 1.8.0
(function() {
  var injectContentScripts;

  injectContentScripts = function() {
    var content_scripts, insertLocation, manifest, script, scriptElement, scriptInfo, style, styleElement, _i, _j, _len, _len1, _ref, _results;
    manifest = chrome.runtime.getManifest();
    content_scripts = manifest.content_scripts;
    insertLocation = document.head.firstChild;
    _results = [];
    for (_i = 0, _len = content_scripts.length; _i < _len; _i++) {
      scriptInfo = content_scripts[_i];
      if (scriptInfo.matches.indexOf("<all_urls>") === -1) {
        continue;
      }
      if (scriptInfo.js) {
        _ref = scriptInfo.js;
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          script = _ref[_j];
          scriptElement = document.createElement("script");
          scriptElement.type = "text/javascript";
          scriptElement.async = false;
          scriptElement.src = chrome.runtime.getURL(script);
          insertLocation.parentElement.insertBefore(scriptElement, insertLocation);
        }
      }
      if (scriptInfo.css) {
        _results.push((function() {
          var _k, _len2, _ref1, _results1;
          _ref1 = scriptInfo.css;
          _results1 = [];
          for (_k = 0, _len2 = _ref1.length; _k < _len2; _k++) {
            style = _ref1[_k];
            styleElement = document.createElement("link");
            styleElement.rel = "stylesheet";
            styleElement.type = "text/css";
            styleElement.href = chrome.runtime.getURL(style);
            _results1.push(insertLocation.parentElement.insertBefore(styleElement, insertLocation));
          }
          return _results1;
        })());
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  injectContentScripts();

}).call(this);
